### ISSUE TITLE
Timeout error (part 2)

### ISSUE THREAD

**Issue by macirex** [cmp-202/ssh2shell#10]
Hello cmp,

I´m sorry to bother you again but I´ve encountered the another time out issue.

Let me provide some context first:

A group of servers I administer have some restricted policies:

- Root and application domain users are inaccessible via ssh.
- None of the application users have password.
- There´s only one user available for ssh connection, it is used for everything and it has limited permissions, for references this will be called "simpleuser". 
- Only way to administer a server is to connect via ssh to the "simpleuser" and then do a su to root. 

Basically the flow goes like this: 
Login -> su - root -> su - domainapp ->  [Here I do what I need to do]   

The list of commands I´m trying is:
  commands:           [
    "su - root", 
    "echo hello" 
    "su - webapp",
    "ls -lthr",
  ]

I managed to log into root using the event on commandProcessing and writing the password directly into the stream:

<code>
SSH.on ('commandProcessing', function onCommandProcessing( command, response, sshObj, stream ) {   
            if (command.match(/root/)&& response.indexOf("Password:") != -1) {
	           if (!admin)
		   {
			stream.write('password\n');
			admin = true;
		    }
              });
</code>

After that, I try to do another su, this time to the domain I need to check but it fails with: 
Timeout error: 10.164.12.159: Command timed out after 5 seconds

Here´s the output my app generates:

Connected
Running commands Now
10.164.12.159 verbose:Your password will expire in 8 days.
[user01@machine043]>
10.164.12.159 verbose:su - root
Password:
[root@machine043]>
10.164.12.159 verbose:echo hello
hello
[root@machine043]>
Timeout error: 10.164.12.159: Command timed out after 5 seconds
Completed

Any commands I execute before trying the second su, it works perfectly but after the second su I only get Timeout error.

This is the full session responses:
Connected to 10.164.12.159
su - root
Password:
[root@machine043]> echo hello
hello
[root@machine043]> su - webapp
machine043@webapp:~>

Any insights you could share with me?
Could this be happening because the name of the prompt is different from the first two?  Where simpleuser and root has username@machinename and webapp has machinename@username?

Btw, merry christmas! and have a happy new year!

**Comment by cmp-202** [comment]
you can increase the timeout value to allow for the scripts to run `host.idleTimeOut = 10000`

**Comment by cmp-202** [comment]
could you show me the debug output.

**Comment by macirex** [comment]
Sadly I'm not near my work computer, I will send you the debug output after the holydays.

**Comment by macirex** [comment]
I couldn´t stand it... it bugged me too much... so I went and tested it on my virtual machine. I simulated the same scenario on my improvised server and it seems it is not an issue of the environment of the user... it times outs after the second su.

I will add the code I´m testing and the response I get after executing.

**Comment by macirex** [comment]
var SSH2Shell = require('../lib/ssh2shell');
var sshObj = {
  server:             {     
	host:         "192.168.56.2",
	port:         "22",
    userName:     "simpleuser",
    password:     "test",
	passPhrase:   "",
    privateKey:   ""
  },
  commands:           [
    "su - root",
	"echo hello",
	"ls -lthr",
	"ls -lthr",
	"ls -lthr",
	"ls -lthr",
	"sudo su - e09048",
	"ls -lthr"
  ],
  msg: {
    send: function( message ) {
      console.log(message);
    }
  },
  verbose:             true,  //optional default:false
  debug:               true,  //optional default:false
  connectedMessage:   "Connected",
  readyMessage:       "Running commands Now",
  closedMessage:      "Completed"
};

var SSH = new SSH2Shell(sshObj);

var admin = false;
SSH.on ('ready', function onReady( command, response, sshObj ) {
});

SSH.on ('commandComplete', function onCommandComplete( command, response, sshObj ) {
  });

SSH.on ('commandProcessing', function onCommandProcessing( command, response, sshObj, stream ) {
   if (command.match(/root/)&& response.indexOf("Password:") != -1) {

	if (!admin)
		{
			stream.write('test\n');
			admin = true;
		}
	}
 });
 
SSH.on ('end', function onEnd( sessionText, sshObj ) {	
    sshObj.msg.send("\nThis is the full session responses:\n" + sessionText);
  });
 
SSH.connect();

**Comment by macirex** [comment]
This is the response ouput:

C:\node\node_modules\ssh2shell\test>node test2.js
Connected
Running commands Now
192.168.56.2: normal prompt
192.168.56.2 verbose:Last login: Wed Dec 31 23:48:19 2014 from 192.168.56.100

[simpleuser@weblogic1 ~]$
su - root
192.168.56.2: next command: su - root
192.168.56.2: normal prompt
192.168.56.2 verbose:su - root
Password:
[root@weblogic1 ~]#
echo hello
192.168.56.2: next command: echo hello
192.168.56.2: normal prompt
192.168.56.2 verbose:echo hello
hello
[root@weblogic1 ~]#
ls -lthr
192.168.56.2: next command: ls -lthr
192.168.56.2: normal prompt
192.168.56.2 verbose:ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]#
ls -lthr
192.168.56.2: next command: ls -lthr
192.168.56.2: normal prompt
192.168.56.2 verbose:ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]#
ls -lthr
192.168.56.2: next command: ls -lthr
192.168.56.2: normal prompt
192.168.56.2 verbose:ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]#
ls -lthr
192.168.56.2: next command: ls -lthr
192.168.56.2: normal prompt
192.168.56.2 verbose:ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]#
sudo su - e09048
192.168.56.2: next command: sudo su - e09048
Timeout error: 192.168.56.2: Command timed out after 5 seconds
Completed

This is the full session responses:
Connected to 192.168.56.2
su - root
Password:
[root@weblogic1 ~]# echo hello
hello
[root@weblogic1 ~]# ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]# ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]# ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]# ls -lthr
total 76K
-rw-r--r--. 1 root root  11K Jul 30 11:13 install.log.syslog
-rw-r--r--. 1 root root  54K Jul 30 11:23 install.log
-rw-------. 1 root root 1.7K Jul 30 11:25 anaconda-ks.cfg
[root@weblogic1 ~]# sudo su - e09048
[e09048@weblogic1 ~]$

**Comment by cmp-202** [comment]
can you try:

```javascript
var sshObj = {
	server: {
		host: "192.168.56.2",
		port: "22",
		userName: "simpleuser",
		password: "test",
		passPhrase: "",
		privateKey: ""
	},
	commands: [
	"msg:Changing to other user",
	"sudo su e09048",
	"msg:Test a dir listing",
	"ls -lthr"
	],
	msg: {
		send: function( message ) {
		console.log(message);
		}
	},
	verbose: true, //optional default:false
	debug: true, //optional default:false
	connectedMessage: "Connected",
	readyMessage: "Running commands Now",
	closedMessage: "Completed"
};

var SSH = new SSH2Shell(sshObj);

SSH.on ('end', function onEnd( sessionText, sshObj ) {
	sshObj.msg.send("\nThis is the full session responses:\n" + sessionText);
});
SSH.connect();
```

**Comment by cmp-202** [comment]
What Linux flavor are you working with it might be worth me spinning up a VM to test at my end. It currently is tested on Ubuntu server.

**Comment by macirex** [comment]
I´m working on redhat, linux oracle and some solaris machines. Will try tomorrow on a debian distribution.

**Comment by macirex** [comment]
C:\node\node_modules\ssh2shell\test>node test3.js
Connected
Running commands Now
192.168.56.2: normal prompt
192.168.56.2 verbose:Last login: Wed Dec 31 22:49:10 2014 from 192.168.56.100

[root@weblogic1 ~]#
192.168.56.2: Changing to other user
sudo su e09048
192.168.56.2: next command: sudo su e09048
Timeout error: 192.168.56.2: Command timed out after 5 seconds
Completed

This is the full session responses:
Connected to 192.168.56.2
sudo su e09048
[e09048@weblogic1 root]$

C:\node\node_modules\ssh2shell\test>

**Comment by cmp-202** [comment]
hmm interesting it looks like it is getting to the prompt but it is not being detected correctly. I will do some testing later tonight.

**Comment by macirex** [comment]
It seems it also does not works on a debian distribution: 

C:\node\node_modules\ssh2shell\test>node test3.js
Connected
Running commands Now
192.168.56.102: normal prompt
192.168.56.102 verbose:Linux kali 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1 (
2014-06-07) x86_64

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Dec  9 13:41:41 2014 from 192.168.11.108

root@kali:~#
192.168.56.102: Changing to other user
sudo su macirex
192.168.56.102: next command: sudo su macirex
Timeout error: 192.168.56.102: Command timed out after 5 seconds
Completed

This is the full session responses:
Connected to 192.168.56.102
sudo su macirex
macirex@kali:/root$

C:\node\node_modules\ssh2shell\test>

**Comment by cmp-202** [comment]
I have added a new test file that passess on Ubuntu Server 13 on all methods. See test/sudosutest.js and sudo section of readme for info.

**Comment by macirex** [comment]
Hello! it seems to work on my virtual machine. Could you explain to me what was happening?

Note: it works when I use sudo su but not when I switch with a normal su.

**Comment by cmp-202** [comment]
Sorry for the delay I have updated the test file and have it working for all cases. Re: solaris was it the sudo wasn't installed or your user is not in the sudo group? I downloaded it and had sudo out of the box. Good luck with this new test file.

**Comment by cmp-202** [comment]
I see how using root reqires you to not need the other password.

**Comment by macirex** [comment]
Thanks! I will test the new version... weirdly enough some of the solaris servers I manage don´t have sudo... it needs to be installed with another package.

**Comment by cmp-202** [comment]
Can I close this issue or is it still unresolved for you.

**Comment by macirex** [comment]
Sorry, I´ve been unable to test the new version... I will test it tomorrow. Thanks

**Comment by macirex** [comment]
I have been unable to make it work... anyway thanks for the effort, I will try to solve it another way.

**Comment by cmp-202** [comment]
Sorry to hear, thanks for raising the issue I will continue to look at it as time allows. Hope you find a quick solution.
