### ISSUE TITLE
Nodejs ssh2shell Connection to remote device issue with code SSH2_MSG_KEXINIT

### ISSUE THREAD

**Issue by DTECHNO1** [cmp-202/ssh2shell#100]
**Hello,**

we are using the ssh2shell Nodejs library in our app (implemented under docker ubuntu image) to connect to remote devices; however, while trying to connect to one of the devices it is displaying the following issue:

```
Nov 28 10:24:37.635: SSH2 0: SSH2_MSG_KEXINIT received
Nov 28 10:24:37.635: SSH2 0: kex: client->server enc:aes128-ctr mac:hmac-sha1
Nov 28 10:24:37.635: SSH2 0: kex: server->client enc:aes128-ctr mac:hmac-sha1
Nov 28 10:24:37.635: %SSH-3-NO_MATCH: No matching kex algorithm found: client ecdh-sha2-nistp256,
ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,
diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,
diffie-hellman-group18-sha512 server diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
Nov 28 10:24:37.799: SSH0: Session disconnected - error 0x00
```
it seems something related to Algorithm kex and Handshaking with that special device. We are seeking a solution maybe on how to add more Algorithm kex and ServerHostKeys to the ssh2shell library so that it can use it and complete the handshake; OR ELSE, what could be a solution.

**Please support! we are in a sensitive situation.**

**Comment by cmp-202** [comment]
Check out the last issue [#99](https://github.com/cmp-202/ssh2shell/issues/99)

**Comment by DTECHNO1** [comment]
Thank you cmp-202; however, I don`t see the reference with that issue #99.
