### ISSUE TITLE
Using Bash scripts on the fly is returning the script itself and the output within the response

### ISSUE THREAD

**Issue by dalgharib** [cmp-202/ssh2shell#104]
Hi Andrew,

I'm using ssh2shell in my project to execute several commands and bash scripts on a remote server, and ofcourse get each command response and use it in some analysis later.

What I`m facing is that, when executing the bash script on the remote server, I'm getting the response containing the script itself and the out put as well. I will post here part of the code to give more details about what is going on:

**CODE HERE - ALL THE BELOW:**

`let host = {
			server: {
				host:         config.host,
				port:         config.port,
				userName:     config.username,
				password:     config.password,
				privateKey:     config.privateKey,
				tryKeyboard: true,
				algorithms: algorithmObj,                    
			},			
			asciiFilter:"[^\r\n\x20-\x7e]",
			disableASCIIFilter:true,
			disableColorFilter:true,
			closedMessage:"Closed",
			debug:hostdebug,
			standardPrompt:">$%#",
			commands: [
				`bash -s ${fs.readFileSync('./script1.sh', 'utf-8')}`,
				'Hello World',
				'ls l'
			],
			idleTimeOut:30000,
			showBanner:         true,
			window:             true,
			
			onCommandComplete: async function( command, response,sshObj,stream) {                  
				const result.output=response;						
			},
		};
		
		
return new Promise(( resolve, reject ) => {

	let SSH = new SSH2Shell(host),
	callback = function(sessionText){                    
		resolve(commandResponses);                    
	}

	ssh2shellInstances.push(SSH);
	SSH.on('error', reject);
	SSH.connect(callback);

	SSH.on ('emitCloseStream', function onClose(){                
		this.emit('closeStream');
	});

	SSH.on ('commandProcessing', function onCommandProcessing( command, response, sshObj, stream ) {
		this.on('closeStream',()=>{                        
				stream.close();
				ssh2shellInstances.pop();                        
		}) 
	});`

Plz support on a way to get the response of bash script as its output only without the script itself after execution on the remote host.

**Comment by cmp-202** [comment]
Hi,
Okay so you seem to be reading in a local script file and adding the content to the end of the `bash -s` command to run on the host.
You can detect the `bash -s` command in `onCommandComplete` and remove it from the `sessionText`.

```javascript
if (command.indexOf("bash -s") > -1) {sshObj.sessonText = sshObj.sessonText.replace(command,'')}
```

**Comment by cmp-202** [comment]
Here is an alternative to you code, may need tweeking,

```javascript
let host = { 
    server: { 
        host: config.host, 
        port: config.port, 
        userName: config.username, 
        password: config.password, 
        privateKey: config.privateKey, 
        tryKeyboard: true, 
        algorithms: algorithmObj
        }, 
    disableASCIIFilter:true, 
    disableColorFilter:true,
    debug:hostdebug, 
    verbose:hostVerbose,
    commands: [ bash -s ${fs.readFileSync('./script1.sh', 'utf-8')},
        'Hello World',
        'ls l'
    ],
    idleTimeOut:30000,
    showBanner: true,
    onCommandComplete: async function( command, response,sshObj,stream) {
        if (command.indexOf("bash -s") > -1){
            sshObj.sessonText = sshObj.sessonText.replace(command,'')
        }
    },
};

return new Promise( resolve, reject ) => {
    let SSH = new SSH2Shell(host),
        callback = function(sessionText){
            ssh2shellInstances.pop();
            resolve(sessionText);
        }

    ssh2shellInstances.push(SSH);
    SSH.on('error', reject);
    SSH.connect(callback);
});
```

**Comment by cmp-202** [comment]
I see you are working with multiple hosts but did you know that ssh2shell has that built in?

[Multiple primary hosts](https://github.com/cmp-202/ssh2shell)

[Tunnelling nested hosts](https://github.com/cmp-202/ssh2shell#tunnelling-nested-host-objects-)

**Comment by cmp-202** [comment]
Last issue that was running scripts on the fly had this this final feedback:

"I read the local script file & encoded into Base64 to avoid any special characters.
Then with it I formed a command at the runtime to execute at the target:

echo "<>" | base64 -d | bash

and if you have command line inputs:
echo "<>" | base64 -d | bash -s

This worked for me without physically copying the script on target as well as running into any special character issues with echo or printf statement. Hopefully it can help others who are looking to solve the same problem.
"

**Comment by dalgharib** [comment]
> I see you are working with multiple hosts but did you know that ssh2shell has that built in?
> 
> [Multiple primary hosts](https://github.com/cmp-202/ssh2shell) [Test example](https://github.com/cmp-202/ssh2shell/blob/master/test/multiple_primary_hosts.js)
> 
> [Tunnelling nested hosts](https://github.com/cmp-202/ssh2shell#tunnelling-nested-host-objects-) [Test example](https://github.com/cmp-202/ssh2shell/blob/master/test/tunnel.js)

Yes sure I'm aware of that and may implement it in the near future

**Comment by cmp-202** [comment]
Yes that will never match to remove it.
Normally the command is removed from output but the command in this case runs over multiple lines with the extra characters and so is part of the command output.

It probably needs a regular expression to match the beginning and end of the command content to remove it.
Only trouble is getting it to work with different scripts if you use more than one.

Something like this, again probably needs tweaking to match correctly.
```javascript
onCommandComplete: function( command, response, sshObj) {
        if (command.indexOf("bash -s") > -1){
            sshObj.sessonText = response.replace(command.substring(0, 4)+"*"+command.substring(command.length - 3),'')
        }
    }
```

**Comment by dalgharib** [comment]
Great! we used the replace function and works fine. using replace will provide many options to search with regular expression and remove the matching lines from the response. Thanks again.

**Comment by cmp-202** [comment]
My pleasure.

Andrew
