### ISSUE TITLE
Conditional Commands

### ISSUE THREAD

**Issue by ghost** [cmp-202/ssh2shell#105]
Hi,

First, I want to thank you for making this. It really helps me a lot, but I was wondering if it is possible to alter the commands array midway, during the execution.

**Comment by ghost** [comment]
Nevermind. I did manage to find a way. You just have to play with the commands array. When you encounter a certain command and want a conditional run you would just have to insert commands after the index of current command. I will close this ticket. 

Thank you again for your hard work!

**Comment by cmp-202** [comment]
Sorry, it seems when I did a big cleanup and simplify of the readme I removed this detail from the example and didn't put it back.

```javascript
//using commandComplete test for command 
if (command === "echo test" & response.indexOf("test") != -1 ) {
   //unshift will add the command as the next command, use push to add command as the last command
   //The command and response check worked. Adding another first and last command
   sshObj.commands.unshift("echo new next command");
   sshObj.commands.push("echo new last command");
  }
else if (command === "echo new next command")
 {
   //or a new array of commands can replace the existing
   sshObj.commands = ["echo 1", "echo 2"];
 }
```
