### ISSUE TITLE
ERR_COMMUNICATION after upgrade

### ISSUE THREAD

**Issue by mcblum** [cmp-202/ssh2shell#106]
Hello! I'm working on upgrading our software to later versions of the SSH libs. I'm currently using ssh2shell 2.0.9, and since upgrading I'm seeing the following.

```
{
  message: '',
  raised: undefined,
  stack: undefined,
  errors: '',
  responseCodes: '',
  info: {
    errorCode: 'ERR_COMMUNICATION',
    errorDesc: 'Failed to connect to host localhost:22222'
  }
}
```

In older versions of the library it worked just fine. Obviously there are a million factors, and I can investigate them, but do you have any idea where I might start looking?

I should add that it only fails when I try to run a command, It does connect successfully first.

Thank you!

**Comment by cmp-202** [comment]
Hi
Can you turn on debug in your host object so we can see where it is failing.
Thanks

Andrew

**Comment by mcblum** [comment]
@cmp-202 thank you for the reply! Here's the debug:

```
Handle SSH request for host: localhost:22222
commands are [ 'show running-config' ]
localhost: Next primary host
localhost: initiate
localhost: Load Defaults
localhost: Host loaded
localhost: Connection.connect
Connected
Initializing fingerprint for host localhost:22222
localhost: Connection.ready
Successfully connected to localhost:22222
Ready
localhost: Connection.shell
localhost: First prompt detected
localhost: Notifications: Normal Command to run
localhost: run command
Data processing: data received timeout
Command timeout 1 for host localhost:22222
```

**Comment by mcblum** [comment]
It seems that no matter what I set the timeouts to, that first "data received timeout" message appears almost instantly

**Comment by cmp-202** [comment]
The data timeout is the response from the server has not happened within the required time.

The command was presumably sent but nothing happened in response.

Can you turn off debug and turn on verbose.
Thanks,

Andrew

**Comment by mcblum** [comment]
Of course, here it is:

```
{
  verbose: true,
  server: {
    host: 'localhost',
    port: 22222,
    userName: 'lockhart',
    algorithms: { kex: [Array], serverHostKey: [Array], cipher: [Array] },
    hashKey: '',
    hashMethod: 'md5',
    hostVerifier: [Function: hostVerifier],
    password: 'xxxxx'
  },
  idleTimeOut: 20000,
  dataIdleTime: 5000,
  commands: [ 'show running-config' ],
  closedMessage: 'Closed',
  readyMessage: 'Ready',
  msg: [Function: send],
  onError: [Function (anonymous)],
  onCommandProcessing: [Function (anonymous)],
  onCommandComplete: [Function (anonymous)],
  onCommandTimeout: [Function (anonymous)],
  sshToNextHost: false,
  connectedMessage: 'Connected',
  showBanner: false,
  debug: false,
  hosts: [],
  standardPrompt: '>$%#',
  passwordPrompt: ':',
  passphrasePrompt: ':',
  passPromptText: 'Password',
  enter: '\n',
  asciiFilter: '[^\r\n -~]',
  disableColorFilter: false,
  disableASCIIFilter: false,
  textColorFilter: '([{1}[0-9;]+m{1})',
  exitCommands: [],
  pwSent: false,
  sshAuth: false,
  sessionText: '',
  streamEncoding: 'utf8',
  window: true,
  pty: true
}
Connected
Initializing fingerprint for host localhost:22222
Successfully connected to localhost:22222
Ready
localhost: Host.commands: show running-config
localhost: Next command from host.commands: show running-config
localhost: sending: show running-config
Command timeout 1 for host localhost:22222
Command timeout 2 for host localhost:22222
Command timeout 3 for host localhost:22222
Error: Command timeout, Level: protocol
err: Command timeout
err.level: protocol
type: timeout
GENERAL ERROR: localhost:22222
res {
  message: '',
  raised: undefined,
  stack: undefined,
  errors: '',
  responseCodes: '',
  info: {
    errorCode: 'ERR_COMMUNICATION',
    errorDesc: 'Failed to connect to host localhost:22222'
  }
}
res {
  message: '',
  raised: undefined,
  stack: undefined,
  errors: '',
  responseCodes: '',
  info: {
    errorCode: 'ERR_COMMUNICATION',
    errorDesc: 'Failed to connect to host localhost:22222'
  }
}
Closed
```

**Comment by mcblum** [comment]
The strange thing about this is that it only happened after the upgrade. If I roll back to an earlier version, everything works as expected.

**Comment by cmp-202** [comment]
What is the latest version that works, note some versions are just readme updates.

**Comment by cmp-202** [comment]
Sorry about this being such a pain for you.

It looks like it is connected and finding the first prompt but when the command is sent there is no response triggering a data timeout and command timeout. 
It also then returns a connection error and closes.

Unfortunately the troubleshooting output is showing when and what but not why. 

I presume a remote server or test VM fails the same way not just localhost?

Feel free to email me content cmp-202@anyzoom.com

What does the verbose turned on for version that works look like.
If I know the newest working version I can check the changes since.

Could you provide your test code with sensitive content removed so I can check it.
Thanks

Andrew

**Comment by mcblum** [comment]
Hi Andrew,

Thanks again for your help! Can't tell you how much I appreciate it. Here's the latest version that works and also the version of SSH2:

```
"ssh2": "^0.8.6",
"ssh2shell": "1.9.1",
```

I'm connecting via localhost because we use a jumpbox to get into the lab, but it is a remote IOS device.

Thanks again!
Matt
