### ISSUE TITLE
Processing response: error

### ISSUE THREAD

**Issue by splendido** [cmp-202/ssh2shell#11]
Hi there,
I'm playing with ssh2shell and getting a weird behaviour.
If I run the following:

```javascript
  var host = {
    server: { ... },
    commands: [
      "ls -l",
      "`All done!`",
    ],
  };

  var ssh = new sshShell(host);
  ssh.connect();
```

I got the following error on the connection close:
`Processing response: error: TypeError: Cannot call method 'indexOf' of undefined TypeError: Cannot call method 'indexOf' of undefined` pointing to [this line](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L29)

While if I use as commands:

```javascript
    commands: [
      "ls -l",
    ],
```

or

```javascript
    commands: [
      "ls -l",
      "`All done!`",
      "exit"
    ],
```

everything works fine...

Perhaps `command` is `undefined` after some `.shift()` or `.pop()`?

**Comment by cmp-202** [comment]
Hmm that is odd but I think I see the problem [here] (https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L121) 

There is no check the command will be something and in your case it wont be and so is undefined on the next onData event. I will sort out a fix.

**Comment by cmp-202** [comment]
I have made a minor change to the code and added a [test file](https://github.com/cmp-202/ssh2shell/blob/master/test/notificationstest.js) for you to look at. It is working on my VM Ubuntu 13 when I run your setup structure.

**Comment by cmp-202** [comment]
thanks for picking up that bug, I hadn't even thought about that possibility.

**Comment by splendido** [comment]
brilliant, tnx!

**Comment by cmp-202** [comment]
Is this issue resolved for you?

**Comment by splendido** [comment]
:+1:

Tnx!
