### ISSUE TITLE
Removing additional weird non-standard ASCII characters

### ISSUE THREAD

**Issue by splendido** [cmp-202/ssh2shell#12]
Hello there,

I'm getting some weird characters inside logs.
This is a sample output I'd like cleaned up a little more (it's from a login command):

```
[1G[0JUsername:
```

Could it be possible to add some more rules among the [already existing ones](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L21-24)?

**Comment by cmp-202** [comment]
Yeah it is a pain. I have changed the regular epression to match all letters not just m which should catch your case. Would you be able to pull from master and see if that works for you. I am hoping it will not remove content that is wanted but I don't think it should. I will publish it once confirmed it worked for you.

**Comment by cmp-202** [comment]
I forgot to change the js file so I have just done that.

**Comment by splendido** [comment]
I'll try to test it out, but it's gonna be likely nex week

tnx!

**Comment by cmp-202** [comment]
If you give me the detail to reproduce it (command, any characteristics of the Linux version you are connecting to that I may need to replicate) I will write a test

**Comment by splendido** [comment]
mmm, might be overkilling...
Anyway, I'm logging in to a remote Ubuntu 14.04 plyaing with [Meteor](https://www.meteor.com/).
and the command is `meteor login`.

Thanks for the suppor!

P.S. All this goes behind the scenes of [autopublish.meteor.com](http://autopublish.meteor.com/) just to tell you for what I'm using it ;-)

**Comment by cmp-202** [comment]
Yeah I see what you mean about overkill just give it a try next week. Cool I will have to readup meteor sounds interesting. Mediasuite.co.nz use the early versions of this core code to deploy updates to complicated web apps written for our local council via a chat bot. It is well suited for repedative server command sequences. Thanks for letting me know where it was being used. It is alway really interesting to see what people are doing with it so thanks for that.

**Comment by splendido** [comment]
you're welcome!

...thanks for the package ;-)

**Comment by cmp-202** [comment]
Just checking if you had a chance to test this. Cheers

**Comment by cmp-202** [comment]
Adding these changes to main code and closing issue
