### ISSUE TITLE
prompt must end with [#$>]

### ISSUE THREAD

**Issue by maboiteaspam** [cmp-202/ssh2shell#14]
Hi,

Maybe an entry for readme.

In current approach, the prompt must end with [#$>] otherwise successful connection can not be detected and ends up in connection time out.

It can be surprising and source of troubles.

**Comment by cmp-202** [comment]
So are you still having issues with the standard prompt detection not working for #,$ or > in the password processing? If #$> if not enough what is your prompt ending with? It maybe that I need to add it to all prompt matching strings if there is another character to detect. The other thing might be that my change is not being reached in your case and the the change you proposed is appropriate when the password sent flag has already been set previously. If that was the case the first if statement would only be processed and the other else statements ignored. I will add it in and see if that helps if so both changes were required to cover it correctly.

**Can I just clarify your use case:**

1. Initial SSH to server was with a password for a non root user with sudo rights or did you use key authentication and so no password?
2. What was the full command you used to switch to root that did not need a password.
3. Are there any other settings on my test server I need to match to correctly test your case like the user not needing to supply a password to switch users using sudo.

I have a number of test scripts in `./test` folder one of which is sudosutest.js. I am keen to add this test case to that file which would enable both of us to test it and confirm it is working as required. No surprises or source of troubles and no need for readme notes (people tend to miss the detail and just hit the problem).

Again thanks for your time and help with making this better.

**Comment by cmp-202** [comment]
Ok updated and published to NPM (test file not changed though).

**Comment by cmp-202** [comment]
I modified my test server using `sudo vidsudo` and added `[username] ALL=(ALL) NOPASSWD: ALL` so the user didn't need to provide a password for `sudo ls` and confirmed that tests are passing and the prompt is detected correctly. Updates are live and you should be good to go.

**Comment by mscdex** [comment]
FWIW you could try setting the `PS1` environment variable right after the shell session starts (e.g. `stream.write('PS1="ssh2shell>>>"\n')` ), this way you can set it to something that is both more unique/easier to parse and is consistent across different *nix systems which may have different default shell prompt formats.

**Comment by cmp-202** [comment]
Sounds like a good strategy to simplify detection.

**Comment by cmp-202** [comment]
Sounds like a good strategy to simplify prompt detection.

**Comment by cmp-202** [comment]
Looks like I would have to do that for every change of user (login, sudo su, su user, sudo -u user -i). Prompt detect is not the issue with this problem it was the failure to check for it in the correct place.

**Comment by cmp-202** [comment]
Had another thought. Add standardPromt and passwordPrompt parameters to the host object with a default of $#> and : respectfully for the prompt types used in the match statements so the values can be overwriten to meet server requirements

**Comment by cmp-202** [comment]
So I have done that. it is now possible to override the default prompt characters used in the regular expression so prompt detection can be modified. I have added an example to the host object structure outlined in the [readme requirements section](https://github.com/cmp-202/ssh2shell#requirements).
There is passwordPrompt, passphrasePrompt and standardPrompt to set in the host object or at run time in on of the command event handlers (if need be for some reason).

**Comment by cmp-202** [comment]
By the way Brian I just want to say that you so much for all your hard work on the code to create and support. Good job.

**Comment by cmp-202** [comment]
Thanks [maboiteaspam](https://github.com/maboiteaspam) for bringing this to attention and providing a solution which was incorperated in with the other modifications.

**Comment by maboiteaspam** [comment]
hi,

amazing, thanks a lot !

I wonder how reliable mscdex solution is across distro. It could be a key element to solve that difficulty in a very friendly way.
If i have time later i ll try to give it a check.
