### ISSUE TITLE
Connection error: Error: Disconnected by host (PROTOCOL_ERROR): Packet integrity error.

### ISSUE THREAD

**Issue by rdewolff** [cmp-202/ssh2shell#15]
Any idea why I'm getting a : 

```
Connection error: Error: Disconnected by host (PROTOCOL_ERROR): Packet integrity error.
```

Using version : 
 "ssh2" : "0.3.6",
  "ssh2shell" : "1.3.2"

**Comment by cmp-202** [comment]
looks like this came up in an issue for [ssh2 #223](https://github.com/mscdex/ssh2/issues/223)

Ssh2shell and ssh2 are at newer versions I would recommend updating ssh2shell to 1.4.1 and it will update ssh2 to 0.4.7. The latest update of ssh2shell is tested on 0.4.7 for ssh2. This should fix it.

**Comment by cmp-202** [comment]
for change log check [ssh2shell wiki](https://github.com/cmp-202/ssh2shell/wiki)

**Comment by rdewolff** [comment]
Updated version to latest and it works!

**Comment by rdewolff** [comment]
Thanks for your quick answers!

**Comment by cmp-202** [comment]
No problem I couldn't sleep so timing worked well.

**Comment by rdewolff** [comment]
Get an e-ink screen so you will be less annoyed, or use something like https://justgetflux.com/ :)
