### ISSUE TITLE
onCommandProcessing get triggered too many times?

### ISSUE THREAD

**Issue by rdewolff** [cmp-202/ssh2shell#16]
When doing a ```su``` on the remote server, I have a strange behavior : the ```onCommandProcessing``` function get triggered multiple times.

```js
onCommandProcessing: function( command, response, sshObj, stream ) {
         if (command == "su" && response.indexOf("Password:") != -1 ) {
           sshObj.msg.send('Sending su password');
           stream.write(options.rootPassword + '\n');
         }
        }
```

Any idea what direction to look?

**Comment by cmp-202** [comment]
Here is the link to the su [test file](https://github.com/cmp-202/ssh2shell/blob/master/test/sudosutest.js)

**Comment by cmp-202** [comment]
I add a flag `host.suPassSent = false;` to the host object that I use to stop repeat if statement triggers in onCommandProcessing by adding it to the conditional statement and setting it to true when the password is sent.

**Comment by rdewolff** [comment]
Found a workaround by using a simple semaphore. It works much better now. But am wondering why the event get triggered so often?? Seems to be associated with the amount of character of the command.

**Comment by cmp-202** [comment]
It is because the event triggers as each data event loads the buffer with command response chars.

**Comment by cmp-202** [comment]
Password prompt detection has to wait until the buffer is loaded

**Comment by rdewolff** [comment]
Could we add a separate event to differentiate the 2 events?

**Comment by cmp-202** [comment]
Check out the test file and the event handlers at end of readme.
