### ISSUE TITLE
Latest commit breaks the data

### ISSUE THREAD

**Issue by jgroom33** [cmp-202/ssh2shell#20]
Line 30 and 31 of the compiled js evaluates to a boolean. That overwrites the response from a device.
data = this.asciiFilter.test(data);
data = this.textColorFilter.test(data);

line 21 of the coffeescript should be:
data = data.replace(@asciiFilter, "")

Line 23 should be:
data = data.replace(@textColorFilter, "")

**Comment by cmp-202** [comment]
sorry that was a dumb mistake I have updated the code to use replace.

**Comment by jgroom33** [comment]
That should do it. Thanks for the quick response
