### ISSUE TITLE
using SSH2Shell cannot connect to Cisco Router (Cipher mismatch)

### ISSUE THREAD

**Issue by ajiratech2** [cmp-202/ssh2shell#24]
I'm using the SSH2Shell wrapper to log in to Cisco Routers but my script fails to login because the Ciphers offered by SSh2Shell do not match Ciphers available on Cisco router.
I get the same issue when I use SSH2 but with SSH2 I was able to pass the 'cipher' and 'KEX' while connecting and that took care of it.

Here is my code:

var host = {
    server:        {  
            host:         "<host IP>",
            port:         "22",
            userName:     "<username>",
            password:    "<password>"
        },
        connection:         require ('ssh2'),
        commands:      [
            "show version",
            "show ssh"
        ],
        msg: {
            send: function( message ) {
            console.log("message: " + message);
            }
        },
    verbose: true,
    debug:               true,
    idleTimeOut:         15000,
    connectedMessage:    "connected",
    readyMessage:        "ready",
    closedMessage:       "closed",

    onCommandComplete: function( command, response, sshObj ) {

        console.log("------------- onCommandComplete ---------");
        console.log(command + ": " + response);
    },
    onEnd: function( sessionText, sshObj ) {
        console.log("--------- onEnd has ------------");
        console.log(sessionText);
    }
};

and here is the section that I am able to add in SSH2 to connect to the same router:

        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc'
            ]
        },

But adding this section to SSH2Shell does not help.

The debug logs on Cisco router report the following message:

Aug 22 12:06:59: %SSH-3-NO_MATCH: No matching cipher found: client aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com server aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc

can you advice how to resolve this issue ? Thanks in advance.

**Comment by cmp-202** [comment]
Hi,
Yes I can see the problem there I previously only used the minimum ssh2.connect config options required to make the connection for ssh2shell. I am going to add all the [config options](https://www.npmjs.com/package/ssh2#client-methods) available to the [host.server](https://github.com/cmp-202/ssh2shell#requirements) so you can set any of those yourself.

**Comment by cmp-202** [comment]
I have created a new branch called [ssh2.connect-options](https://github.com/cmp-202/ssh2shell/tree/ssh2.connect-options) can you pull from that, alter you host.server setting to add the algorithms object and give it a try.

**Comment by ajiratech2** [comment]
Awesome! Thank you ! that was very quick.

I'll try it out tomorrow, it is on my work computer.

**Comment by ajiratech2** [comment]
I get an error this time. 

I'm new to Github and programming in general so I may be doing it wrong. Here is what I've done to test out the new branch.
- downloaded the branch 'ssh2shell.connect-options' as zip and copied it under my node modules so it shows up the same way 'SSH2' and 'SSH2Shell' shows with similar folder structure.
- I tested using the same code by changing the require to 'ssh2shell.connect-options'
- now when I run it I get the following error:

C:\Users\ahujapa\Documents\workarea\Automation tools\Node>node ssh2shellclient.js
message: Connect: error: Error: Invalid host hash algorithm: undefined Error: Invalid host hash algorithm: undefined
    at Client.connect (C:\Users\ahujapa\Documents\workarea\Automation tools\Node\node_modules\ssh2\lib\client.js:342:13)
    at SSH2Shell.connect (C:\Users\ahujapa\Documents\workarea\Automation tools\Projects\ConsoleServer\Node\node_modules\ssh2shell-ssh2.connect-options
    at SSH2Shell.connect (C:\Users\ahujapa\Documents\workarea\Automation tools\Projects\ConsoleServer\Node\node_modules\ssh2shell-ssh2.connect-options
    at Object.<anonymous> (C:\Users\ahujapa\Documents\workarea\Automation tools\Projects\ConsoleServer\Node\ssh2shellclient.js:71:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

**Comment by ajiratech2** [comment]
added 'hashMethod' to the server section to as follows and now I'm back to the same situation as earlier. The cisco router says "No Matching cipher found".

    server:        {  
            host:         "10.40.129.2",
            port:         "22",
            userName:     "<username>",
            password:    "<password>",
            hashMethod:   "md5", //optional "md5" or "sha1" default is "md5"
            //other ssh2.connect options
        },

**Comment by cmp-202** [comment]
No Worries I will do what I can to help.
Error: Invalid host hash algorithm: undefined means its getiing nothing when it is expecting something. hashMethod is related to fingerprint validation not cipher so that wont impact it. 
It might be how I have added the other params without defaults but I would have expected the error to have had a value set by you. I used ssh2shell-ssh2.connect-options/test/devTest.js (in your branch path) if you are lookinng for an example that worked for me. Can you post your script without sensitive details.

**Comment by cmp-202** [comment]
Maybe just the host server section

**Comment by ajiratech2** [comment]
Thank you!! 
I've made more progress and am almost all set,  I re-read your comments and moved the algorithms section to go inside 'host.server' and now it works. Earlier it was in the 'host' section. 

Here is how my script looks like now and it is working. only one minor issue remaining that is mentioned at the end of this comment:

// ------ start of script that works ------
var host = {
    server:        {  
            host:           "<host IP>",
            port:           "22",
            userName:       "<user>",
            password:       "<password>",
            hashMethod:     "md5", //optional "md5" or "sha1" default is "md5"
            //other ssh2.connect options
            algorithms: {
                kex: [
                    'diffie-hellman-group1-sha1',
                    'ecdh-sha2-nistp256',
                    'ecdh-sha2-nistp384',
                    'ecdh-sha2-nistp521',
                    'diffie-hellman-group-exchange-sha256',
                    'diffie-hellman-group14-sha1'],
                cipher: [
                    'aes128-ctr',
                    'aes192-ctr',
                    'aes256-ctr',
                    'aes128-gcm',
                    'aes128-gcm@openssh.com',
                    'aes256-gcm',
                    'aes256-gcm@openssh.com',
                    'aes256-cbc'
                ]
            }
        },
        connection:         require ('ssh2'),
        commands:      [
            "terminal length 0",
            "show version",
            "show ssh",
            "show log"
        ],
        msg: {
            send: function( message ) {
                console.log("message: " + message);
            }
        },
    verbose: true,
    debug:               true,
    idleTimeOut:         15000,
    connectedMessage:    "connected",
    readyMessage:        "ready",
    closedMessage:       "closed",
 
    onCommandComplete: function( command, response, sshObj ) {

        console.log("------------- onCommandComplete ---------");
        console.log(command + ": " + response);
    },
    onEnd: function( sessionText, sshObj ) {
        console.log("--------- onEnd has ------------");
        console.log(sessionText);
    }
};
 
//Create a new instance 
var SSH2Shell = require ('ssh2shell-ssh2.connect-options'),
    SSH       = new SSH2Shell(host);
 
//Start the process 
SSH.connect();

// -------------- end of script -------------


minor issue:
At the end of the script execution, after all output is displayed I get the following message:

"message: Connection error: Error: write ECONNABORTED
message: closed"

do I need to do anything to gracefully close the connection ?

**Comment by ajiratech2** [comment]
Never mind the minor issue from last comment. I got that only when I was logging to console all output in "OnEnd". I don't see that when I log messages from "onCommandComplete" and that is where most of my logic will be.
The issue that I originally reported  is completely resolved so I will mark it as closed later today.

Thank you for your prompt help, I really appreciate your time and effort in helping me with this!!

**Comment by cmp-202** [comment]
Here is my altered script:
--------
```javascript
var host = {
   server: {
      host: "",
      port: "22",
      userName: "",
      password: "",
      algorithms: {
         kex: [
            'diffie-hellman-group1-sha1',
            'ecdh-sha2-nistp256',
            'ecdh-sha2-nistp384',
            'ecdh-sha2-nistp521',
            'diffie-hellman-group-exchange-sha256',
            'diffie-hellman-group14-sha1'],
         cipher: [
            'aes128-ctr',
            'aes192-ctr',
            'aes256-ctr',
            'aes128-gcm',
            'aes128-gcm@openssh.com',
            'aes256-gcm',
            'aes256-gcm@openssh.com',
            'aes256-cbc' ]
         }
      },
   commands: [
      "terminal length 0",
      "show version",
      "show ssh",
      "show log" ],
   msg: {
      send: function( message ) {
         console.log("message: " + message);
      }
   },
   verbose: true,
   debug: true,
   idleTimeOut: 15000,
   onEnd: function( sessionText, sshObj ) {
      sshObj.msg.send("--------- onEnd has ------------");
      sshObj.msg.send(sessionText);
   }
};

//Create a new instance
var SSH2Shell = require ('ssh2shell-ssh2.connect-options'),
SSH = new SSH2Shell(host);

//Start the process
SSH.connect();
```
Here is my reasons for changes:
-----------
* You had `connection: require ('ssh2'),` which is not defined in the readme as a valid host object value.
* I removed all of the optional values that don't need redefining ( again check the readme on npm or github)
* I replaced your console log with sshObj.msg.send which you have defined to use console.log
* I removed your onCommandComplete event handler because you have verbose (show all responses) and debug (show each process step and command) set to true (for testing only I presume) making the onCommandComplete redundent.
* Your timeout might be a little long at 15sec but it is there to set it to whatever you want.
The rest should be good. Not sure about error but try it without that connect: require(ssh2) and see if that helps.

**Comment by ajiratech2** [comment]
wow! Thanks, I will try this again with your edits and report back.

**Comment by ajiratech2** [comment]
I copied your script, plugged my host info and it failed with the hash message. so I added the following in the 'host.Server' section and then it was fine. I know it says it's optional but looks like with the 'ssh2shell.connect-options' it must be specified.
      hashMethod:     "md5", 

I still get the error "message: Connection error: Error: write ECONNABORTED" at the end but that's not a big deal.

--- I do have a different issue, please advice if I should open a separate issue for the following: ---
I reduced the idleTimeout as that was increased for a Lantronix device which is very slow, but seems like 'idleTimeout' does not help there. The Lantronix devices we have takes over 30 seconds during handshake and it is failing. I tried setting the 'readyTimeout' but that's not an object in ssh2Shell so it is still failing.

**Comment by cmp-202** [comment]
That is very odd as it should default in ssh2 to md5, I could try setting a default in ssh2shell to md5 but I don't understand why it is causing the error. I also don't get that error connecting to an Ubuntu server VM that I test against so I don't quite understand why it would be an issue for you but it obviously is.
What platform are you running your script on?

I searched for ECONNABORTED and can't find it in any file for ssh2 or any other dependancy files for ssh2shell. Can you add the following event handler to the SSH instance so I can check the error event handler.

```javascript
SSH.on ("error", function onError(err, type, close, callback) {
   consol.log("Error Check: err: " + err + ", type: " + type);};
```

**Comment by cmp-202** [comment]
idleTimeout is not related to connection timeout. IdleTimeout is to stop the host waiting indefinitly for a response that it will never get from the script because say it wasn't handled in onCommandComplete.

This parameter is now available in host.server.readyTimeout which should help with connection delays (maybe).
Here is the SSH2 doc referense:
* readyTimeout - integer - How long (in milliseconds) to wait for the SSH handshake to complete. Default: 20000

**Comment by ajiratech2** [comment]
Thank you. i'll try both sessions and report back.

My current platform is windows 7, eventually it will get deployed in Ubuntu or Red hat. I'll try out one of the Linux platforms as well and report back.

**Comment by cmp-202** [comment]
I am running it on Windows 10 but I don't think that will make a difference.

Google ECONNABORTED looks like it is a server side error, could be not terminating the ssl/tls connection properly etc

**Comment by ajiratech2** [comment]
I can enable debugs on the Server (Cisco Router) and see if I can find anything that helps us document this behavior. I'll report back with my findings

**Comment by ajiratech2** [comment]
Setting up 'readyTimeout' in 'host.server' section did help my connection move forward. It now allows the handshake to complete. This exposed a different issue 'keyboard interactive' aka 'tryKeyboard' in SSH2 package. The Lantronix device requires me to enable that, I tried enabling it in 'host.server' section but it seems to be an unknown object.

update on ECONNABORTED to follow shortly.

**Comment by cmp-202** [comment]
SSH2 decs:
* tryKeyboard - boolean - Try keyboard-interactive user authentication if primary user authentication method fails. If you set this to true, you need to handle the keyboard-interactive event. Default: false

* keyboard-interactive(< string >name, < string >instructions, < string >instructionsLang, < array >prompts, < function >finish) - The server is asking for replies to the given prompts for keyboard-interactive user authentication. name is generally what you'd use as a window title (for GUI apps). prompts is an array of { prompt: 'Password: ', echo: false } style objects (here echo indicates whether user input should be displayed on the screen). The answers for all prompts must be provided as an array of strings and passed to finish when you are ready to continue. Note: It's possible for the server to come back and ask more questions.

That event isn't implemented in SSH2Shell yet.

**Comment by ajiratech2** [comment]
you're right. I had to also do keyboard-interactive in SSH2.

Most of my devices are Cisco, so I'm ok there. For Lantronix, i'll figure something out.

I want to be respectful of this forums procedures. Let me know if "keyboard-interactive" should be opened as a separate issue or if we should leave this issue as open for now?

**Comment by cmp-202** [comment]
Open it as a new issue as it is a different development banch and I will get onto it over the next couple of days. I am hoping I can add it like the other event handlers so you define your own handler.

Regarding this issue and branch are you happy for me to merge into master and publish as a minor patch v1.5.1 to npm?

**Comment by ajiratech2** [comment]
Yes, absolutely.

This works perfectly now.

I'll open a separate issue for keyboard-interactive.
Thanks again. I really appreciate it.

**Comment by cmp-202** [comment]
I have just commited the keyboard-interactive addition to the current branch. Add an event handler called keyboard-interactive(name, instructions, instructionsLang, prompts, finish) to either the host file or the instance. I am not going to reference this in readme or release yet but if you get it going let me know and I will glean how you did it so it can be added as an example.
Cheers for this. Hmm 6:30 am must be bed time lol.

**Comment by ajiratech2** [comment]
Thanks ! I'll give this a shot and report back.
wow! didn't realize you were burning the midnight oil to help me out.

**Comment by ajiratech2** [comment]
This works as desired. Thanks again !!!

I discovered a typo in your coffeescript, which doesn't seem to affect my tests. But I'll still share it anyway - filename  'ssh2shell.coffee' line 283 first word is misspelled.
        @conneciton.on "keyboard-interactive", (name, instructions, instructionsLang, prompts, finish) =>

Funny thing on how I ended up looking into the code - someone replaced the lantronix that I was testing against and didn't tell me. My attempts continued to fail, so I figured I'll see what was added this time in your code.

Anyhow, Here is the working script for documentation:

    var host = {
       server: {
          host: "<hostname or IP>",
          port: "22",
          userName: "<username>",
          password: "<password>",
          hashMethod:     "md5", 
          readyTimeout: 50000,
          tryKeyboard: true,
          algorithms: {
             kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
             cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
             }
          },
          commands: [
             "show deviceport global",
             "show deviceport names" ],
          msg: {
             send: function( message ) {
                console.log("message: " + message);
             }
          },
          verbose: true,
          debug: true,
          idleTimeOut: 10000,
          ["keyboard-interactive"]: function(name, instructions, instructionsLang, prompts, finish){
             console.log('Connection :: keyboard-interactive');
             console.log(prompts);
             finish(["<password>"]);
          },
          onEnd: function( sessionText, sshObj ) {
             sshObj.msg.send("--------- onEnd has ------------");
             sshObj.msg.send(sessionText);
          }

    };

    //Create a new instance
    var SSH2Shell = require ('ssh2shell-ssh2.connect-options'),
    SSH = new SSH2Shell(host);

    //Start the process
    SSH.connect();

**Comment by cmp-202** [comment]
Branch merged into master and published to npm as v1.5.1  don't wory about another issue both cases are clearly outlined here.
Cheers

**Comment by ajiratech2** [comment]
Thanks again, Andrew!!

So I should now be able to download ssh2shell and use these features?

Pankaj


On Aug 23, 2016, at 8:21 PM, Andrew McMurtrie <notifications@github.com<mailto:notifications@github.com>> wrote:


Branch merged into master and published to npm as v1.5.1 don't wory about another issue both cases are clearly outlined here.
Cheers

-

**Comment by cmp-202** [comment]
Recent changes to fingerprint validation should fix your md5 issue

**Comment by ajiratech2** [comment]
Thank you! I'll try that out as well.

**Comment by ajiratech2** [comment]
I have one follow up question, hopefully this won't take much of your time.

In ssh2shell when I use the event "onCommandTimeout", the default behavior is to exit out of the connection. Instead I want it to try the next command in the array and only end the connection once all commands in array have been tried.

Is it possible to the above in this section ? Thanks again!

            onCommandTimeout:    function(command, response, sshObj, stream, connection) {

            },

**Comment by cmp-202** [comment]
Please review the readme there are the event handler definitions and an example for using command timeout. It is always recommended to give the readme a good going over first. You may even pick up on some other stuff you didn't know it can do.

Just to clarify host event handlers over ride default handlers for each host they are defined for. That might not be clear in readme. The event parameters provide the previous command and response to check for a prompt for a given command and respond to it using stream.write(). It is recommended close the connection with connection.close() as the last action if all other comparisons are not met.
I hope that helps.

**Comment by cmp-202** [comment]
On trying all other commands, that it not possible as command timeout has been triggered because the proccess has not detected a valid prompt to output the next command and so has timedout. Command timeout let's you handle what is probably a required response and continue.

**Comment by ajiratech2** [comment]
Thanks @cmp-202. 
I did go through the readme examples and SO but still could not figure out how to do this. I read the lib file from your source code to see If I could somehow hack it and get it to do what I want. But still was not able to get it to work. Perhaps I'm missing something.

I'll elaborate on the reason behind me wanting to do this - The Lantronix device is a terribly slow device. It delivers the "ready" message and just sits there. I thought it was trying the first command but now I think that it delivers a non-standard prompt, which the script does not interpret as a prompt. 

"Connected to port 22."

technically this is not a prompt. The lantronix is a console server which allows me to connect via SSH to serial/console port of cisco devices. So when I connect and get the message "Connected to port 22." I am supposed to wait a few seconds and hit enter and then I get prompt from my Cisco router which ends in '>' or '#'.

On my terminal the last message I see is "Ready" and then it waits there for 45 seconds (idleTimeout) and then enters event 'onCommandTimeout'.

My script in 'onCommandTimeout' is:

         onCommandTimeout:    function(command, response, sshObj, stream, connection) {
                console.log("onCommandTimeout: command holds: " + command);
                console.log("onCommandTimeout: response holds: " + response);
                console.log("onCommandTimeout: sessionText holds: " + sshObj.sessionText);
                connection.close();
        },

My array of commands that I send in is -  [  "show version", "show log" ];

I get the following output from my connection attempt:

    will now connect to device at host LAB-DMZ at port 22 
    message: Connected
    message: LAB-DMZ verbose: Server hash:55d2178044a6641e7a3f528a97f5f043
    message: Ready
    onCommandTimeout: command holds:
    onCommandTimeout: response holds: Connected to port 22.

    onCommandTimeout: sessionText holds: undefined
    C:\Users\ahujapa\Documents\workarea\Automation tools\Node\sshToLantronix.js:108
                    connection.close();
                              ^

    TypeError: Cannot read property 'close' of undefined
        at Object.host.onCommandTimeout (C:\Users\ahujapa\Documents\workarea\Automation tools\Node\sshToLantronix.js:108:27)
        at SSH2Shell.<anonymous> (C:\Users\ahujapa\Documents\workarea\Automation tools\Node\node_modules\ssh2shell-ssh2.connect-options\lib\ssh2shell.js:350:33)
        at emitMany (events.js:108:13)
        at SSH2Shell.emit (events.js:182:7)
        at SSH2Shell._timedout (C:\Users\ahujapa\Documents\workarea\Automation tools\Node\node_modules\ssh2shell-ssh2.connect-options\lib\ssh2shell.js:26:19)
        at null._onTimeout (C:\Users\ahujapa\Documents\workarea\Automation tools\Node\node_modules\ssh2shell-ssh2.connect-options\lib\ssh2shell.js:4:59)
        at Timer.listOnTimeout (timers.js:92:15)


Any suggestions on how to handle this non standard prompt ? or how to force sending next command in array when "onCommandTimeout" is fired?

**Comment by cmp-202** [comment]
Looks like I am starting a new branch for commandTimeout and readme changes! Sorry won’t take long to make some needed changes.

**Comment by ajiratech2** [comment]
My apologies for bothering you with this.

I do really appreciate your help.

**Comment by cmp-202** [comment]
https://github.com/cmp-202/ssh2shell/issues/27

 

https://github.com/cmp-202/ssh2shell/tree/CommandTimeout

**Comment by cmp-202** [comment]
No Worries looks like it needed some love.

 

So grab the new branch, extract it and copy the contents of the folder into your ssh2shell folder so you don’t need to change paths.

Try the following:

 

onCommandTimeout: function( command, response, stream, sshObj ) {

   if (command === "" && response === “Connected to port 22.” ) {

     stream.write('\n'); //to trigger the standard prompt on a new line

   }else{

     stream.end();

   }

}

 

Or 

 

onCommandTimeout: function( command, response, stream, sshObj ) {

   if (command === "" && response === “Connected to port 22.” ) {

     var command

     command = sshObj.commands.shift(); //to load the first command and run it

     stream.write(command+ '\n');

   }else{

     stream.end();

   }

}

**Comment by cmp-202** [comment]
Probably don’t need `var command` in the second example

**Comment by cmp-202** [comment]
Sorry forgot to build javascript

**Comment by ajiratech2** [comment]
Thanks! I just reached home. Will try it tonight and report back.


On Aug 25, 2016, at 6:44 PM, Andrew McMurtrie <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry forgot to build javascript
