### ISSUE TITLE
Differentiate between stdout and stderr

### ISSUE THREAD

**Issue by bibulle** [cmp-202/ssh2shell#34]
is there a way to differentiate between stdout and stderr in server response ?

for example, I'd like to know what is 
    a "normal" output (echo "toto" --> "toto")
    a "error" output (cd toto --> "bash: cd: toto: No such file or directory")

**Comment by cmp-202** [comment]
Hi there,
The stderr output is not writen to the session buffer instead stderr raises an error event with source identified as 'Stream STDERR' and passes in an error object. It would be possibe to add an error event handler that looked for those error types and responded as you required like calling msg with whatever you wanted based on the error object.

If debug is turned on then a msg will be returned indicating a stderr has occured but doesn't provide any other information. 

ssh2shell supports .pipe() but I suspect that might not include stderr. Could be worth a test though.

**Comment by cmp-202** [comment]
If you send a command that would generate a error message in a terminal then you should see that in the command response string loaded from the buffer from command execution to next prompt detection. This is handled in the host.onCommandComplete event and the text is added to the full session text. If it blocks a command prompt then a timeout event will trigger.

**Comment by bibulle** [comment]
Hi (and thanks for the quick answer),

That exactly my point... you perfectly manage the "errors" as is it's normal output.
I don't see the way to separate them

**Comment by cmp-202** [comment]
So are you not seeing what you are expecting to in the output from your commands when you create an error?

**Comment by bibulle** [comment]
My aim is to get a way to differentiate.
I'd like to display to the final user in "green" or "red" depending if it's a stdout or sdterr.

So ... via an onError or just something different in the response (for example with options "beforeError" and "afterError" that should be used in my usecase)

**Comment by cmp-202** [comment]
So stderr and stdout are merged in normal output (http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout) and stderr is currently not being handled as you would need it. 
So there are two options:

1. I expose the stderr on data event for you to bind your own data event handler.

2. I enable you to add a pipe to stderr which basically does the same.

I do both for the normal stream pipe, unpipe and on data event.
Both cases would require buffering the data to get the whole block.
Color codes are filtered out by default but you can disable the filter and add your own.

**Comment by bibulle** [comment]
Ok, I just try to see if I can do a PR to you for this...
And the point is.... in the shell mode of ssh2, stderr is not used... it's already merged...
That's why :-(

I'm going to try the colors directly from the server.
I'm a little bit ashamed to bother you with this ;-).

**Comment by cmp-202** [comment]
His shell example directs stderr to the console but I don't know if it outputs anything, I can't see why not. Looking at the code it would be bloody messey to use pipe and unpipe, they can't be added untill the connection is made and a second teir stream just starts making it too complicated when it doesn't really get used. I think exposing the stderr on data event would be the best way. Not sure what data would come out of that but it would be easy to test. Just about finished it now.

See the readme for info on the color code filters and how to turn them on and off or they will get stripped out of your session text as the buffer loads.

Its all good I do try to accomodate the varying needs of those using the package especially if I have missed something. Then every one benefits from the improvements and the more is possible.

**Comment by cmp-202** [comment]
So I have updated git with a new version. Grab the /lib/shh2shell.js file and drop it into you project node_modules/ssh2shell/lib/ folder. You can add a host.onStderrData event handler or an instance.on("stderrData",function(data){}) it takes one variable containing the next char in the data stream which will need to be buffered for it to be usefull.

**Comment by bibulle** [comment]
Great, I'll try it just now.

**Comment by bibulle** [comment]
So, it doesn't work for me...
I think everything is on the stdout :-(

It works for you ?

**Comment by cmp-202** [comment]
I am not able to test it at the moment because I am working. If you have setup the host.StderrorData  event handler to output to console.error or to console.log with something to identify it was stderr and nothing happened then it may not be working. The other thing to check is the ssh2 client params readme info, they can be set in ssh2shellthrough the host.server options. There might be something in there to turn it on or off.

**Comment by cmp-202** [comment]
If none of that works you can use onCammandComplete to test the command response text for error responses and color it accordingly. It can be done based on the previous command unless your commands are dynamic from user command definitions. Apart from that you are probably limited to coloring on the server and setting `host.disableColorFilter = true;`

**Comment by bibulle** [comment]
yep... never mind.... 
Thanks a lot for making yourselves available !!

**Comment by bibulle** [comment]
As seen with ssh2 project... it is not possible (https://github.com/mscdex/ssh2/issues/523)
So let's close it
