### ISSUE TITLE
Custom encoding

### ISSUE THREAD

**Issue by sekrasoft** [cmp-202/ssh2shell#37]
There is a `setEncoding` call at [ssh2shell.coffee#L428](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L428) that forces `stdout` to be UTF-8 encoded.
Could you provide an option (e.g. `sshObj.encoding`) for this?

**Comment by cmp-202** [comment]
host.streamEncoding option added.

**Comment by cmp-202** [comment]
I presume this is resolved
