### ISSUE TITLE
Erroneous sharing mutable initializers between SSH2Shell objects

### ISSUE THREAD

**Issue by sekrasoft** [cmp-202/ssh2shell#38]
Lines [15](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L15) and [16](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee#L16) at ssh2shell.coffee define `_connections` and `_pipes` members.
The lines result in the following JS output:

    SSH2Shell.prototype._connections = [];
    SSH2Shell.prototype._pipes = [];

The arrays **are shared** between all the `SSH2Shell` instances. The instances don't reassign `_connections` and `_pipes` but modify these arrays.
So every instance at least adds its pipe to `_pipes` and then writes its own data to all the pipes.

P.S. `_stream` seems to have similar issue but `SSH2Shell` instances reassigns it somewhere (not in the constructor).

**Comment by cmp-202** [comment]
Moved both to constructor. Can you please check this is working for you and then I will publish to npm.

_stream is set when the connection.shell event triggers returning the stream established.

**Comment by sekrasoft** [comment]
It works, thank you!

By the way, there is a type at [line 508](https://github.com/cmp-202/ssh2shell/blob/fd9c1c8cb719bc623f7e439fa195ba597d596d2d/src/ssh2shell.coffee#L508):
`missingParameters( err, type, close ) ->`
It produces `missingParameters` call instead of defining.

**Comment by cmp-202** [comment]
if you look at the emit structure `missingParameters( err, type, close ) ->` is the same as `function( err, type, close ) ->`
It is just a callback function only used if required connection params are not found and named to make it easy to see what error was being handled by the emitter.

**Comment by sekrasoft** [comment]
I mean, it results in `missingParameters` call:
`missingParameters(err, type, close)(function() {`
but should result in declaration:
`function missingParameters(err, type, close) {`

So the line throws "ReferenceError: missingParameters is not defined" and `this.emit` is not called.

**Comment by cmp-202** [comment]
Okay I will have a look tomorrow. Thanks for the input.On 10/06/2017 2:18 PM, sekrasoft <notifications@github.com> wrote:I mean, it results in missingParameters call:
missingParameters(err, type, close)(function() {
but should result in declaration:
function missingParameters(err, type, close) {
So the line throws "ReferenceError: missingParameters is not defined" and this.emit is not called.

**Comment by cmp-202** [comment]
The emit callback name is remoed now. Thanks for identifying these issues I appreciate the help.
