### ISSUE TITLE
Login to remote shell without any command sent

### ISSUE THREAD

**Issue by hanct** [cmp-202/ssh2shell#40]
Hi,
How do we login to remote shell without sending any command.

I ask this, cos the below example and the ssh2shell page seems to indicate that commands property is required. But I only want to login, and don't want send any command such as echo or ls . Is that possible?

//host configuration with connection settings and commands
var host = {
 server:        {     
  host:         "127.0.0.1",
  userName:     "test",
  password:     "1234",
 },
 commands:      [ "echo $(pwd)", "ls -l" ] 
};

**Comment by cmp-202** [comment]
Hi,
If there are no commands in the host.commands array the connection is closed for that host if the initial login was successful if it wasn't you would get a connection error. 
If you are not wanting to run any commands and only check login then ssh2shell is probably not the package to use. Have a look at SSH2 that this package is built on.

**Comment by hanct** [comment]
Thanks for reply. Based on the above discussion, can i conclude that everytime i wanted to execute an array of commands, a new login and new connection need to be created? 

 I ask that cos the host object contain the login credential and a array of commands.  So the 2nd time and subsequent , i wanted to execute these array of commands again, I will reuse this host object, and that would mean the ssh2shell will login again thus creating a new connection.

**Comment by cmp-202** [comment]
Yes once the array of commands is completed the connection is closed. SSH2shell does not maintain a persistant connection. 

When you create the ssh2shell instance and call the connect function the new connection is made and the commands are run then it disconnects on completion. 

Currently running connect again doesn't reset the instance data from the previous process so it would be recommended to repeat calling the constructor to initiate a new instance. I might change that but there has never been a request for it.

It is possible to add or remove commands using the host.onCommandComplete event handler based on a spacific command response content while the command processing is running.

**Comment by hanct** [comment]
Thanks for your reply. Seem like i need to look into ssh2 that this package is built on to get persistent connection.

**Comment by cmp-202** [comment]
It is a little more complicated than that unfortunitly. It might be worth looking at some of the other SSH packages built on SSH2 shell to see if someone else has already created support for persistance, not sure if there is.

It is not likely you can just use SSH2 shell without needing to code additional handling for lower level functionality like stream data buffering, event handlers and other logic required to support how you want to use it. If you look at my [coffee script source](https://github.com/cmp-202/ssh2shell/blob/master/src/ssh2shell.coffee) you will see the SSH2 shell connection code at the very end of the file but there is heaps of other code required to handle everything after the connection if made.
Hope this helps.
