### ISSUE TITLE
Shell window resize

### ISSUE THREAD

**Issue by vinnie-d** [cmp-202/ssh2shell#43]
I can't seem to find a way to resize the shell window size. I've created a few scripts that login into HP/Cisco switches and routers. Every time I get a response back, if the response is too long, the line wraps around.

Current Ex Output (exaggerated):

> **Image stamp: /ws/build/btm(swbuildm_
> rel_richmond_qaoff_rel_richmond)**
> Mar 23 2016 11:45:27
> K.16.01.0006

Desired output:

> **Image stamp: /ws/build/btm(swbuildm_rel_richmond_qaoff_rel_richmond)**
> Mar 23 2016 11:45:27
> K.16.01.0006

Any help would be greatly appreciated!

`var host = {
 server:        {     
  host:         "10.10.10.10",
  userName:     "user",
  password:     "pass",
 },
 commands:      [ "sh ver" ]
};

var SSH2Shell = require ("ssh2shell"),
  SSH = new SSH2Shell(host),
  callback = function(sessionText){
    //mongodb insert code
  }

SSH.connect(callback);`

**Comment by cmp-202** [comment]
Hi,
There is no wrapping text in ssh2shell. The text resulting from either a command or the full session output is plaintext with original carriage returns, anything else is stripped out using a couple of filters.  
If you save the sessionText as a file and view it you should see the required layout with no wrapping as long as your editing program isn't wrapping. If so either try turning that off or view it in another program.

Where are you viewing the output that shows it wrapping? If saving it to mongodb is the saved value wrapped (carriage return added) or is it the output and what are you viewing it with? I would be looking in this area first.

**Comment by vinnie-d** [comment]
If I initiate the `show version` command in a Putty session using the default window size, one of the output lines will wrap around because the line exceeds the window width. If I maximize the window and I use the entire screen, the line doesn't wrap around anymore and it's displayed on one line.
[https://github.com/vinnie-d/ssh2json/blob/master/putty-log](url)

When I initiate the same command using the ssh2shell library, the output wraps around just like the default Putty session.
[https://github.com/vinnie-d/ssh2json/blob/master/ssh2shell-output](url)

I know that the original ssh2 library documentation talks about the possibility to resize the window:
[https://github.com/mscdex/ssh2#pseudo-tty-settings](url)

Hopefully this helps

**Comment by cmp-202** [comment]
Thanks.
I am going to create a new branch called `window` which will add a `host.window = false;` default value that you can change to `host.window = {cols: 200};` for example (default is 80) or any of the Pseudo-TTY settings.

**Comment by cmp-202** [comment]
Okay give that a go using the window branch with host.window added to your config.

**Comment by cmp-202** [comment]
That code has a bug don't use it yet.

I ran my test/simple.js with some commands added:

```javascript
var host = {
  server: {     
    host:         process.env.HOST,
    port:         process.env.PORT,
    userName:     process.env.USER_NAME,
    password:     process.env.PASSWORD
  },
  showBanner:     true,
  debug:          false,
  verbose:        false,
  commands:       [
    "ls -la",
    "cat /proc/version",
    "uname -a"
  ]
};
```

and I got this output in my windows cmd window:

```
-----Callback session text:
Connected to 192.168.0.117
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-96-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

119 packages can be updated.
0 updates are security updates.


banner content
Last login: Wed Oct 11 00:08:07 2017 from 192.168.0.6
user@ubuntu:~$ ls -la
total 72
drwxr-xr-x 5 user user  4096 Feb  1  2017 .
drwxr-xr-x 4 root root  4096 Sep  2  2016 ..
-rw------- 1 user user 33767 Oct 11 00:08 .bash_history
-rw-r--r-- 1 user user   220 Aug 18  2016 .bash_logout
-rw-r--r-- 1 user user  3771 Aug 18  2016 .bashrc
drwx------ 2 user user  4096 Aug 18  2016 .cache
drwxrwxr-x 2 user user  4096 Sep  1  2016 .nano
-rw-r--r-- 1 user user   655 Aug 18  2016 .profile
drwx------ 2 user user  4096 Sep 30  2016 .ssh
-rw-r--r-- 1 user user     0 Aug 18  2016 .sudo_as_admin_successful
user@ubuntu:~$ cat /proc/version
Linux version 4.4.0-96-generic (buildd@lgw01-10) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017
user@ubuntu:~$ uname -a
Linux ubuntu 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
user@ubuntu:~$
-----Callback end
```

As you can see I am not getting wrapping and I haven't changed the pseudo-TTY settings.

Can you use the onEnd event handler to save the session text to either a text file and post it here or send it via email as the body using the example below. Thanks 

View the [single use example](https://github.com/cmp-202/ssh2shell#connecting-to-a-single-host) in the readme for requirements.
```javascript
onEnd: function( sessionText, sshObj ) {
  //email the session text instead of outputting it to the console
  var sessionEmail = new Email({ 
    from: "you@email.com", 
    to:   "cmp-202@anyzoom.com", 
    subject: "ssh2shell test",
    body: "\nThis is the full session response:\n\n" + sessionText
  });
}
```

**Comment by vinnie-d** [comment]
I really appreciate your engagement. I'll provide you with more feedback once I get back home to my dev environment. The ssh2shell-output file that I've included earlier was generated by dumping the console.log into a file (node ssh2shell.js > out.txt) and removing the console ASCII VT100 gibberish using a regex filter.

In my research I've also ran into this document from HP: [Making window size negotiation available for a telnet session](https://h20564.www2.hpe.com/hpsc/doc/public/display?docId=emr_na-c04725280#Making_window_size_negotiation_available_for_a_telnet_session)

So, I it looks like my devices are limiting the terminal output size. I've initially ran the library against an Ubuntu server and I had the same results as yours, no text wrapping.

I still think that being able to negotiate the pseudo-tty-settings would be a great feature.

Thanks!

**Comment by vinnie-d** [comment]
I'm glad to report back that your new update solved my problem. I've added the `window: {cols: 200},` parameter to my config and now the shell doesn't wrap around anymore.

I've also tested the terminal resize command `terminal width 200` within the switch config and that worked too. However, Your solution is more elegant, Not all equipment has the option to resize the terminal using built-in commands.

Thanks!

**Comment by cmp-202** [comment]
Awesome. It is interesting how many times it is the characteristics of the hardware that drives the changes to ssh2shell, in a good way. I agree far better to have the pseudo-TTY setting available as well as being able to run a command. I will update the readme and publish the changes on npm. Thanks for taking the time to do the research and provide the debug info.

Andrew

**Comment by vinnie-d** [comment]
No, no, thank you for being so responsive! It's great when developers are so active and willing to help. I'm not a developer, I'm a network specialist with some scripting knowledge and having this kind of support it's priceless. 

Thank you!
