### ISSUE TITLE
Login to Cisco WLC

### ISSUE THREAD

**Issue by unchained-za** [cmp-202/ssh2shell#45]
Good day
Back again, this time trying to login on a Cisco wireless LAN controller. It doesn't use the standard user@host format but rather prompts for a Username and Password. I expected it to use the keyboard-interactive mode, but it doesn't seem to reach that section. Trying to catch the prompt in onCommandProcessing wasn't too successful yet.

Any ideas perhaps from your side?

Regards

**Comment by cmp-202** [comment]
Have you tried turning on [keyboard-interactive in ssh2shell](https://github.com/cmp-202/ssh2shell#keyboard-interactive)? 
Prompt detection only works if the initial ssh connection completed to return the prompt so if that didn't authenticate it won't happen. Data events only start being processed after the ssh2 connection in shell mode.
User@host is not in the prompt detection method (not sure if that is what you meant) it is the end char (% or > or # or $).
Can you provide verbose and debug output please.
Thanks

**Comment by unchained-za** [comment]
Here is one of the original samples of code that we used with the banner problem along with the output. I also added 2 commandline ssh examples.

cmp-202.js

var host = {
    server:             {
        host: "10.65.1.140",
        port: "22",
        userName: "user",
        password: "password",
        tryKeyboard:  true,
        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
        }
    },
    commands:           [
        "show clock"
    ],
    showBanner: true,
    verbose: true,
    debug: true,
    onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        this.emit("msg", "name: " + name + ", prompts: " + prompts);
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandTimeout: function( command, response, stream, connection ){
        if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout")};
        this.emit ("msg", "command: " + command + "\nResponse:\n" + response);
    }
};

host.onData = function(data){
    // console.log(data);
    if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onData: " + data)};
}

var SSH2Shell = require ('./user_modules/ssh2shell')
var SSH = new SSH2Shell(host);
SSH.connect();

---------------------------------

$ ../../bin/node/node/bin/node cmp-202.js
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
10.65.1.140: host.onData:

(Cisco Controller)
User:
10.65.1.140: host.onCommandTimeout
command:
Response:


(Cisco Controller)
User:
10.65.1.140: Stream.finish
10.65.1.140: Session Text:
Connected to 10.65.1.140

10.65.1.140: Stream.close
10.65.1.140: Connection.close
Closed
$

---------------------------
Commandline ssh examples;

$ ssh user@10.65.1.140


(Cisco Controller)
User: user
Password:************
(Cisco Controller) >logout
The system has unsaved changes.
Would you like to save them now? (y/N) n
Connection to 10.65.1.140 closed.
$

---------------------------------

$ ssh 10.65.1.140


(Cisco Controller)
User: user
Password:************
(Cisco Controller) >logout
The system has unsaved changes.
Would you like to save them now? (y/N) n
Connection to 10.65.1.140 closed.
You have new mail in /var/spool/mail/sintrex
$

**Comment by unchained-za** [comment]
Just to see what happens, I changed the script for output and debugs in ssh2 too.

 var host = {
    server:             {
        host: "10.65.1.140",
        port: "22",
        userName: "username",
        password: "password",
        tryKeyboard:  true,
        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
        },
        debug: 'console.log(msg)'
    },
    commands:           [
        "show clock"
    ],
    showBanner: true,
    verbose: true,
    debug: true,
    loggedIn: false,
    onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        this.emit("msg", "*** onKeyboardInteractive - name: " + name + ", prompts: " + prompts);
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit("msg", "*** onEnd");
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandTimeout: function( command, response, stream, connection ){
        this.emit("msg", "*** onCommandTimeout");
        if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout")};
        this.emit ("msg", "command: " + command + "\nResponse:\n" + response);
    }
};

host.onData = function(data){
    this.emit("msg", "*** host.onData");
    // console.log(data);
    if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onData: " + data)};
    if (!this.loggedIn && data.search('.*User: ?$') != -1) {
        this._stream.write(this.sshObj.server.userName + '\n');
    }
    if (!this.loggedIn && data.search('.*Password: ?$') != -1) {
        this._stream.write(this.sshObj.server.password + '\n');
    }
}

var SSH2Shell = require ('./user_modules/ssh2shell')
var SSH = new SSH2Shell(host);
SSH.connect();

----------------------------------------------------
This was the result:
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
*** host.onData
10.65.1.140: host.onData:

*** host.onData
10.65.1.140: host.onData:
(Cisco Controller)
User:
*** host.onData
10.65.1.140: host.onData: u
*** host.onData
10.65.1.140: host.onData: sername
Password:
*** host.onData
10.65.1.140: host.onData: *
*** host.onData
10.65.1.140: host.onData: ***********
*** host.onData
10.65.1.140: host.onData:
(Cisco Controller) >
*** onCommandTimeout
10.65.1.140: host.onCommandTimeout
command:
Response:


(Cisco Controller)
User: username
Password:************
(Cisco Controller) >


... just hangs, eventually break with ^C

Seems to have sort of logged in, but with an incomplete process as it didn't get to the command execution.

**Comment by cmp-202** [comment]
Don't turn on ssh2 debug it is not helpful.
it could be prompt detection like the other issue being worked on.

**Comment by unchained-za** [comment]
I had a look at the other issue, not in detail though, and thought it might be similar. Again the script and result but with ssh2 debug off. I left my additional messages in, marked with '+++ '.

```
var host = {
    server:             {
        host: "10.65.1.140",
        port: "22",
        userName: "Username",
        password: "Password",
        tryKeyboard:  true,
        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
        },
    },
    commands:           [
        "show clock"
    ],
    showBanner: true,
    verbose: true,
    debug: true,
    loggedIn: false,
    onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        this.emit("msg", "+++ onKeyboardInteractive - name: " + name + ", prompts: " + prompts);
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit("msg", "+++ onEnd");
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandTimeout: function( command, response, stream, connection ){
        this.emit("msg", "+++ onCommandTimeout");
        if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout")};
        this.emit ("msg", "command: " + command + "\nResponse:\n" + response);
    }
};

host.onData = function(data){
    this.emit("msg", "+++ host.onData");
    if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onData: " + data)};
    if (!this.loggedIn && data.search('.*User: ?$') != -1) {
        this._stream.write(this.sshObj.server.userName + '\n');
    }
    if (!this.loggedIn && data.search('.*Password: ?$') != -1) {
        this._stream.write(this.sshObj.server.password + '\n');
    }
}

var SSH2Shell = require ('./user_modules/ssh2shell')
var SSH = new SSH2Shell(host);
SSH.connect();
```

---------------------------------------


```
$ time ../../bin/node/node/bin/node  cmp-202.js 
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
+++ host.onData
10.65.1.140: host.onData: 

+++ host.onData
10.65.1.140: host.onData: 
(Cisco Controller) 
User: 
+++ host.onData
10.65.1.140: host.onData: U
+++ host.onData
10.65.1.140: host.onData: sername
Password:
+++ host.onData
10.65.1.140: host.onData: *
+++ host.onData
10.65.1.140: host.onData: *******
+++ host.onData
10.65.1.140: host.onData: 
(Cisco Controller) >
+++ onCommandTimeout
10.65.1.140: host.onCommandTimeout
command: 
Response:


(Cisco Controller) 
User: Username
Password:************
(Cisco Controller) >
```

-----WAITS, eventually times out / terminates, nothing left out here, just a blank display.

```
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140

10.65.1.140: Stream.close
10.65.1.140: Connection.close
Closed

real	5m19.233s
user	0m0.182s
sys	0m0.018s
$
```

**Comment by cmp-202** [comment]
I am not seeing your onKeyboardInteractive handler outputting your debug message to the output. 
I am confused why the prompt isn't being detected. 
Here is what I would modify:

```javascript
var host = {
    server:             {
        host: "10.65.1.140",
        port: "22",
        userName: "Username",
        password: "Password",
        tryKeyboard:  true,
        algorithms: {
            kex: [
                'diffie-hellman-group1-sha1',
                'ecdh-sha2-nistp256',
                'ecdh-sha2-nistp384',
                'ecdh-sha2-nistp521',
                'diffie-hellman-group-exchange-sha256',
                'diffie-hellman-group14-sha1'],
            cipher: [
                'aes128-ctr',
                'aes192-ctr',
                'aes256-ctr',
                'aes128-gcm',
                'aes128-gcm@openssh.com',
                'aes256-gcm',
                'aes256-gcm@openssh.com',
                'aes256-cbc' ]
        },
    },
    commands:           [
        "show clock"
    ],
    showBanner: true,
    verbose: true,
    debug: true,
    loggedIn: false,
    //not sure about this
    onKeyboardInteractive: function(name, instructions, instructionsLang, prompts, finish){
        this.emit("msg", "+++ onKeyboardInteractive - name: " + name + ", prompts: " + prompts);
        finish([this.sshObj.server.password]);
    },
    onEnd: function( sessionText, sshObj ) {
        this.emit("msg", "+++ onEnd");
        this.emit ("msg", sshObj.server.host + ": Session Text:\n" + sessionText);
    },
    onCommandProcessing: function(command, data, sshObj, stream){
        if (!this.loggedIn && data.search('.*User: ?$') != -1) {
            this._stream.write(this.sshObj.server.userName + '\n');
        } else if (!this.loggedIn && data.search('.*Password: ?$') != -1) {
            this._stream.write(this.sshObj.server.password + '\n');
        }
    },
    onData: function(data){
        this.emit("msg", "data >:"+data+":<");
    }
}
var SSH2Shell = require ('./user_modules/ssh2shell')
var SSH = new SSH2Shell(host);
SSH.connect();
```
This still doesn't fix the prompt detection.

**Comment by unchained-za** [comment]
```
$ time ../../bin/node/node/bin/node  cmp-202b.js  
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:

(Cisco Controller) 
User: :<
data >:U:<
data >:sernam
Password::<
data >:*:<
data >:***********:<
data >:
(Cisco Controller) >:<
10.65.1.140: Class.commandTimeout
10.65.1.140: Timeout command:  response: 

(Cisco Controller) 
User: Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Run exit
10.65.1.140: Exit command: Stream: close
10.65.1.140: Class.error
Timeout error: 10.65.1.140: Command timed out after 5 seconds
10.65.1.140: Connection.close
Closed
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140


(Cisco Controller) 
User: Sintrex
Password:************
(Cisco Controller) >
10.65.1.140: Stream.close

real	0m12.008s
user	0m0.135s
sys	0m0.012s
$ 

```

**Comment by cmp-202** [comment]
Thanks for that. 
Are you able to test this against the ssh2shell code before I made the changes to handle showing the banner (pre prompt detection after no more data timeout). 
The timeout is due to it failing to step into the first command from detecting the first prompt.
The data event content doesn't look like it should fail prompt detection and the last data event is just the prompt line which would match the regex. It would also reset the timer looking for no more data events to proceed but instead it is the command timeout firing. That could be worth a look. I will check that later.

**Comment by cmp-202** [comment]
I have made a change to the current master to improve checking if a command is present.
Can you give that a try.

**Comment by unchained-za** [comment]
I tried with commit 782c501 with the following result:

```
$ time ../../bin/node/node/bin/node  cmp-202b.js 
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:
:<
data >:
(Cisco Controller) 
User: :<
data >:U:<
data >:ernam
Password::<
data >:*:<
data >:***********:<
data >:
(Cisco Controller) >:<
10.65.1.140: Class.commandTimeout
10.65.1.140: Timeout command:  response: 

(Cisco Controller) 
User: Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Run exit
10.65.1.140: Exit command: Stream: close
10.65.1.140: Class.error
Timeout error: 10.65.1.140: Command timed out after 5 seconds
10.65.1.140: Connection.close
Closed
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140


(Cisco Controller) 
User: Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Stream.close

real	0m11.658s
user	0m0.145s
sys	0m0.009s
$ 
```

Then with your latest code:
```
$ time ../../bin/node/node/bin/node  cmp-202b.js 
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:

(Cisco Controller) 
User: :<
10.65.1.140: first prompt detected
10.65.1.140: Host.commands: show clock,show clock
10.65.1.140: Next command from host.commands: show clock
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: show clock
data >:s:<
data >:how clock
Password::<
data >:************:<
data >:
User::<
data >:Usernam
Password::<
data >:************:<
data >:
(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 show clock
Response: 
Password:************
User:Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Raising commandComplete event
10.65.1.140: Class.commandComplete
10.65.1.140: Host.commands: show clock
10.65.1.140: Next command from host.commands: show clock
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: show clock
data >:show clock

Incorrect usage.  Use the '?' or <TAB> key to list commands.

(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 show clock
Response: 

Incorrect usage.  Use the '?' or <TAB> key to list commands.

(Cisco Controller) >
10.65.1.140: Raising commandComplete event
10.65.1.140: Class.commandComplete
10.65.1.140: No commands so exit
10.65.1.140: Run exit
10.65.1.140: Exit command: Stream: close
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140


(Cisco Controller) 
User: show clock
Password:************
User:Usernam
Password:************
(Cisco Controller) >show clock

Incorrect usage.  Use the '?' or <TAB> key to list commands.

(Cisco Controller) >
10.65.1.140: Stream.close
10.65.1.140: Connection.close
Closed

real	0m10.253s
user	0m0.144s
sys	0m0.011s
$ 

```

**Comment by cmp-202** [comment]
Wow so it looks like it has fixed it. I needed to confirm that the current command was something rather than anything. I added checking the length of the string which has done it.

**Comment by cmp-202** [comment]
published fix to npm

**Comment by unchained-za** [comment]
I've lost access to the WLC host, will have to check later again, possibly only this evening. Midday here now.

**Comment by cmp-202** [comment]
Okay I'll keep my fingers crossed. Your last output is exactly as I would expect to see for a working case so fingers crossed. It's a good change anyway.

This is the good bit where it identifies prompt and triggers command complete.
```
data >:
(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 show clock
Response: 
Password:************
User:Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Raising commandComplete event
```

**Comment by unchained-za** [comment]
I could try it again with your latest code: It seems like the first command is skipped, if I duplicate it, I actually get it's result, else nothing for it.

The 2 valid commands in this case that I used, are
```
show time
logout
```
Logout requires a yes/no confirmation too. Show time shows it's output if I repeat it. Here the output without a repetition:
```
$ time ../../bin/node/node/bin/node  cmp-202b.js 
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:

(Cisco Controller) 
User: :<
10.65.1.140: first prompt detected
10.65.1.140: Host.commands: show time,logout
10.65.1.140: Next command from host.commands: show time
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: show time
data >:s:<
data >:how time
Password::<
data >:************:<
data >:
User::<
data >:Usernam
Password::<
data >:************:<
data >:
(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 show time
Response: 
Password:************
User:Usernam
Password:************
(Cisco Controller) >
10.65.1.140: Raising commandComplete event
10.65.1.140: Class.commandComplete
10.65.1.140: Host.commands: logout
10.65.1.140: Next command from host.commands: logout
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: logout
data >:logout
The system has unsaved changes.
Would you like to save them now? (y/N) :<
10.65.1.140: Class.commandTimeout
10.65.1.140: Timeout command: logout response: 
The system has unsaved changes.
Would you like to save them now? (y/N) 
10.65.1.140: Run exit
10.65.1.140: Exit command: Stream: close
10.65.1.140: Class.error
Timeout error: 10.65.1.140: Command timed out after 5 seconds
10.65.1.140: Connection.close
Closed
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140


(Cisco Controller) 
User: show time
Password:************
User:Usernam
Password:************
(Cisco Controller) >logout
The system has unsaved changes.
Would you like to save them now? (y/N) 
10.65.1.140: Stream.close

real	0m15.249s
user	0m0.127s
sys	0m0.011s
$
```

**Comment by cmp-202** [comment]
I know what it is let me fix it.

**Comment by cmp-202** [comment]
Okay so that is committed to master. It was detecting the first data timeout without also doing the standard prompt check. That affected the first command because it thought the first data timeout was the time to load and run the first command even though it wasn't a prompt, it was asking for the username.

The logout handling has to be done in onCommandProcessing by detecting the logout question and responding with a stream.write(). The timeout is happening because there is no response to the question and so it closes the connection.

**Comment by unchained-za** [comment]
Sorry for this very late reply, I could test again now. It seems like it can't even login now:

```
$ time ../../bin/node/node/bin/node  cmp-202b.js
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:
:<
data >:
(Cisco Controller)
User: :<
```
... long wait
```
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140

10.65.1.140: Stream.close
10.65.1.140: Connection.close
Closed

real    1m20.441s
user    0m0.148s
sys     0m0.014s
$
```
I'll add the logout handling later. These Cisco hosts are really troublesome!

**Comment by cmp-202** [comment]
Sigh yeah your telling me. 
So I have added a fix and some more debug to master. See how that goes.

**Comment by cmp-202** [comment]
For the onCommandProccessing code look at the later code snippets from issue #44 and instead of testing for `command = "cusp"` test that `command.length < 1` as in no command which is your case. You might only need the username and password prompt tests and responses.

**Comment by unchained-za** [comment]
Hi, mostly success, thanks.

First, my commands, then comments after sections:
```
commands:           [
	"show time",
	"config paging disable",
	"show run-config\n",
	"logout"
},
```
Initial part until before "show run-config":
```
$ time ../../bin/node/node/bin/node  cmp-202b.js
10.65.1.140: Connection.connect
Connected
10.65.1.140: Connection.ready
Ready
10.65.1.140: Connection.shell
data >:
:<
data >:
(Cisco Controller)
User: :<
10.65.1.140: No command processing to first prompt
data >:U:<
data >:sernam
Password::<
10.65.1.140: No command processing to first prompt
data >:************:<
10.65.1.140: No command processing to first prompt
data >:
(Cisco Controller) >:<
10.65.1.140: first prompt detected
10.65.1.140: Host.commands: show time,config paging disable,show run-config
,logout
10.65.1.140: Next command from host.commands: show time
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: show time
data >:show time

Time............................................. Fri Nov 10 22:31:43 2017

Timezone delta................................... 0:0
Timezone location................................ (GMT +2:00) Jerusalem

NTP Servers
    NTP Polling Interval.........................     3600

     Index     NTP Key Index                  NTP Server                  NTP Msg Auth Status
    -------  ----------------------------------------------------------------------------------
       1              0                                  10.40.1.11       AUTH DISABLED


(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 show time
Response:

Time............................................. Fri Nov 10 22:31:43 2017

Timezone delta................................... 0:0
Timezone location................................ (GMT +2:00) Jerusalem

NTP Servers
    NTP Polling Interval.........................     3600

     Index     NTP Key Index                  NTP Server                  NTP Msg Auth Status
    -------  ----------------------------------------------------------------------------------
       1              0                                  10.40.1.11       AUTH DISABLED


(Cisco Controller) >
10.65.1.140: Raising commandComplete event
10.65.1.140: Class.commandComplete
10.65.1.140: Host.commands: config paging disable,show run-config
,logout
10.65.1.140: Next command from host.commands: config paging disable
10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: config paging disable
data >:config paging d:<
data >:isable


(Cisco Controller) >:<
10.65.1.140: Normal prompt detected
10.65.1.140: Command complete:
Command:
 config paging disable
Response:


(Cisco Controller) >
10.65.1.140: Raising commandComplete event
10.65.1.140: Class.commandComplete
```
The "show run-config" prompt for an <enter> before actually starting ouput, so I just added a '\n' to the command that solved that. The actual output is very slow so I only got the first block as it seems to timeout, will have to adjust the timeout for the run-config command. On some Cisco switches I've seen it taking up to about 3 minutes to complete the command with a significant wait in the beginning before any output.
```
10.65.1.140: Host.commands: show run-config
,logout
10.65.1.140: Next command from host.commands: show run-config

10.65.1.140: Notifications: Normal Command to run
10.65.1.140: running: show run-config

data >:show run-config

Press Enter to continue...


System Inventory
NAME: "Chassis"    , DESCR: "Cisco 5500 Series Wireless LAN Controller"
PID: AIR-CT5508-K9,  VID: V03,  SN: xxxxxxxxxx

Burned-in MAC Address............................ xx:xx:xx:xx:xx:xx
Power Supply 1................................... Present, OK
Power Supply 2................................... Absent
Maximum number of APs supported.................. 500

```
Here is the wait for more output, eventual timeout.
```
:<
10.65.1.140: Command waiting
10.65.1.140: Class.commandTimeout
10.65.1.140: Timeout command: show run-config
 response: show run-config

Press Enter to continue...


System Inventory
NAME: "Chassis"    , DESCR: "Cisco 5500 Series Wireless LAN Controller"
PID: AIR-CT5508-K9,  VID: V03,  SN: xxxxxxxxxx

Burned-in MAC Address............................ xx:xx:xx:xx:xx:xx
Power Supply 1................................... Present, OK
Power Supply 2................................... Absent
Maximum number of APs supported.................. 500


10.65.1.140: Run exit
10.65.1.140: Exit command: Stream: close
10.65.1.140: Class.error
Timeout error: 10.65.1.140: Command timed out after 5 seconds
10.65.1.140: Connection.close
Closed
10.65.1.140: Stream.finish
+++ onEnd
10.65.1.140: Session Text:
Connected to 10.65.1.140


(Cisco Controller)
User: Usernam
Password:************
(Cisco Controller) >show time

Time............................................. Fri Nov 10 22:31:43 2017

Timezone delta................................... 0:0
Timezone location................................ (GMT +2:00) Jerusalem

NTP Servers
    NTP Polling Interval.........................     3600

     Index     NTP Key Index                  NTP Server                  NTP Msg Auth Status
    -------  ----------------------------------------------------------------------------------
       1              0                                  10.40.1.11       AUTH DISABLED


(Cisco Controller) >config paging disable


(Cisco Controller) >show run-config

Press Enter to continue...


System Inventory
NAME: "Chassis"    , DESCR: "Cisco 5500 Series Wireless LAN Controller"
PID: AIR-CT5508-K9,  VID: V03,  SN: xxxxxxxxxx

Burned-in MAC Address............................ xx:xx:xx:xx:xx:xx
Power Supply 1................................... Present, OK
Power Supply 2................................... Absent
Maximum number of APs supported.................. 500


10.65.1.140: Stream.close

real    0m14.848s
user    0m0.148s
sys     0m0.020s
[sintrex@ww-sintelligent sshService]$
```
I must still look into the logout response, should be able to handle that (I hope!)
```
The system has unsaved changes.
Would you like to save them now? (y/N)
```

**Comment by cmp-202** [comment]
In onCommandProcessing  do a check that the command is logout and do a regex test against the response to look for say `y/n` or whatever will identify that prompt and then respond stream.write("y\n") or stream.write("\n").

**Comment by unchained-za** [comment]
Thank you so much, I'll just have to try this out and then confirm that all the previous situations still work fine too.

**Comment by unchained-za** [comment]
Thank you so much, I'll just have to try this out and then confirm that all the previous situations still work fine too.

**Comment by unchained-za** [comment]
I've added the onCommandProcessing code for the logout handling, but it still tries to do the _doExit() which then times out to give a timeout error at the end.

**Comment by cmp-202** [comment]
Okay so your logout command terminates the session after you respond to the `save (y/n)`?
Normally `exit` is the command to terminate the session and it is handled automatically when there are no more commands.
The only way you can avoid the timeout error is to handle it in `onCommandTimeout` by testing if the current command is `exit` and your command array length is zero. If it is then call `this._stream.close()`

**Comment by cmp-202** [comment]
Probably better to use `this._runExit()` instead of stream.close()` that function does that anyway

**Comment by cmp-202** [comment]
If it times out add `this.sshObj.exitCommands = []` before calling `this._runExit()`

**Comment by unchained-za** [comment]
Thanks, will try that these options.

**Comment by cmp-202** [comment]
Recent changes have been published to npm.

**Comment by unchained-za** [comment]
Thank you again, all seems to work now. I'll just keep a flag that logout have been used to terminate the session so the final timeout can be avoided. I know there is another Cisco special case that I have to handle, but as far as I remember it only relates to prompts and specific commands. Then of course also the command timeout issues that I'll have to adjust, as I've recently discovered on some firewalls.

I really appreciate all your effort on this.

**Comment by cmp-202** [comment]
My pleasure. 
I think the combination of this and the previous issue has improved the prompt handling code so it is more robust in different hardware environments. Interesting seeing it used in this context and even better seeing it working after all our work on it.

Good idea using a flag for logout command.

```javascript
if (this.sshObj.logout and this.sshObj.commands.length < 1){
    this.sshObj.exitCommands = [];
    //this also shifts the last buffer to sessionText before closing the stream
    this._runExit();
}
```

If you are happy this issue is resolved I can close it.

**Comment by unchained-za** [comment]
Yes, very happy at this stage. Thank you very much. You've been extremely helpful!

**Comment by Fritouz12** [comment]
Hi! I reply to this post 5 years after but I'm doing exactly the same and have an issue: I'm using a read only access from the Cisco WLC and I cannot disable de pagination (with the command _config paging disable_ so when I run show client detail for instance I need to press enter to show the full output of the command> Do you know if there is a way to do it without disabling pagination ?
Can we simulate enter key with ssh2shell ?
Thanks !

**Comment by cmp-202** [comment]
Hi,
One option could be to use [host.onCommandProccessing(command, response, sshObj, stream){}](https://github.com/cmp-202/ssh2shell#responding-to-non-standard-command-prompts) to detect the command and presence of paging in the response and either send enter via `stream.write("" + sshObj.enter);` or add it to the array of commands so it is the next command to run `sshObj.commands.unshift("" + sshObj.enter)`. You will likely need a variable to track sending on current command and then resetting for new commands responding with paging.

There is also [persistent-shell](https://github.com/cmp-202/persistent-shell)
