### ISSUE TITLE
Issue with passing a existing array to commands: 

### ISSUE THREAD

**Issue by zoosdamoose** [cmp-202/ssh2shell#47]
Currently I am using this module to login and run several different sets of commands on a array of devices and recording the output from those hosts. I've been accomplishing this by looping thru my array of devices and updating the host object. This works great, an example of code is below.

var arrayOfHosts = ['host1', 'host2']
    var routerLoop = arrayOfHosts.map(function(val){

        var host = {
          server:        {
            host:         val,
            userName:     "user",
            password:     "myPassword",
          },
          standardPrompt:     "#",
          streamEncoding:     "utf8",
          commands:           ['cmd1', 'cmd2'],
          verbose:            true,
          debug:              true, 
          idleTimeOut:        5000, 
        }
        
    SSH = new SSH2Shell(host),

    SSH.on('end', function (sessionText, sshObj) {
      console.log(sessionText)
    })
//Start the process
    SSH.connect();
    })

This works successfully and runs both cmd1 and cmd2 on each device. The issue arises when I try 
to pass cmd1 and cmd2 as array to commands:  an example is below
var arrayOfHosts = ['host1', 'host2']
var arrayOfCommands = ['cmd1', 'cmd2']

    var routerLoop = arrayOfHosts.map(function(val){

        var host = {
          server:        {
            host:         val,
            userName:     "user",
            password:     "myPassword",
          },
          standardPrompt:     "#",
          streamEncoding:     "utf8",
          commands:           arrayOfCommands,
          verbose:            true,
          debug:              true, 
          idleTimeOut:        5000, 
        }
        
    SSH = new SSH2Shell(host),

    SSH.on('end', function (sessionText, sshObj) {
      console.log(sessionText)
    })
//Start the process
    SSH.connect();
    })

When this is the case the module splits the commands between each device so that arrayOfCommands[0] is run on arrayOfHosts[0] and arrayOfCommands[1] is run on arrayOfHosts[1]. Needless to say this has kinda stumped me as the value of commands: is the same in either case regardless and passing an array to commands: works on a single host as well. ex below  

var arrayOfHosts = ['host1']
var arrayOfCommands = ['cmd1', 'cmd2']
    var routerLoop = arrayOfHosts.map(function(val){

        var host = {
          server:        {
            host:         val,
            userName:     "user",
            password:     "myPassword",
          },
          standardPrompt:     "#",
          streamEncoding:     "utf8",
          commands:          arrayOfCommands,
          verbose:            true,
          debug:              true, 
          idleTimeOut:        5000, 
        }
        
    SSH = new SSH2Shell(host),

    SSH.on('end', function (sessionText, sshObj) {
      console.log(sessionText)
    })
//Start the process
    SSH.connect();
    })

**Comment by cmp-202** [comment]
So sorry about taking so long to respond but I don't seem to be getting the emails, will look into that.

This is something I had considered adding. Instead of the constructor just taking a host object coding it so it could take an array of hosts and process each one as it does with tunnaling multiple hosts. In the mean time here are my questions etc:
 
Why do you need an array of commands declared outside the scope of the host object if they are always the same for each host? Given this is causing you the grief just return the commands definition to the host object as in your first code example to resolve it. 

I also don't see the benefit of using array.map() as nothing is ever returned from the map callback function so routerLoop will be empty. SSH2shell events will never be returnable from that callback.

Not sure if this will help but this is how I would write it:
```javascript
var arrayOfHosts = ['192.168.0.1', '192.168.0.2']
var host = {
      server:        {
        userName:     "user",
        password:     "myPassword",
      },
      standardPrompt:     "#",
      streamEncoding:     "utf8",
      commands:         ['cmd1', 'cmd2'],
      verbose:            true,
      debug:              true, 
      idleTimeOut:        5000, 
}
arrayOfHosts.forEach(function(serverHost){
    host.server.host = serverHost
    SSH = new SSH2Shell(host)
    SSH.connect(function(sessionText){
        console.log(sessionText)
    });
})
```

If having the commands defined in an array is for some reason valid I will need some debug content to see the state of process for each host and commands. Always helpful to enable me to see what is going on as it processes. Attach a file rather than posting the content.

**Comment by cmp-202** [comment]
I might make a branch for this and do some work on it.

**Comment by cmp-202** [comment]
So I have made a branch called Multiple-Hosts for you to try. Instead of looping through an array of hosts creating the SSH2shell instance each time create your array of hosts and pass it into the constructor like you do with the normal host object. When you run SSH.connect() all hosts in the array will be processed. 

I have modified the /test/simple.js file to give you an example. 

Note each host object mush be an actual object not a reference or it will break.

**Comment by cmp-202** [comment]
I think the arrayOfCommands content is being changed by each SSH2shell instance as it pops a command from the array to run it. The arrayOfCommands is a reference in each host object and each host is processed through the map callback function (asynchronous). Each host will be run with the arrayOfCommands in a variable state depending on what other instances had modified it.

Solution: (current code) don't use a referenced array that will be modified with each host process.

Try this:
Define the commands as an object and merge it with the host object to create a new object.

```javascript
var arrayOfHosts = ['192.168.0.1', '192.168.0.2']
//use an object for commands so it can be merged into a new scoped host object
var arrayOfCommands = {commands: ['cmd1', 'cmd2']}
var host = {
      server:        {
        userName:     "user",
        password:     "myPassword",
      },
      standardPrompt:     "#",
      streamEncoding:     "utf8",
      verbose:            true,
      debug:              true, 
      idleTimeOut:        5000, 
}

arrayOfHosts.forEach(function(serverHost){
    //merge into a new object rather than using references
    var thisHost = Object.assign({}, host, arrayOfCommands)
    thisHost.server.host = serverHost
    SSH = new SSH2Shell(thisHost)
    SSH.connect(function(sessionText){
        console.log(sessionText)
    });
})
```

**Comment by cmp-202** [comment]
The Multiple-Hosts branch is working using an array of hosts sent to the constructor.

```javascript
var host = {
  server: {
    host:        host,
    userName:    username,
    password:    password
  }
},
host2 = {commands: ["cd ~"]},
host3 = {commands: ["ls"]}

Object.assign(host2,host)
Object.assign(host3,host)
host.commands = ["ls -la"]

var SSH = new SSH2Shell([host,host2,host3]),
callback = function( sessionText ){
  console.log ( "-----Callback session text:\n" + sessionText)
  console.log ( "-----Callback end" )
}

SSH.connect(callback)
```

**Comment by zoosdamoose** [comment]
Great! I will test this out this week. Sorry for the late response on my end as well.

**Comment by zoosdamoose** [comment]
Thank you for the work on the Multiple Hosts branch along with the documentation  it has been working successfully for me for a week now since implementing it. 

I have another situation related to multiple hosts that I am attempting to figure out while using this module.. and that is parallel connections/commands running across multiple hosts. 
The premise is this. 
1. Run a change that requires changes across multiple hosts 
2. Step/Stage error handling and verification throughout the completion process. 
ex. (the module reports 'Ready' on all hosts before proceeding with running the individual host's commands. That way if one host errors or times out the entire process is exited and no commands are run on any of the hosts.)

As it stands today I can build the step validation/error handling on a per host basis using the event handlers you have created, onCommandTimeout/Processing/Complete ect.. but each host goes down it's own path regardless of the steps completed/progress of the other hosts.

**Comment by cmp-202** [comment]
Hi,
So from what I understand you want to bail on the process if a host has a fail state that you catch.
The solution might be to set the hosts array to nothing in one of the handlers when it fails.
If the SSH.hosts is set to [] then it won't have other hosts to loop through.

```javascript
  //catch failure where appropriate
  SSH.on('end', function (sessionText, sshObj) {
    if([your condiftion]){
       //remove any further hosts so they are not processed
      this.hosts = [];
    }
  });
```

**Comment by cmp-202** [comment]
New code merged and published to npm. v1.9.0

**Comment by cmp-202** [comment]
Given the orriginal issue was reported as working I am closing it.
