### ISSUE TITLE
1.8.6 and ping

### ISSUE THREAD

**Issue by simakwm** [cmp-202/ssh2shell#48]
I have a small function on my socket.io server to execute ping on a remote server:

```
`function cmdPing(target, socket) {
  let started = false;
  let executable = 'ping';
  if (target.typeip === 'IPv6') {
    executable = 'ping6';
  }
  HOST.commands = [`${executable} -c5 ${target.pingtarget}`];
  const ssh = new Ssh2shell(HOST);
  ssh.on('error', (err, type) => {
    console.log(err);
    socket.emit(CMDPING, { status: 'error', text: type });
  });
  ssh.on('data', (text) => {
    const s = _.trim(text);
    const PROMPT = /@.*:~\$/;
    if (!PROMPT.test(s) && !_.isEmpty(s)) {
      if (/^(PING|ping:|unknown).*/.test(s)) {
        started = true;
      }
      // skipped non ping output lines
      if (started) {
        console.log(s);
        socket.emit(CMDPING, { status: 'working', text: s });
      }
    }
  });
  ssh.on('end', () => {
    socket.emit(CMDPING, { status: 'finished', text: null });
  });
  ssh.connect();
}`
```

It timeouts just after the first ping reply arrives. It only happens with ping (!?). 1.8.4 doesn't have this issue.

**Comment by cmp-202** [comment]
Hi thanks for taking the time to post this issue.
Yes from 1.8.4 there were a number of changes to prompt detection which has obviously caused the problem. I am not quite sure why it worked and now it doesn't.

Have you tried increasing the timeout time to accomodate the ping command processing time?

Can you provide the timeout event debug/verbose (without sensitive detail) or debug/verbose around that first ping command execution and timeout so I can see what the content and process was. Attach as a file.
Thanks

**Comment by simakwm** [comment]
I will try to post some debug logs tomorrow.
Strange fact: If I set idleTimeout to 60000, it disconnects *immediately after first ping reply* saying that timeout of 60 seconds was reached.
:/

**Comment by cmp-202** [comment]
That's great! Not. I will have a look at that first to see if I can replicate it.
One other question I had is does it work detecting the prompt if you run a basic command like `cd ~` or something similar. I would also output your sessionText it might have clues.

With your ping command I noticed there is no space between -c and the number. It might just be a typo in your post but worth checking. The command timeout should reset on every data event so endless ping responses shouldn't cause it. The prompt detection is done after the last data event by checking the end of the buffer for the valid prompt expression. If it is not found the command timeout timer waits based on what is set (well is supposed to) and then emits the commandTimeout event. 

Before 1.8.4 the prompt was checked every data event.

Some thoughts:
Looking at your code I would not use the data event I would use commandComplete with a test that the command has ping in it and emit the full response to the socket if it does. Or you can use commandProcessing to emit the ping has started and commandComplete as above again using a check that the command contains ping in both cases. 
Same with console.log command, I wouldn't us it in a data event except for debug. Emit msg using response in the commandComplete handler, not in commandProcessing as it is the buffer as it loads. 
The data event content is redundent using the methods given. No need for defining and setting start, use the command as the flag if it is the only command. If you have to use a flag use sshObj.started to maintain the flag with the commandProcessing and commandComplete handlers.
The on error should be defined as part of the HOST object `HOST.onError` so it replaces the default error handler and stops duplicate messages in the console.
If your prompt requirements are as tested in your post then set HOST.standardPrompt to those.

**Comment by cmp-202** [comment]
Can you run that ping command maually on the host and see what happens.

**Comment by cmp-202** [comment]
Yes I do understand what ping -c does.
The man page for ping indicates a space betweem -c and the max count number.
An example on [thegeekstuff.com](https://www.thegeekstuff.com/2009/11/ping-tutorial-13-effective-ping-command-examples/) gives the following: `$ ping -c 5 google.com`

**Comment by cmp-202** [comment]
No commandProcessing won't give you the individual data event content as it happens which is no good to you. It gives you the buffer as it loads (appended). 

I have simplified your handler to only return the data while the command contains 'ping' which should do the same thing without all the checks and started flag.
```javascript
  ssh.on('data', (text) => {
      const s = _.trim(text);    
      if (this.command.indexOf("ping") >= 0) {
        console.log(s);
        socket.emit(CMDPING, { status: 'working', text: s });
      }
    }
  });
```

**Comment by simakwm** [comment]
> Can you run that ping command maually on the host and see what happens.

It happens exactly what it is expected :/

> The man page for ping indicates a space betweem -c and the max count number.

It does the same thing with or without a space between "-c" and "5".

> I have simplified your handler to only return the data while the command contains 'ping' which should
do the same thing without all the checks and started flag.

Thanks. The checking is used to strip login messages that comes before ;) 

Well, for now I will downgrade to 1.8.4 as it was working as I needed.

**Comment by cmp-202** [comment]
Thanks. 
I have some time today to fire up my VM's to do some testing and see if I canreplicate it.

**Comment by cmp-202** [comment]
Can you pull from master and try it again.

Here is a code example for you to try.
```javascript

    var HOST = {
        server: {     
            host:         host,
            userName:     username,
            password:     password
        },
        onError: function(err, type, close, callback) {
            console.log(err)
            socket.emit(CMDPING, { status: 'error', text: type })
            if (close === true){connection.end()}
            //I haven't included callback
        },
        onCommandProcessing: function( command, buffer, sshObj, stream ){
            if (command.indexOf("ping") >= 0) {
                console.log("working");
                socket.emit(CMDPING, { status: 'working', text: nul });
            }
        },
        onCommandComplete: function( command, response, sshObj ){
            if (command.indexOf("ping") >= 0) {
                console.log(response);
                socket.emit(CMDPING, { status: 'complete', text: response });
            }
        },
        onEnd: function( sessionText, sshObj ){
            console.log("status: 'finished'")
        }
    }
    
    function (target, socket){
        let executable = 'ping'
        if (target.typeip === 'IPv6'){executable = 'ping6'}
        HOST.commands = [`${executable} -c5 ${target.pingtarget}`]
        //run the commands in the shell session
        var ssh = new SSH2Shell(HOST)
        ssh.connect()
    }
```

**Comment by cmp-202** [comment]
published to npm 1.8.7

**Comment by simakwm** [comment]
Thanks for the piece of code.

And 1.8.7 works fine even with the old code =)

**Comment by cmp-202** [comment]
Very good. Thanks for taking the time to bring it up and work with me on it.

Andrew
