### ISSUE TITLE
Running commands on Windows machine (cmd)

### ISSUE THREAD

**Issue by ChenAlon** [cmp-202/ssh2shell#49]
Hi,

I'm connecting to a windows machine via ssh but the commands do not seem to be running there properly.

The idleTimeOut property is set to 1000 * 60 * 60, so it's not the issue.
I tried to run various commands but no one is working.

This is the output:
```
192.168.56.2: Connection.connect
Connected to Win Server
192.168.56.2: Connection.ready
Ready
192.168.56.2: Connection.shell
192.168.56.2: No command processing to first prompt
192.168.56.2: No command processing to first prompt
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
192.168.56.2: First prompt detected
192.168.56.2: Host.commands: \release.bat
192.168.56.2: Next command from host.commands: \release.bat
192.168.56.2: Notifications: Normal Command to run
192.168.56.2: running: \release.bat
192.168.56.2: Command waiting
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
Data processing: data received timeout
^C
```

Any idea what is the issue and how I can solve it?

Thanks ahead!!

**Comment by cmp-202** [comment]
Can you turn on verbose and run a basic command like cd, ping or something else and just post the timeout output at the end that will show command and response.

**Comment by ChenAlon** [comment]
Thanks for the quick response!

This is the output:
```
$ node build/test.js
192.168.56.2: Connection.connect
Connected to Win Server
192.168.56.2: Connection.ready
Ready
192.168.56.2: Connection.shell
192.168.56.2: No command processing to first prompt
192.168.56.2: No command processing to first prompt
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
192.168.56.2: First prompt detected
192.168.56.2: Host.commands: cd \
192.168.56.2: Next command from host.commands: cd \
192.168.56.2: Notifications: Normal Command to run
192.168.56.2: running: cd \
192.168.56.2: Command waiting
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
Data processing: data received timeout
```

This is the script:
```
const WIN = {
    server: WIN_SERVER,
    commands: [
        'cd \\',
    ],
    verbose: true,
    debug: true,
    enter: '\r\n',
    idleTimeOut: 1000 * 60 * 60,
    connectedMessage: 'Connected to Win Server',
    onCommandTimeout:    function( command, response, stream, connection ) {
        this.emit('msg', command);
        this.emit('msg', response);
        this.emit('msg', stream);
        this.emit('msg', connection);
    },
};


//Create the new instance
const SSH2Shell = require('ssh2shell');
const SSH = new SSH2Shell(WIN);

//Add a commandComplete handler used by all hosts
SSH.on('commandComplete', function onCommandComplete(command, response, sshObj) {
    //we are listing the dir so output it to the msg handler
    this.emit('msg', response);
});

//Add an on end event handler used by all hosts
SSH.on('end', function (sessionText, sshObj) {
    this.emit('msg', sshObj.server.host + ':\n' + sessionText);
});

//Start the process
SSH.connect();
```

**Comment by cmp-202** [comment]
Can you remove `enter: '\r\n',` first of all.

**Comment by ChenAlon** [comment]
Yes, I removed it.
At first, I thought that was the issue.

I still get the same result :/

**Comment by cmp-202** [comment]
Can you also remove host.onCommandTimeout handler.
On commandComplete is redundant because you see the output in the on end event when you emit the sessionText. 
Also turn off debug we have enough process info at this point let's just look for verbose.

**Comment by cmp-202** [comment]
It would be good to confirm the required terminator for the windows ssh session simply because if it is wrong then the command won't actually run, it will just timeout waiting for the enter to action it.

**Comment by ChenAlon** [comment]
Done.

This is the output:
```
$ node build/test.js
Connected to Win Server
Ready
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
192.168.56.2: Host.commands: cd \
192.168.56.2: Next command from host.commands: cd \
192.168.56.2: running: cd \
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
```

Regarding the terminator, I'm also thinking that this is the issue, that's why I changed the ```enter``` value to ```\r\n```. 
Eventually, the command is running on a windows CMD.

**Comment by cmp-202** [comment]
Process for running the command and timeout:
 1. Send the command text followed by the line tetminator say \n.
 2. If anything results from that we start receiving data events which are added to a buffer untill not more data is received.
 3. After the last data event the end of the buffer is checked for a valid prompt pattern and if it is found the command complete event is raised. If no prompt is detected a commandTimeout event is raised.
 1a. If no data events after running the  command then the commandTimeout is raised.

**Comment by cmp-202** [comment]
I am not seeing the default timeout verbose response in your output or in the earlier output.


`Timeout command: #{command} response: #{response}`

**Comment by ChenAlon** [comment]
This is the output:

```
$ node build/test.js
Connected to Win Server
Ready
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
192.168.56.2: Host.commands: cd \ \n
192.168.56.2: Next command from host.commands: cd \ \n
192.168.56.2: running: cd \ \n
192.168.56.2: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
192.168.56.2: ASCII filter: [^
 -~], filtered: true
192.168.56.2: Timeout command: cd \ \n response: [5;1H
Timeout error: 192.168.56.2: Command timed out after 5 seconds
Command Timeout error: Command `cd \ \n` timed out after NaN seconds. command: cd \ \n
Closed
192.168.56.2:
Connected to 192.168.56.2
cd \ \n[5;1Hcd \ \n[5;1H
```

**Comment by ChenAlon** [comment]
I found something that may help.

When I'm doing ssh directly in the terminal with these commands it's working as expected:

```
$ ssh user@192.168.56.2 "cd \ & npm run release"
user@192.168.56.2's password:

> App@0.3.0 release C:\
> node build/release.js && npm run test --appPath='/'

[06:39:45.184] [info] C:\
```

**Comment by cmp-202** [comment]
Its 3:40am here so I need to sleep. I will fire up my VM's tomorrow and try it.
Are you connecting from a Windows OS or Linux?
Have you tried doing it manually with identical settings like line terminator?
Might be worth adding an on data event handler that outputs each data event to the console to give raw verbose.

**Comment by cmp-202** [comment]
Ahhh prompt format is different C:\

**Comment by cmp-202** [comment]
Maybe try:
standardPrompt: ":\"

**Comment by cmp-202** [comment]
Ops that got altered dropped the \\
`standardPrompt: ":\"`

**Comment by cmp-202** [comment]
Don't worry about the prompt the first prompt is detecting correctly using >.
That tumeout output looks insane! It's just garbage but it doesn't make sense can you turn off the two filters for formatting and non-standard ascii to see if it stays the same.

**Comment by ChenAlon** [comment]
I found a solution meanwhile, I'm doing it manually.  
running the ssh tunnel and commands as part of the commands like this:
```
'ssh -i "~/.ssh/id_rsa" user@192.168.56.2 "cd \\ & npm run release & exit"',
```

**Comment by cmp-202** [comment]
I tested from Windows 10 cmd running node back through the localhost to OpenSSH on the same machine (not the win10 beta version) and it worked without issue. See below.

The garbage showen in the timeout response you provided is the cause of the timeout but what is the cause of the garbage. I would still recommend attaching the data event handler so we can see the raw incoming characters without my code interacting with it. 

 ```
SSH.on ("data", function(data){
  console.log (data);
});
```

Can you output the result of the ssh command: 
```
ssh -i "~/.ssh/id_rsa" user@192.168.56.2 > file.log << EOF
cd \\ 
npm run release 
exit
EOF
```

My test:
```
ssh2shell\>node test/simple.js
{ server:
   { host: 'localhost',
     port: 22,
     userName: 'user',
     password: 'password' },
  debug: true,
  verbose: false,
  commands: [ 'cd /' ] }
localhost: Connection.connect
Connected
localhost: Connection.ready
Ready
localhost: Connection.shell
localhost: No command processing to first prompt
localhost: First prompt detected
localhost: Notifications: Normal Command to run
localhost: Command waiting
localhost: Normal prompt detected
localhost: Raising commandComplete event
localhost: Class.commandComplete
localhost: No commands so exit
localhost: Run exit
localhost: Exit command: Stream: close
localhost: Stream.finish
localhost: Class.end
-----Callback session text:
Connected to localhost
cd /
C:\>
-----Callback end
localhost: Stream.close
localhost: Connection.close
Closed
```

**Comment by ChenAlon** [comment]
Thanks Andrew!!

I'll check it tomorrow when I'll be at the office and will update here accordingly.

**Comment by cmp-202** [comment]
No Prob.
Can you give me details of the Windows SSH implementation and any ssh config details that are non standard if you have access to that. What SSH server are you using? Windows SSH beta, OpenSSH or something else? What version of ssh2shell are you running?

There is some suggestion that the text formatting is different from what ssh2shell has as the default filtering expression so you don't just get the text. Default is `host.textColorFilter = /(\[{1}[0-9;]+m{1})/g`. Based on the content I think that is viable. 
Even with the command response having that content the next prompt should still be reached unless the command is hung. I saw in a previous post you used `cd \ \n` which is invalid. Shh2shell handles the `\n` to run each command so the command should be `cd \` but that should still fall back to the prompt instead of timing out. 
A more left field option was that the SSH2 psuedo-tty term mode of vt100 needs to be changed which cant currently be done, I can add that.

So two issues command garbage and timeout (no prompt or premature timeout) to resolve.

Here is my test code for you to try:
```javascript
var host = {
  server: {     
    host:         Host_Address,
    userName:     "username",
    password:     "password"
  },
  commands: ["cd /"],
  debug:          true,
  verbose:        false
};

var SSH2Shell = require ('ssh2shell');
var SSH = new SSH2Shell(host),
    callback = function( sessionText ){
          console.log ( "-----Callback session text:\n" + sessionText);
          console.log ( "-----Callback end" );
      }
//SSH.on("data",function(data){console.log( data);});
SSH.connect(callback);
```

**Comment by ChenAlon** [comment]
Hi,

I used [Bitvise client]https://www.bitvise.com/ssh-client-download) to install the SSH.
SSH2Shell: 1.8.7

This is the output of your code:
```
$ node build/test.js
192.168.56.2: Connection.connect
Connected
192.168.56.2: Connection.ready
Ready
192.168.56.2: Connection.shell
192.168.56.2: No command processing to first prompt
192.168.56.2: No command processing to first prompt
192.168.56.2: First prompt detected
192.168.56.2: Notifications: Normal Command to run
192.168.56.2: Command waiting
Data processing: data received timeout
192.168.56.2: Class.commandTimeout
192.168.56.2: Run exit
192.168.56.2: Exit command: Stream: close
192.168.56.2: Class.error
Timeout error: 192.168.56.2: Command timed out after 5 seconds
192.168.56.2: Connection.close
Closed
192.168.56.2: Stream.finish
192.168.56.2: Class.end
-----Callback session text:
Connected to 192.168.56.2
cd /[5;1H
-----Callback end
192.168.56.2: Stream.close
```

**Comment by cmp-202** [comment]
Okay been buggering around with this most of the morning installing that SSH server and checking it. SSH2shell is actually working correctly the problem is the host ssh server you are connecting to.

The first problem is `host.enter = "\r"` is required instead of the default "\n" because it is not effectively hitting enter after the command so it just hangs. 

Second problem is that the output also uses a carage return which results in each line being appended to the last when output is to the console. Again probably "\r" instead of "\n". Outputting to a file would bypass this I suspect. It is also full of color formatting chars which makes it unreadable. 

The reason your client was probably working, if it was from the same place, was because it is configured to match all the server requirements and so wouldn't hit these problems.

The color code can be removed using the filter expression `host.textColorFilter` if you get the expression to match what is in the output. The standard Linux formatting is clearly not the same. 
From reading their brief technical information I couldn't see scope to remove formatting by changing the terminal type (without doing more research).

Options:
 

1. Easiest from my perspective would be to switch to OpenSSH or something similar for the server but that might not be an option for a number of reasons.
2. Set enter to "\r" and work out the filter required to remove the coloring and then deal with the carriage return issue in the output.

**Comment by cmp-202** [comment]
The difference is the default pattern `+m` changes to `+H`
try:
`host.textColorFilter = "(\[{1}[0-9;]+H{1})"`

**Comment by ChenAlon** [comment]
Thanks Andrew! I really appreciate your effort!

It's mostly working now :)
Except for the new line.

Now the output is:
```
192.168.56.2: Connection.connect
Connected
192.168.56.2: Connection.ready
Ready
192.168.56.2: Connection.shell
192.168.56.2: No command processing to first prompt
192.168.56.2: No command processing to first prompt
192.168.56.2: First prompt detected
192.168.56.2: Notifications: Normal Command to run
192.168.56.2: Normal prompt detected
192.168.56.2: Raising commandComplete event
192.168.56.2: Class.commandComplete
192.168.56.2: Notifications: Normal Command to run
192.168.56.2: Normal prompt detected
192.168.56.2: Raising commandComplete event
192.168.56.2: Class.commandComplete
192.168.56.2: No commands so exit
192.168.56.2: Run exit
192.168.56.2: Exit command: Stream: close
192.168.56.2: Stream.finish
192.168.56.2: Class.end
-----Callback session text:
cd /C:\>dir Volume in drive C is Windows 10 Volume Serial Number is EA7B-3605 Directory of C:\10/23/2017  09:13 AM    <DIR>          BGinfo03/06/2018  09:33 AM    <SYMLINKD>     chatflow [\\VBOXSRV\chatflow]03/05/2018  07:45 AM    <DIR>          cygwin6403/05/2018  04:17 AM    <DIR>          PerfLogs03/08/2018  09:15 AM    <DIR>          Program Files03/05/2018  01:59 AM    <DIR>          Program Files (x86)10/23/2017  09:16 AM    <DIR>          Users03/05/2018  02:44 PM    <DIR>          Windows               0 File(s)              0 bytes               8 Dir(s)  23,109,791,744 bytes freeC:\>
-----Callback end
192.168.56.2: Stream.close
192.168.56.2: Connection.close
Closed
```

**Comment by cmp-202** [comment]
Soooooo.
The output I get from that server software after the color codes removed was useless because I couldn't get any carriage returns (no lines) it was one line of text. I wrote the raw data and the sessionText to separate files so I could see the hidden chars and there were not end of line chars at all only esc periodically but not at expected line ends.
Even if you clean the output I doubt it will work. 
I spent most of the afternoon on this right down to checking the core code.

If all you want is for the command to run and/or you don't care about the output except being able to check a command response for a condition to act apon.

**Comment by ChenAlon** [comment]
Yes, I understand.
Will work with it like it is now and I'll try to change the client to OpenSSH.

THANKS!!

**Comment by cmp-202** [comment]
Recommendation is to bail on the wonderful windows SSH server software and all these problems will go away. 
I would recommend OpenSSH.

**Comment by cmp-202** [comment]
Hey thanks for bringing this to my attention. It is priceless testing to confirm funtionality of core code and checking flexibility under different environments. It's interesting identifying the response from a windows SSH service in comparison to the Linux based SSH which is mostly standardised (except for cisco routers ahhhhhh). Windows on the other hand likes doing it differently.
Cheers

Andrew

**Comment by cmp-202** [comment]
I think this is done and dusted.
