### ISSUE TITLE
ConnectTimeout option is not obeyed.

### ISSUE THREAD

**Issue by coreyman** [cmp-202/ssh2shell#50]
Tried several different ways to pass the ConnectTimeout option of ssh and none of them take affect -
 ssh:{
   Options: { "ConnectTimeout":0  }
 }

 ssh:{
   Options: { ConnectTimeout: 0  }
 },

 ssh:{
   ConnectTimeout: 0,
   Options: {   }
 },

**Comment by cmp-202** [comment]
Hi,
As per the host object deffinition in the readme try: 
`host={server: ssh: {ssh2connectionOption: 1234}}`

**Comment by cmp-202** [comment]
Is it the connecting timeout you are trying to set or the command timeout?

**Comment by coreyman** [comment]
connect timeout

**Comment by cmp-202** [comment]
That wasn't quite what I suggested, I didn't give you the param name. There is no ConnectTimeout in the SSH2 documentation for client connect params which my readme points to in a couple of places.

Try:

```
SSH2 Client.connect doc:
readyTimeout - integer - How long (in milliseconds) to wait for the SSH handshake to complete. Default: 20000
```

**Comment by coreyman** [comment]
Ahh I was looking at this http://man.openbsd.org/ssh  instead of https://github.com/mscdex/ssh2#client-methods

**Comment by cmp-202** [comment]
Yep that will do it, totally different beast.On 10/03/2018 4:43 PM, coreyman <notifications@github.com> wrote:Ahh I was looking at this http://man.openbsd.org/ssh  instead of https://github.com/mscdex/ssh2#client-methods

**Comment by coreyman** [comment]
I switched over to https://www.npmjs.com/package/ssh2 and created the same code with it. It obeys the readyTimeout option.

**Comment by cmp-202** [comment]
I am looking at pty settings at the moment so will also debug what is actually being passed to the ssh2.client.connect command for that timeout. Its a bit if a generic process so not sure what is happening there.  Also hard me to test that the increase is being followed. Cheers,AndrewOn 13/03/2018 9:48 AM, coreyman <notifications@github.com> wrote:I switched over to https://www.npmjs.com/package/ssh2 and created the same code with it. It obeys the readyTimeout option.

**Comment by cmp-202** [comment]
Sorry my example wasn't quite right. 
Try:

`host={
    server: {
        readyTimeout: 2000
    }
}`

**Comment by cmp-202** [comment]
I ran the standard test with that setting to a host that failed to respond and I am getting different timeouts depending on that setting.

**Comment by cmp-202** [comment]
I presume this is resolved

**Comment by coreyman** [comment]
Sorry for the delay in response. It appears  https://www.npmjs.com/package/ssh2 didn't work properly on my windows 10 box and that was my issue all along.

https://github.com/mscdex/ssh2/issues/672

**Comment by cmp-202** [comment]
Thanks for updating me on that. On 31/03/2018 7:13 AM, coreyman <notifications@github.com> wrote:Sorry for the delay in response. It appears  https://www.npmjs.com/package/ssh2 didn't work properly on my windows 10 box and that was my issue all along.
mscdex/ssh2#672
