### ISSUE TITLE
Timeout hung issue

### ISSUE THREAD

**Issue by Stieneee** [cmp-202/ssh2shell#52]
First off thanks for the package it's perfect for a little project I'm working on.

I am attempting to send a few command to a cygwin ssh server in a windows vm. The command I'm trying to run is `screen -r` to attach to screen process spawned in the windows user session. The command hangs for a moment before attaching to the screen. In the past this has worked successfully. I recently came back to use my program again and encountered the "Timeout after hung data event" response. Looking at the code it appears there is some timeout used to process data and that message is a result of a switch case. I bumped the timeout to several seconds and that resolved this issue.

I'm wondering if there is something I could do with the `ssh2shell.on ("commandTimeout"`
OR
Make and alteration to  the I would be happy to create a PR with a possible patch. I have a short list of ideas.
1. quick and dirty - expose this timeout time variable as configurable property and set it in the object properties.
2. wrap this switch in a retry strategy with an eventual timeout. On a default case loop again for x number of times before emitting commandTimeout.
3. A possible modification to the switch case?

Any further ideas? I am happy to do any additional debugging.

Looking forward to hearing back!

**Comment by cmp-202** [comment]
Hi,
Thanks for posting your issue. It is interesting the number of windows ssh issues popping up recently.

The 'hung data' you pointed to is just to determine if any further data has been received, buffer is loading or not.

Try adjusting your host.idleTimeOut value in your host object as this is the only timeout time that indicates command failure and impacts a session connection. 
If that timeout value is a problem for your other commands you can set the value in `host.onCommandProccessing` and reset it to normal in `host.onCommandComplete` based on detecting the 'screen' command. Use sshObj.idleTimeOut in those events.

**Comment by cmp-202** [comment]
Background info:
There are two timeouts: no longer receiving data and prompt detection.
The first is reset every time a data event is raised (buffer is loading) or times out indicating there is no further data events being raised which is when the switch cases are tested. This is where prompt detection is done or the command timeout timmer is started if that failed.
The command timeout is the time the process will wait after there has been no further data and no prompt was detected so the script doesn't hang.
If a data event is recevied within in the command timeout time both timeouts will be reset.

Switch cases:
The first couple are for handling commands requiring password management for tunneling or sudo.
The next two are for prompt detection after initial connection (no command) or after a command is run.
The last is when none of the above apply so there is nothing more that can be done. Reset the command timeout timer and wait because there is no more data to retry.

So: 
1. There should be no need to expose the data timeout value because changing the command timout value will do the same thing. Command timeout is the only timeout that will terminate the connection.
2. The switch is already 'wraped' in a retry in that it is event driven and will retry everytime there is a data event that triggers it again. If there isn't new data there is nothing to retry.
3. The switch case is likely to be doing what it is supposed to be doing considering the info above so no point is adjusting case tests.

**Comment by Stieneee** [comment]
Great response. I had tried changing host.idleTimeOut to one day and had my test case erroring in less then a second. That was what prompted me to look at the data timer. I probably should have mentioned that in my initial post. 

I kept digging and realized that I wasn't up-to-date. I see that since 1.8.6 you have committed some fixes to timeout related behavior. I updated to 1.9.0 which fixed my issue. Comparing the code I can see why 1.8.6 was behaving the way it was and how 1.9.0 fixes my issue.

Lowering host.idleTimeOut I can replicate the old behavior.

Strangest part in this was I never ran into the behavior before. I guess the windows box is just responding slower than it did several months ago.

Thanks for your help.

**Comment by Stieneee** [comment]
I did the adjustment and everything worked fine.

See [stackoverflow](https://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values) for a discussion on largest timeout values. Maxed out 2147483647 works out to be a little over 24 days.

I'm pretty confident that the instant timeout behavior I was seeing was the result of the behavior of the old default data timeout switch case. [this line](https://github.com/cmp-202/ssh2shell/blob/74c0b7404af6d0db04f61440073f68c7413d9467/lib/ssh2shell.js#L122) It looks like on a data timeout commandTimeout is triggered immediately. In your latest commit this line it replaced with setting the idle [for comparison.](https://github.com/cmp-202/ssh2shell/blob/3a44843694ec47a1be6ce4cbec78867a40632d99/lib/ssh2shell.js#L128)

I now believe what I was seeing was related to #48. In this scenario if the ping command took longer then 500ms data timeout would have triggered a commandTimeout printing a "Command timed out after ## seconds" were ## is the idleTimeout value.

Everything looks good to me in the current version.

Let me know if you want me to try anything else.

**Comment by cmp-202** [comment]
Yes I had read that.
Thanks for the extra work looking into that timeout value and confirming in your environment that those patches don't allow for that to happen under cygwin. 
I think that is done and done.
Cheers

**Comment by marcosturbonett** [comment]
I'm having timeout issues too.

##########################
192.168.8.254: Next primary host
192.168.8.254: initiate
192.168.8.254: Load Defaults
192.168.8.254: Host loaded
192.168.8.254: Connection.connect
Connected
192.168.8.254: Connection.ready
Ready
192.168.8.254: Connection.shell
Data processing: data received timeout
192.168.8.254: First prompt detected
192.168.8.254: Notifications: Normal Command to run
192.168.8.254: run command
Data processing: data received timeout
192.168.8.254: Class.commandTimeout
Class.error: 192.168.8.254: Command timed out after 100 seconds, Timeout
Timeout error: 192.168.8.254: Command timed out after 100 seconds
192.168.8.254: Stream.close
192.168.8.254: Stream.finish
192.168.8.254: Connection.close
Closed
192.168.8.254: ip address print

**Comment by marcosturbonett** [comment]
on another device the error is this.

10.200.100.246: Normal prompt detected
10.200.100.246: Raising commandComplete event
10.200.100.246: Class.commandComplete
10.200.100.246: Notifications: Normal Command to run
10.200.100.246: run command
10.200.100.246: Normal prompt detected
10.200.100.246: Raising commandComplete event
10.200.100.246: Class.commandComplete
10.200.100.246: No commands so exit
10.200.100.246: Process an exit
10.200.100.246: Exit command: Stream: close
10.200.100.246: Connection.error
Class.error: Error: Received oclose for nonexistent channel 0., Connection
Error: Received oclose for nonexistent channel 0., Level: undefined
10.200.100.246: Connection.error
Class.error: Error: read ECONNRESET, Connection
Error: read ECONNRESET, Level: client-socket
10.200.100.246: Connection.close
Closed

10.200.100.246: Stream.close

**Comment by cmp-202** [comment]
Those appear to me to be two unrelated errors from this issue or each other and need their own issues.

The first, although it is showing timeouts, looks to be using multiple (primary) hosts and is not the same timeout process as this issue. It is not receiving a data event within the timer before detecting each prompt including the first prompt where no command has been run. You could try increasing `host.dataIdleTime` but that's just a hack we still don't know why that host is triggering the data timeout. Multiple hosts are potentially a critical difference in this issue.

The second error is like  #97 but this was fixed so check your ssh2shell version.

**Comment by marcosturbonett** [comment]
"ssh2shell": "^2.0.6",

**Comment by marcosturbonett** [comment]
var SSH2Shell = require("ssh2shell")

var hostConfig = {
  commands: [
    "ip onu",
    "show online slot 14 pon 14"
    
    
  ],
  server: {
    host: '10.200.100.246',
    username: 'marcos',
    password: 'peacelove',
    port: 22,
    agent: process.env.SSH_AUTH_SOCK,
    compress: true,
    algorithms: {
        kex: [
          "diffie-hellman-group1-sha1",
          "ecdh-sha2-nistp256",
          "ecdh-sha2-nistp384",
          "ecdh-sha2-nistp521",
          "diffie-hellman-group-exchange-sha256",
          "diffie-hellman-group14-sha1"
        ],
        cipher: [
          "3des-cbc",
          "aes128-ctr",
          "aes192-ctr",
          "aes256-ctr",
          "aes128-gcm",
          "aes128-gcm@openssh.com",
          "aes256-gcm",
          "aes256-gcm@openssh.com"
        ],
        serverHostKey: [
          "ssh-rsa",
          "ecdsa-sha2-nistp256",
          "ecdsa-sha2-nistp384",
          "ecdsa-sha2-nistp521"
        ],
        hmac: [
          "hmac-sha2-256",
          "hmac-sha2-512",
          "hmac-sha1"
        ]
    }
  },

  showBanner:         false,
 
 
  idleTimeOut:         100000,  
 
   
  enter:              "\n",
  debug: true,
  
};


  SSH =  new SSH2Shell(hostConfig),
  
  SSH.onCommandTimeout = function( command, response, stream, connection ) {
   
    
    console.log(`COMANDO: ${command} resposta: ${response}`)
    
 }



    //Use a callback function to process the full session text
    callback = function (sessionText) {
      console.log(sessionText)
  }

SSH.connect(callback);

**Comment by marcosturbonett** [comment]
var SSH2Shell = require("ssh2shell")

var hostConfig = {
  commands: [
    "cd onu",
    "show online slot 14 pon 14"
    ],
  server: {
    host: '10.200.100.246',
    username: 'marcos',
    password: 'xxxxx',
    port: 22,
    agent: process.env.SSH_AUTH_SOCK,
    compress: true,
    algorithms: {
        kex: [
          "diffie-hellman-group1-sha1",
          "ecdh-sha2-nistp256",
          "ecdh-sha2-nistp384",
          "ecdh-sha2-nistp521",
          "diffie-hellman-group-exchange-sha256",
          "diffie-hellman-group14-sha1"
        ],
        cipher: [
          "3des-cbc",
          "aes128-ctr",
          "aes192-ctr",
          "aes256-ctr",
          "aes128-gcm",
          "aes128-gcm@openssh.com",
          "aes256-gcm",
          "aes256-gcm@openssh.com"
        ],
        serverHostKey: [
          "ssh-rsa",
          "ecdsa-sha2-nistp256",
          "ecdsa-sha2-nistp384",
          "ecdsa-sha2-nistp521"
        ],
        hmac: [
          "hmac-sha2-256",
          "hmac-sha2-512",
          "hmac-sha1"
        ]
    }
  },

  showBanner:         false,
 
 
  idleTimeOut:         100000,  
 
   
  enter:              "\n",
  debug: true,
  
};


  SSH =  new SSH2Shell(hostConfig),
  

    //Use a callback function to process the full session text
    callback = function (sessionText) {
      console.log(sessionText)
  }

SSH.connect(callback);

**Comment by cmp-202** [comment]
Thanks. Does this work?

```javascript
var SSH2Shell = require("ssh2shell")

var hostConfig = {
  commands: [
  "cd onu",
  "show online slot 14 pon 14"
  ],
  server: {
  host: '10.200.100.246',
  username: 'marcos',
  password: 'xxxxx'
  },
  debug: true,
  verbose: false
};

SSH = new SSH2Shell(hostConfig),

callback = function (sessionText) {
  console.log(sessionText)
}

SSH.connect(callback);

**Comment by marcosturbonett** [comment]
10.200.100.246: Next primary host
10.200.100.246: initiate
10.200.100.246: Load Defaults
10.200.100.246: Host loaded
10.200.100.246: Connection.connect
Connected
10.200.100.246: Connection.error
Class.error: Error: Handshake failed: no matching key exchange algorithm, Connection
Error: Handshake failed: no matching key exchange algorithm, Level: handshake
10.200.100.246: Connection.error
Class.error: Error: read ECONNRESET, Connection
Error: read ECONNRESET, Level: client-socket
10.200.100.246: Connection.close
Closed

**Comment by cmp-202** [comment]
okay add your algorithms back in

**Comment by marcosturbonett** [comment]
10.200.100.246: Next primary host
10.200.100.246: initiate
10.200.100.246: Load Defaults
10.200.100.246: Host loaded
10.200.100.246: Connection.connect
Connected
10.200.100.246: Connection.ready
Ready
10.200.100.246: Connection.shell
10.200.100.246: First prompt detected
10.200.100.246: Notifications: Normal Command to run
10.200.100.246: run command
10.200.100.246: Normal prompt detected
10.200.100.246: Raising commandComplete event
10.200.100.246: Class.commandComplete
10.200.100.246: Notifications: Normal Command to run
10.200.100.246: run command
Data processing: data received timeout
10.200.100.246: Class.commandTimeout
Class.error: 10.200.100.246: Command timed out after 100 seconds, Timeout
Timeout error: 10.200.100.246: Command timed out after 100 seconds
10.200.100.246: Connection.error
Class.error: Error: Received oclose for nonexistent channel 0., Connection
Error: Received oclose for nonexistent channel 0., Level: undefined
10.200.100.246: Connection.error
Class.error: Error: read ECONNRESET, Connection
Error: read ECONNRESET, Level: client-socket
10.200.100.246: Connection.close
Closed

10.200.100.246: Stream.close

**Comment by cmp-202** [comment]
Can you turn on verbose

**Comment by marcosturbonett** [comment]
I think he is waiting for a command....
 
 --Press any key to continue Ctrl+c to stop--

**Comment by cmp-202** [comment]
yes look at:
[non-standard command prompts](https://github.com/cmp-202/ssh2shell#responding-to-non-standard-command-prompts-)

**Comment by marcosturbonett** [comment]
eu preciso somente desta informação:

ONLINE ONU TOTAL NUM = 83

**Comment by cmp-202** [comment]
Also check [ssh2 client connection options](https://github.com/mscdex/ssh2#client-methods)

**Comment by cmp-202** [comment]
Okay.
In `onCommandProcessing` you can detect the command and that line and then set response to just the content you want.
Then call `stream.write '\x03'` to cancel the further command output.

**Comment by marcosturbonett** [comment]
First, I would like to thank you for your attention!


how do i save the output in a variable?

Thank you so much

**Comment by cmp-202** [comment]
You could add a variable to `sshObj` which you set in onCommandProccesing and process it in `onEnd(sessionText, ssh2Obj){}`.

It's event-driven so you can't know when ssh2shell has set a variable outside the scope of the ssh2shell events. You can pipe to your own write stream or add your own onData event but these only receive raw output from the host.

**Comment by marcosturbonett** [comment]
I can not enter the command and not capture the return! I don't think I can understand how it works...
🥲🥲🥲🥲🥲

**Comment by marcosturbonett** [comment]
I just need to access this device and perform two commands.
command 1 (enter the directory):
cd onu

command 2:
show onu auth-and-online statistics level slot

and save the output to a variable.

as the image below 
🥹🥹🥹

<img width="582" alt="image" src="https://user-images.githubusercontent.com/45607452/194711601-cf36f4d8-ffd9-43d3-bacd-c214b40add1c.png">
