### ISSUE TITLE
I use the vue framework to reference this package. Why Cannot find module "ssh2"?

### ISSUE THREAD

**Issue by navysummer** [cmp-202/ssh2shell#53]
The development environment is vue+vuex+webpack
js code：
`import SSH2Shell from 'ssh2shell';
var host = {
    server: {
        host: '127.0.0.1',
        userName: 'navy',
        password: '990722',
    },
    commands: ['ls -l']
};
    var SSH = new SSH2Shell(host),
    callback = function(sessionText) {
        console.log(sessionText)
    }
SSH.connect(callback);`

**Comment by cmp-202** [comment]
English please.

[Basic Example in ReadMe](https://github.com/cmp-202/ssh2shell#minimal-example)

```
var SSH2Shell = require ('ssh2shell');
```

**Comment by cmp-202** [comment]
"Can't find ssh2"
ssh2 is included using `this.connection = new require('ssh2')();` which might be the problem if the two import systems can't be used together. I couldn't easily find anything to confirm that.
Try the method in the example to confirm it works and I might try to change the ssh2 require to import and check it doesn't break anything.

**Comment by cmp-202** [comment]
No that isn't going to work I would have to accomodate ES6 instead of commondJS for one use case.
All I can suggest is use require just for ssh2shell so the same import type is in play when ssh2 is included using require.

**Comment by cmp-202** [comment]
I presume this is resolved
