### ISSUE TITLE
Leave connection opened

### ISSUE THREAD

**Issue by Josepdal** [cmp-202/ssh2shell#55]
Hello, is there any way to leave the connection opened so I don't need to reconnect everytime I want to send a command?

I saw #8 but it's a different case. I just want to connect once and then send multiple commands without setting a new connection. Is it possible?

Best regards, Josep.

**Comment by Josepdal** [comment]
> Yes once the array of commands is completed the connection is closed. SSH2shell does not maintain a persistant connection.
> 
> When you create the ssh2shell instance and call the connect function the new connection is made and the commands are run then it disconnects on completion.
> 
> Currently running connect again doesn't reset the instance data from the previous process so it would be recommended to repeat calling the constructor to initiate a new instance. I might change that but there has never been a request for it.
> 
> It is possible to add or remove commands using the host.onCommandComplete event handler based on a spacific command response content while the command processing is running.

Would be so difficult to implement a persistant connection?

**Comment by cmp-202** [comment]
Hi Josep,
Do you mean a never closing connection?
Can you give an example of how you wanted to use it so I can understand what you need.

FYI
Ssh2shell doesn't connect for every command it runs them all in a shell session and then closes it.

Andrew

**Comment by Josepdal** [comment]
I am developing an app that sends and gets info from a ssh server. I have a bunch of buttons so everytime I click one of them it connects to the server, sends the commands and get some info back. It takes higher time that I expected while doing all those tasks. One thing I was interested on doing is make what you said, a never closing connection so I can just send commands and get info without connecting and disconnecting everytime from the server.

**Comment by cmp-202** [comment]
Hi Josep,
I am not going to do this under the current project, it is already bloated.
Instead I am starting a new project called [persistent-shell](https://github.com/cmp-202/persistent-shell) which will have most of the functionality of ssh2shell removed but hopefully persistent.
As a result I will close this issue and get you to move to that repo.

Please note althought I have done a lot of the code removeal I have not tested it in any way so I would not consider it worth trying at this point. I am continuing to work on it over the next few days so hopefully I will have something for you soon.

Andrew

Andrew
