### ISSUE TITLE
Extraneous console logging

### ISSUE THREAD

**Issue by ExcelNet-Public** [cmp-202/ssh2shell#58]
Please remove the line 459 code which I suspect was there for debugging at some point:

 console.log(host)

This ends up sending a lot of information to the console when you make 1000's of connections that really does not need to be logged.  Thanks!

**Comment by cmp-202** [comment]
Yes this has been raised in issue #57.

**Comment by cmp-202** [comment]
See #57 for published fix info. If you are happy with the result feel free to close this issue.

**Comment by ExcelNet-Public** [comment]
Excellent, that cleared it up.  Thanks for the quick response.  Now onto getting this to work with Powershell command prompts...  They are always timing out though I know the SSH connection is establishing and manually can send commands just fine.
