### ISSUE TITLE
Powershell processing

### ISSUE THREAD

**Issue by ExcelNet-Public** [cmp-202/ssh2shell#60]
We have implemented the Microsoft solution for accessing PowerShell over SSH.  We are then trying to use this package to allow us to script the commands we need to run and parse the results.  What seems to be getting in the way is the data being returned has the xterm escape sequences in them.  So we get something like:
`Connected to windows.mydomain.com\n[2J[1;1HWindows PowerShell                                                              \n[2;1HCopyright (C) 2014 Microsoft Corporation. All rights reserved.                  [4;1H\n\n[4;1HC:\\Users\\root>                                                                  [4;15H[4;15H`

Have finally been able to "trick" the command prompt detection by using the following setting:

`standardPrompt: '>$%#]|(\\[\d+:\d+H)'`

VERY KLUDGY yes, works though.  The ouptut though just continues to be cluttered with these escape codes making it very difficult to parse the response.

This may not really even be powershell related, just how do we get this to accept the xterm terminal type and strip all of the escape sequences.  Thanks in advance for any ideas people can suggest.

**Comment by cmp-202** [comment]
Hi,
I it is the formatting codes which probably is some varience from linux based formatting.

`host.textColorFilter = "(\[{1}[0-9;]+m{1})"` is the default so try searching for the powershell formatting codes and modify host.textColorFilter to match.

**Comment by ExcelNet-Public** [comment]
That gave me a start, thanks! I have them stripped and now can see another strange thing going on, it appears to be echoing back the command input MANY times.  For example if I send powershell the command 'dir' (yes not a true powershell command) my output will get returned:
ir 
r
Like it accepted the 'd' and returned the rest, then accepted the 'i' and returned the rest,...  This is really noticable on long powershell commands.  I realize this is probably not the ideal forum for discussing this, the issue is I am not sure exactly where to go.  Does not seem many people accessing powershell over SSH and then scripting it in Javascript.  

Thanks again!

**Comment by cmp-202** [comment]
Hi,
Thats alright these are the sort of issues that can be a challenge to work out so am happy to help if I can.

- The first thing I would need to confirm is the standard prompt pattern back to default setting or to a pattern that matches the windows ssh prompts. The modified prompt pattern could cause multiple command complete events that you don't want and potentually this type of output. 

- I don't think it is the host responding to each command charactor, it is the data received processing which is why the standard prompt detection nees to be correct.

- Commands are filtered out from the returned text by default so it isn't that unless the data it is chopped up before it gets that far causing it to not see a full command. That doesn't explain the output though.
 
- Could you run it with debug turned on only then verbose only (set in host object) and upload the output here (maybe text file) with any sensitive info removed. Keep it to one or more commands that shows the issue but not heaps of content to wade through. 
   
Thanks,

Andrew

**Comment by ExcelNet-Public** [comment]
Andrew:

Thanks for the assistance!  I believe you are on the right track with the command prompt interfering, however without the modified detection string a command prompt is never detected and no command is ever run.

I have attached running the command 'get-childitem' with standardPrompt at defaults and the modified so detection occurs with debug in one and verbose in another.   My thoughts are that we need to leave the standardPrompt alone but that the RegEx that detects white space after the prompt characters also detects the control secquences or they are stripped before that point.  This would be the @standardPromt (not sure if intentionally misspelled or not).  I may try passing something in there to see what I can find.

Thanks again!

[sshPowershellDebug.txt](https://github.com/cmp-202/ssh2shell/files/2460847/sshPowershellDebug.txt)

**Comment by cmp-202** [comment]
Hi,
From your verbose:
```javascript
//found command to run
server.mydomain.com: Next command from host.commands: get-childitem

//removed from the commands and ran
server.mydomain.com: running: get-childitem

//data received event with the text formatting fliter failing to match anything
server.mydomain.com: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false

//Non-standard ascii filter matched and removed
server.mydomain.com: ASCII filter: [^ -~], response is ok: true

//Standard prompt detected and so command has completed
server.mydomain.com: Command complete:
Command: get-childitem
Response: [4;15H ...... //all the rest of command output showing the command actually worked
```

This is not a ssh2shell bug it is the MS OpenSSH implementation differening from SSH. 
At this point it is only the host config that should be the focus not the core code.

What the breakdown above means: prompt **is** detected, command **is run** and completed, ascii filter is matched and removed, **text formatting failed** to match and was not removed.

Based on the verbose the text formatting filter looks like it needs to be changed `host.textColorFilter = "(\[{1}[0-9;]+H{1})"`, either way this needs to be changed until it is correct. 
Maksure you haven't turned any of the filtering off not because it will stop it from working but because you will get the extra you don't want

The standard prompt is `>` so the default `.standardPrompt  = ">$%#"` should be left at default because it is working. 

Sorry for spelling mistakes I am dyslexic so I try to fix the mistakes but I don't always get everything.

**Comment by ExcelNet-Public** [comment]
The prompt is ONLY being detected in the verbose / debug version because we have set:

'standardPrompt: '>$%#]|(\\[\d+:\d+H)'

Otherwise we get the results of the first example where it never detects the prompt.  The problem I believe it that my code to detect a prompt detects more than that because the pattern is seen more frequently than that.  I will work on getting a better regex or I believe a second solution would be to create an inputFilter property that PRE filters the text coming from the SSH connection prior to any processing.  I would have it "clean" the data field before it is appended to the buffer.  I may fork and try adding that if I cannot get it to work with the prompt stuff.

Do appreciate the help!

**Comment by cmp-202** [comment]
I need a copy of failing host through to connection code minus sensitive info.  I presume change you made to standard prompt is the only difference.
I will need to do a setup of Windows 10 OpenSSH to test it.

**Comment by ExcelNet-Public** [comment]
Attached is the debug / verbose output running the same command as the first time but with standardPrompt set at the default value.  It still seems the issue is that you are looking for a prompt character, white space and end of line to detect the prompt.  Unfortunately powershell seems to be giving us prompt character, white space, control string and then end of line.  


[sshPowershellDebug-StandrdPrompt.txt](https://github.com/cmp-202/ssh2shell/files/2473167/sshPowershellDebug-StandrdPrompt.txt)

**Comment by ExcelNet-Public** [comment]
OK kept playing and making some progress here.  I have modified settings as follows:

```
standardPrompt: '>$%#]|(>\\s?\\[\\d+;\\d+H$)'
textColorFilter: '(\[{1}[0-9;]+m{1})|(\\[\\d+;\\d+H)'
```
This results in the commands being processed and the result being ALMOST ok.  The only issue left is that it still seems to echo the command back, stripping a single character at at time.  I have to believe this is a Windows OpenSSH implementation issue.  I am going to start looking at other SSH servers as I cannot get hung up here too much longer.  The result using the settings above provides:

`
Connected to server.mydomain.com\n                                                     et-childitem                                                     t-childitem                                                     -childitem                                                     childitem                                                     hilditem                                                     ilditem                                                     lditem                                                     ditem                                                     item                                                     tem                                                     em                                                     m                                                     \n\n\n    Directory: C:\\Users\\root                                                    \n\n\nMode                LastWriteTime     Length Name                               \n----                -------------     ------ ----                               \nd----         2/29/2016  12:34 PM            .oracle_jre_usage                  \nd----         9/28/2018  10:27 AM            .ssh                               \nd-r--         9/27/2018   9:55 AM            Contacts                           \nd-r--         9/27/2018   9:55 AM            Desktop                            \nd-r--         10/4/2018  11:26 AM            Documents                          \nd-r--         10/5/2018  10:43 AM            Downloads                          \nd-r--         9/27/2018   9:55 AM            Favorites                          \nd-r--         9/27/2018   9:55 AM            Links                              \nd-r--         9/27/2018   9:55 AM            Music                              \nd-r--        11/20/2015  12:29 PM            OneDrive                           \nd-r--         9/27/2018   9:55 AM            Pictures                           \nd-r--         9/27/2018   9:55 AM            Saved Games                        \nd-r--         9/27/2018   9:55 AM            Searches                           \nd-r--         9/27/2018   9:55 AM            Videos                             \n-a---        10/12/2018   1:56 AM     290643 certenroll.log                     \n-a---         9/28/2018  11:04 AM     196736 melist.txt                         \n-a---         10/2/2018  12:17 PM     196736 MEPowershell.txt                   \n\n\nC:\\Users\\root>                                                                  
`

Almost have it, though the whole thing seems pretty kludgy.  Thanks for all the help!

**Comment by ExcelNet-Public** [comment]
Tested using Bitvise SSH server and everything worked fine after changing the enter = '\r\n'.  Did use the textColorFilter from above as well to cleanup the output but other than that getting expected results.

**Comment by cmp-202** [comment]
[Have a read of this issue](https://github.com/cmp-202/ssh2shell/issues/49#issuecomment-372155267)

**Comment by cmp-202** [comment]
I should put a note in the readme to not use Windows ssh and to use OpenSSH instead or whatever thirdparty ssh server works as normal SSH shell does on windows.
Sorry I completely forgot about that issue it wasn't untill you said about changing the software that the lights came on and I thought "this sounds familiar".

**Comment by cmp-202** [comment]
I presume this is closed.
