### ISSUE TITLE
Override default standardPromt

### ISSUE THREAD

**Issue by eozer** [cmp-202/ssh2shell#61]
Hi,

I need to override "this.standardPromt" as the terminal prompt has different format at the end. So the regex ("[" + this.sshObj.standardPrompt + "]\\s?$") can be extended. In my case I had to change the regex to regex ("[" + this.sshObj.standardPrompt + "]\\s?**..**$") (two dots at the end).

Related line:
https://github.com/cmp-202/ssh2shell/blob/fc62b12149d17195d278f53f82e7d4e2fee944b6/lib/ssh2shell.js#L588

Is there any way to override the default "this.standardPromt" than changing the file? Maybe somehow I missed it from the documentation? If not, perhaps this can be an improvement, like add "this.standardPromt" to the property of the host object so it can be overridden. As I have already checked the other issues somehow related to this.

**Comment by cmp-202** [comment]
https://github.com/cmp-202/ssh2shell#host-configuration.

Host = {
//Optional: Characters used in prompt detection
  standardPrompt:     ">$%#",
  passwordPrompt:     ":",
  passphrasePrompt:   ":"
}

**Comment by eozer** [comment]
I think host.standardPrompt is equivalent to this.sshObj.StandardPrompt. What I need is to override "this.standardPromt" (the internal one).

**Comment by eozer** [comment]
That worked fine. I guess coffeescript confused me. Thanks for help :)
