### ISSUE TITLE
Timeout triggerred on exit commands

### ISSUE THREAD

**Issue by eozer** [cmp-202/ssh2shell#62]
Hi,

I need to clean up gracefully the SSH connection by running additional commands at the end (like 'exit'), otherwise I can see from the remote host that port is still in **TIME_WAIT** state. So, I pushed the required command to sshObj's exitCommands property before running ssh.connect() like below:

https://github.com/cmp-202/ssh2shell/blob/fc62b12149d17195d278f53f82e7d4e2fee944b6/lib/ssh2shell.js#L260

The problem is that after the exit command run and the stream closed, onCommandTimeout is still triggered. I can workaround the problem by ignoring some specific commands, but is there any other way to solve the issue? After running the exit command/stream closed one should not care whether it is timed-out.

Output
---------------------------------------------------------------------------------------
```
  (some data events)
  ........
  testproject 127.0.0.1: No commands so exit +0ms
  testproject 127.0.0.1: Run exit +1ms
  testproject 127.0.0.1: Queued exit commands: ABCD; +1ms
  testproject 127.0.0.1: running: ABCD; +0ms
  testproject 127.0.0.1: data event +3ms
  testproject 127.0.0.1: Command waiting +1ms
  testproject 127.0.0.1: data event +1ms
  testproject 127.0.0.1: Command waiting +0ms
  testproject 127.0.0.1: Connection.close +214ms
  testproject Closed +1ms
  testproject 127.0.0.1: Stream.finish +1ms
  testproject 127.0.0.1: Stream.close +0ms
    √ Should return okay (1958ms)


  1 passing (2s)
  8 pending

  testproject 127.0.0.1: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false +286ms
  testproject 127.0.0.1: ASCII filter: [^
  testproject  -~], response is ok: true +2ms
  testproject Data processing: data received timeout +3ms
  testproject Command "ABCD;" timeouted +5s
  testproject 127.0.0.1: Class.error +2ms
  testproject Error: 127.0.0.1: ABCD; timed out after 5 seconds, Level: client-cmdtimeout +4ms

```
-------------------------------------------------------------------------------------------------------

**Comment by cmp-202** [comment]
So the timeout is probbably triggered because data processing handles a command 'exit' differently than normal commands (no timeout). You are pushing the 'abcd' command to the exit commands array which probably is beening treated as a commend not an  'exit'.In that case the timer to detect no further data events for prompt detctect is added which then triggers the command timeout.I am confused by the port time_wait in the context that ssh2 should handle closing the shell session and tcp connections (port) not ssh2shell.Does ssh2 have any issues on that, just in case.The other option is to add a timeout handler that detects your terminating command and does nothing rather than timing out. Not sure off the top of my head how a stream.write('abcd\n') would be handled. I suspect it would be handled as a command (timeout timer added on data event). The uncertinty is the test if command = '' which is the initial banner handling before a command is run.

**Comment by cmp-202** [comment]
The exit commands array is not for closing the ssh2shell connection! (normally) It is used for closing ssh sessions created on the host to hop to another hosts using ssh command. 
A normal connection is closed using stream.close() from the app host. 
One suggestion was to change which side is closing the connection so its the other host getting the time_wait.
So you could try making the host close the connection by running an exit command.

**Comment by eozer** [comment]
By the way, "ABCD;" is the literally the exit command for some VAX computer. About **TIME_WAIT** state, I think I confused you a little bit, because the kernel actually cleaning the port after some time passed. So there is not any port open left, they are open for **a certain time.** But I think the session should be closed gracefully anyways.

For the suggestions
- I couldn't find any related issue in ssh2 repo
- I have some solution already for handling timeout errors for a given commands. But in my case handling the "error" was not the issue. The issue was just to not trigger any onCommandTimeout after the stream finishes.
- I added an OR statement for "ABCD;" similarly like below, so that it can call _this._runExit(); immediately.  But of course then the output was same as it is still writing to the stream and there is still a stream data listener event.
https://github.com/cmp-202/ssh2shell/blob/fc62b12149d17195d278f53f82e7d4e2fee944b6/lib/ssh2shell.js#L272

Actually the last suggestion then gave me an idea about removing stream's data event listener when the stream finishes.

https://github.com/cmp-202/ssh2shell/blob/fc62b12149d17195d278f53f82e7d4e2fee944b6/lib/ssh2shell.js#L817

But, I am not sure whether if it would work or not. I will give it a try, but what do you think about this?

**Comment by eozer** [comment]
Actually I just remove all listeners on close method like below. onCommandTimeout did not get trigger (that is a good sign imo), but now there is a small delay to exit from the execution, which I believe there is still some command timeout waiting.
```js
            return _this._stream.on("close", function(code, signal) {
              if (_this.sshObj.debug) {
                _this.emit('msg', _this.sshObj.server.host + ": Stream.close");
              }
              _this.removeAllListeners();
              _this.connection.end();
              return _this.connection.removeAllListeners();
            });
```

I don't know where should I check to remove timers now, I will dig more.

**Comment by eozer** [comment]
I think this does what I need.
```
            return _this._stream.on("close", function(code, signal) {
              if (_this.sshObj.debug) {
                _this.emit('msg', _this.sshObj.server.host + ": Stream.close");
              }
              if (_this.sshObj.dataReceivedTimer) {
                clearTimeout(_this.sshObj.dataReceivedTimer);
              }
              _this.removeAllListeners();
              _this.connection.end();
              return _this.connection.removeAllListeners();
            });
```

But now the question is do you think this should be implemented in the next version?

**Comment by cmp-202** [comment]
Sorry I have been flat out today (2am now) and I am tied up for a couple of days. If I find a gap I will look over it.

**Comment by eozer** [comment]
No worries! I sent a PR #63 please review it. I ran the whole tests folder I think they are working as expected. But still I found it a little bit hard to understand the tests, I think it would be much better if somehow it could be implemented using some test framework.

**Comment by eozer** [comment]
Yes I can exit from the system by putting “ABCD;” at the end of the commands. But again, without clearing timers and listeners when the sesssion closes onCommandTimeout is still triggering.

**Comment by cmp-202** [comment]
I think you  should try my other package [persistent-shell](https://github.com/cmp-202/persistent-shell)
It leaves a lot more up to you like no timeout handlers. I think this would give you much more control without the extra functionality in ssh2shell.

**Comment by cmp-202** [comment]
I have looked at the code and I am reluctant to make those changes.
I do not believe the listeners need to be removed to "clean" everything up. I don't think you will find that in closing stream examples, happy to be proved wrong if you can provide documentation to back it up. It isn't an issue for normal use of the package which closes the stream not by running and exit command.

You are clearing the dataReceivedTimer timer which should stop the command timeout being set if you get to it before the 500ms for that timer finished. I would have to do both just in case it had been started. The timeout timer is cleared in the connection.close() to stop that running after that point.

One use case that doesn't fit within the normal package opporation is difficult to justify a code change when it works for everyone else. I will have a look now to see what I can do but I strongly recomment you look to use persistent-shell for the level of control you are needing. 
persistent-shell has that ability and it is structured very similar to ssh2shell the main difference is you have to close the session (by command or closing the stream) which is what you want.

**Comment by cmp-202** [comment]
something like this might work:

```javascript
host.onCommandProcessing=function( command, response, sshObj, stream ){
    //look for your command and the timeout set
    if(command.indexOf("ABCD") != -1 && sshObj.idleTimer) {
            clearTimeout(sshObj.idleTimer);
            //you can remove the timeout handler as well or even replace it.
            this.removeListener 'commandTimeout',  this.onCommandTimeout
      }
}  
```

**Comment by cmp-202** [comment]
Difficulty is fighting the core functionality out of synk with the events that add the timers.

It seems from your detail that by removing the listener for the timeout the timeout no longer happens regardless of the timer still getting activated.
Every data event will trigger the dataReceivedTimer which will in turn add the timeout timer again once it times out (no prompt detected).
CommandProcessing is not catching the last data event in a way it can reset those timers.

Now I have some time I will setup a test using 'exit' to close the session and see if I can get it working.
Use your branch for now and I will let you know how I get on.

**Comment by codexnovus** [comment]
I am experiencing a similar problem, but with the normal exit command. 

For some reason, my connections never disconnect gracefully (I never get the closedMessage, at least not without a timeout error). My guess is that because I have set up a VPN connection before the script starts and when the script ends I close it, the SSH connection doesn't have time to exit gracefully. And that happens because the "end" event is triggered because the SSH connection is really disconnected.

In my case removing the listener as per eozer's proposed PR is worse, because then the error is not handled properly and instead of reporting an error, the node app crashes. 

What I need is a way to force the SSH object disconnect on End, before I spawn the "vpnc-disconnect" command.

(I just wanted to chime in because I wanted to add a case where a heavy-handed approach like the one eozer proposes can be detrimental).

**Comment by cmp-202** [comment]
I am closing this after all this time. This issue has now been fixed in the latest version in the repo.
