### ISSUE TITLE
The normal exit command not closing cleanly with VPN.

### ISSUE THREAD

**Issue by cmp-202** [cmp-202/ssh2shell#64]
For some reason, my connections never disconnect gracefully (I never get the closedMessage, at least not without a timeout error). My guess is that because I have set up a VPN connection before the script starts and when the script ends I close it, the SSH connection doesn't have time to exit gracefully. And that happens because the "end" event is triggered because the SSH connection is really disconnected.

In my case removing the listener as per eozer's proposed PR is worse, because then the error is not handled properly and instead of reporting an error, the node app crashes. 

What I need is a way to force the SSH object disconnect on End, before I spawn the "vpnc-disconnect" command.

(I just wanted to chime in because I wanted to add a case where a heavy-handed approach like the one eozer proposes can be detrimental).

_Originally posted by @codexnovus in https://github.com/cmp-202/ssh2shell/issues/62#issuecomment-441262266_

**Comment by cmp-202** [comment]
Have you tried closing the vpn from say a callback function. That way the action of closing the VPN is dictated by a connection.close() related events. Utilise those events, the shell will be closed before the vpn closes.

**Comment by cmp-202** [comment]
@codexnovus try adding a listener to host.onEnd( sessionText, sshObj ). This triggers on stream.finish().
That is the lastest event we have access to, the step before the stream.close() event.

**Comment by codexnovus** [comment]
@cmp-202 I'm working on a series of test to further diagnose the problem. I was wary of opening an issue because I haven't finished discarding non-ssh2shell factors. I will add your suggestions to the test list and ping back when is done.

**Comment by codexnovus** [comment]
@cmp-202 ok I need to implement in the real life app but I managed to isolate the issue on tests already.

On the test, if I put the VPN disconnection call inside the onEnd, the stream doesn't close (I never get the closedMessage). When I move the VPN disconnection call to the callback the stream seems to close properly.

On the app, the SSH is encapsulated within a promise. I made the promise resolve itself on the "onEnd" event. The VPN disconnection is called just after the resolution. I will move the promise resolution/rejection to the callback, and that will probably will fix the error.

I am wondering, though... can I return the callback in the middle of a command chain to abort it?
The reason being that one of the things we check during the ssh2shell command is a svn username/password. if the check fails we abort the rest of the commands. I fear that we still will have an unclean close otherwise.

**Comment by cmp-202** [comment]
So you detect the password promt in commandProcessing and if you needto bail empty the commands array then send your response to the prompt. No more commands triggers disconnection.

**Comment by codexnovus** [comment]
I'll try that. It's mildly inconvenient because I am setting return points from many events but on the other hand that means I'm just not using it as intended and because of this, have not much reason to complain :)

**Comment by codexnovus** [comment]
Still, and that is not a bug but a feature suggestion, I would like to know if there's a way to tell ssh2 that something went wrong and that the stream needs to be closed. I have everything encapsulated inside promises and as such, it tends to fail "gracefully" (aka, not closing the app), and it would be nice to be able to manually close the stream if for some reason is still open while reaching the catch()

**Comment by cmp-202** [comment]
Try calling _runExit() on the instance, must be connected first. Big issue is you don't know the actual state of the session or connection as it may have actually closed before you call _runExit().  I wonder if you could use a commandProcessing handler to notify that the process is still running, like a tick. So you could run that runExit() command (hopefully) and disconnect if its ticking or let it close if it isn't. No tick means process is finished or maybe a timeout so closing.

**Comment by codexnovus** [comment]
I moved my return call from the onEnd event to the callback event but seems that still the listener refuses to close.

Here's a "sanitized" excerpt of the code that calls the ssh2shell object:
`new Promise that connects to VPN, returns jobObject or rejects with error
.then (jobObject) {
    new Promise( (resolve, reject) => {
        let sshOnCommandComplete = function (command, response, sshObj) {
                // we remove the executed command and the prompt from the response
            response = response.split('\n');
            response.shift(); response.pop();
            // we save the last response. it should be filtered by command once stable
            sshObj.lastCommandResponse = response.join('\n');
        }
        let sshOnError = function (err, type) {
            // we attach the error and the job Object for the rejection on callback
            this.sshObj.sshError = {reason: err, jobObject};
            // we empty the commands to trigger the disconnection
            this.sshObj.commands = [];
        }
        let sshOnCallback = function (_sessionText) {
            // on error, we reject with the data collected
            if (this.sshObj.sshError) { return reject(this.sshObj.sshError; }
            // on success, we resolve with the data collected
            return resolve({reason: this.sshObj.lastCommandResponse, jobObject});
        }
        let sshOptions = {
            server : { <here would go the server data. I use host, port, userName and password > },
            commands: [
                'sudo su - otheruser', // we connect as one user but need to execute the commands as another
                'cd <particular folder>',
                '<command that returns a csv after between 30 and 90 seconds>'
            ],
            idleTimeout: 90000,
            connectedMessage: 'Connected to ${server.hostname}',
            closedMessage: 'SSH connection to ${server.hostname} closed',
            onCommandComplete: sshOnCommandComplete,
            onError: sshOnError,
            callback: sshOnCallback,
            opeError: null,
            lastCommandResponse: null
        };
        let sshCheck = new ssh2shell(sshOptions):
        sshCheck.connect();
    }
.then (send report, disconnect VPN);
.catch (handle error, disconnect VPN);
`

I've omitted the logging that let's me keep track of the status of the app but I guess that won't cause the EINVAL 😄 

Here's a common log output of what happens (again, a bit sanitized)
`
[info]: QUEUESRV > Job request queued with ID: 5bfc22ddb7de466ce581ad36
[fluff]: OPEMODEL > Received check request with the following data <job data>
[info]: OPEMODEL > Called a SSH based check for project <project name>
[debug]: OPEMODEL > Connecting to VPN <VPN name>
[info]: IO> Sending status update to client with <job request accepted, connecting to vpn>
[debug]: VPNODEC > STDOUT: VPNC started in background (pid: 27978)...
[info]: VPNODEC > VPNC Started successfully. PID: 27978. Saved PID to <VPN name> for disconnection
[info]: IO > Sending status update to client with <connected to vpn, executing check>
[debug]: SSH > Connected to <host IP>
[debug]: SSH > Ready
[debug]: OPEMODEL > <host IP>: The following command was completed: sudo su - otheruser
[debug]: OPEMODEL > <hostIP>: The response was: <welcome message>
[debug]: OPEMODEL > <hostIP>: The following command was completed: cd <particular folder>
[debug]: OPEMODEL > <hostIP>: The response was: <none, of course>
[debug]: OPEMODEL > <hostIP>: The following command was completed: <command that returns a csv>
[debug]: OPEMODEL > <hostIP>: The response was: <a CSV>
[info]: IO > Sending status update to client with <check completed>
[fluff]: OPEMODEL > SSH Session finished: <sessionLog>
[fluff]: QUEUESRV > Completed queued item with ID 5bfc22ddb7de466ce581ad36
[info]: QUEUESRV > Queue for server <VPN name> is empty. Disconnecting VPN.
[debug]: VPNODEC > Killing process with ID 27978
[info]: VPNODEC > VPNC process terminated successfully
<several minutes later>
[error]: OPEMODEL > Check error. Type: Connection ; Error: Error: read EINVAL
[debug]: SSH > SSH connection to <hostIP> closed
`

**Comment by codexnovus** [comment]
I ran additional tests, now with the sshObj.debug enabled and I found that on the production app, I get the `Stream.close` event before resolving, but not the `Connection.close` one.

**Comment by codexnovus** [comment]
I successfully avoided the problem by latching on the connection.on('close') event instead of relying on the callback. Seems that, for some reason, the remote server takes a bit too long to close the connection (this didn't happen on local network tests) and while the stream closed, the connection took a bit more. Disconnecting the VPN before giving the connection a chance to disconnect was causing the timeout.

I would suggest triggering the callback on connection.close() instead of relying on stream.finish(), as it seems this is really when the "call" really ends 😄

**Comment by cmp-202** [comment]
I am closing this one lol. I have implemented the connection.close callback in the first block of work I have done on this since way to long ago along with a rewrite of the multi host connection management. [Multi host test is a good one to see what it can do now if your interested](https://github.com/cmp-202/ssh2shell/blob/master/test/Multiple%20primary%20hosts.js).
