### ISSUE TITLE
SSH2Shell does not connect properly to next host when tunnelling

### ISSUE THREAD

**Issue by codexnovus** [cmp-202/ssh2shell#65]
Hello! I'm writing a ssh through ssh connection and for some reason, the ssh2shell object executes what I found on the code a "connection check" (ssh -q user@server "echo 2>&1" && echo "OK" || echo "NOK") but after that it doesn't tries to connect. Instead, it assumes it has connected and proceeds to execute the commands. 

Removing the "echo 2>&1" line from the library seems to fix the problem, as long as I put a command that ssh2shell expect to have a password prompt (like "sudo") but I understand this workaround is a bit of a hack.

While studying the code, it seems that it does a connection check, and my guess it was the intention of making a good connection after. Instead, it declares it connected.

So my problem here is twofold: on one side, it doesn't seem to be detecting the password prompt. On the other side, it doesn't seem to be really connecting.

I can provide an example code and/or logs if necessary.

**Comment by cmp-202** [comment]
Hi,
Sorry for the delay I am not getting to these issues very well recently.
I will need to set up the multi host test platform to recheck this.
My test has a big hole in it, I am not testing for "OK" I am testing for not "NOK" and so if the response was "OK" or anything not "NOK" it will presume it can connect which is wrong.

try:
```javascript
//line 370
if (response.indexOf("OK") >= 0) {
```

Here is the desired logic:
SSH loads the next ssh host config and testConnection is set to true to do the ssh connection test. 
The output from the ssh test command is then checked for `NOK` or "OK" as per the ssh command you identified.
`ssh -q #{@sshObj.server.userName}@#{@sshObj.server.host} \"echo 2>&1\" && echo OK || echo NOK`

If its "OK" then it constructs the actual SSH command using available flags and host parameters provided by the new host config and sets the testConnection to false so further prompt detection is not looked as a connection test.
If it is not "OK" then connection is abandoned and the previous host config is reloaded. Any further hosts in the primary hosts array are then attempted. 
If testConnection is set to false it is presumed the SSH connection to the new host has completed and its commands can be run. 

Viewing the debug output should show `SSH: Okay` to connect` for "OK" and `SSH: Connection not possible reverting host` for "NOK".
If you view verbose you should see `SSH: Connection test response: #{response}` to see what came back from the connection test.

**Comment by cmp-202** [comment]
I ran the tunneling test with 2 hosts (Ubuntu) and the connection completed and ran commands.

Path to test: ssh2shell/test/tunneltest.js

**Comment by cmp-202** [comment]
I have been doing some failure tests and am finding it is not moving back through the hosts that were in the hop path to get to the disconnecting host.
Connection test logic definitely needs work to get that handling potential failure cases better. 
That's pretty fundamental.
I am part way through that and I will try and do some more over the next couple of days.

**Comment by codexnovus** [comment]
I think that in my case failed because it asked for username/password and it interpreted it as OK. I can provide logs if necessary. SSH2Shell has become something of a keystone of the maintenance tool I'm writing, so I have quite the interest of seeing these kinds of kinks ironed out :smiley:

**Comment by codexnovus** [comment]
By reading the logs I can see that for some reason the "ssh" command does not trigger the "command waiting" prompt on my system and goes to the next command. I can see in the buffer some ANSI codes, but I don't know if this could be triggering the error.

**Comment by cmp-202** [comment]
Can you post the debug log and verbose with sensitive detail removed I am going to spend time on this now.
Thanks and sorry it has taken so long.

**Comment by cmp-202** [comment]
I am just working on removing the pre connection test. If connection fails it fails.

**Comment by codexnovus** [comment]
This log I collected with a version of your library I modified to skip the connection test.

```
<Jumpbox IP>: Connection.connect
Connected to Jumpbox
<Jumpbox IP>: Connection.ready
Ready for launching connections to new servers
<Jumpbox IP>: Connection.shell
Last login: Wed Jan 23 12:46:04 2019 from <my ip>
<Jumpbox IP>: No command processing to first prompt
<server welcome banner>
<Jumpbox IP>: No command processing to first prompt
[<user>@<servername> ~]$
<Jumpbox IP>: ASCII filter: [^
 -~], response is ok: true
<Jumpbox IP>: First prompt detected
<Jumpbox IP>: No commands so exit
<Jumpbox IP>: Run exit
<Jumpbox IP>: Next host from this host <next host object>
<Jumpbox IP>: SSH to <External server IP>
<Jumpbox IP>: Clearing previous event handlers
<External server IP>: SSH: connect
<External server IP>: Host.commands: ssh -x  -o "StrictHostKeyChecking=no" -p 22 <username>@<External server IP>,sudo su - <auth user>,ls
<External server IP>: Next command from host.commands: ssh -x  -o "StrictHostKeyChecking=no" -p 22 <username>@<External server IP>
<External server IP>: Notifications: Normal Command to run
<External server IP>: running: ssh -x  -o "StrictHostKeyChecking=no" -p 22 <username>@<External server IP>
<External server IP>: Host.commands: sudo su - <auth user>,ls
<External server IP>: Next command from host.commands: sudo su - <auth user>
<External server IP>: Notifications: Normal Command to run
<External server IP>: running: sudo su - <auth user>
.174-x  -o "StrictHostKeyChecking=no" -p 22 <user>@10.0.1

<External server IP>: Command waiting
sudo su - <auth user>

<External server IP>: Command waiting
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false
<External server IP>: ASCII filter: [^
 -~], response is ok: true
<External server IP>: Password prompt: process 
<External server IP>: Password prompt: Password Sent: false
<External server IP>: Password prompt: Buffer: ssh -x  -o "StrictHostKeyChecking=no" -p 22 <username>@10.60.108.174
[?1l>

Authorized uses only. All activity may be monitored and reported.

<External server IP>: Command waiting
<user>@<External server IP>'s password:
<External server IP>: Command waiting
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false
<External server IP>: ASCII filter: [^
 -~], response is ok: false
<External server IP>: Password prompt: process 
<External server IP>: Password prompt: Password Sent: false
<External server IP>: Password prompt: Buffer: ssh -x  -o "StrictHostKeyChecking=no" -p 22 <username>@<External server IP>
[?1l>
Authorized uses only. All activity may be monitored and reported.
<username>@<External server IP>'s password: 
<External server IP>: Password prompt: Send password 
<External server IP>: Sent password: <password>
<External server IP>: Command waiting
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false
<External server IP>: ASCII filter: [^
 -~], response is ok: false
<External server IP>: Password prompt: process 
<External server IP>: Password prompt: Password Sent: true
Last login: Wed Jan 23 17:46:07 2019 from <jumpbox ip>
Authorized uses only. All activity may be monitored and reported.

<External server IP>: Command waiting
<external server welcome banner>

<External server IP>: Command waiting
<username>@<servername> <username>>

<External server IP>: Command waiting
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false
<External server IP>: ASCII filter: [^
 -~], response is ok: false
<External server IP>: Password prompt: process 
<External server IP>: Password prompt: Password Sent: true
Connection to <External server IP> closed by remote host.
Connection to <External server IP> closed.
<External server IP>: Command waiting
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: false
<External server IP>: ASCII filter: [^
                                                  -~], response is ok: true
<External server IP>: Password prompt: process
<External server IP>: Password prompt: Password Sent: true
<External server IP>: Password prompt: Standard prompt detected
<External server IP>: Sudo su adding exit.
<External server IP>: Command complete:
Command:
sudo su - onelink
.174                                             Response: ssh -x  -o "StrictHostKeyChecking=no" -p 22 pmuntal@10.0.1
                                                 [?1l>
Authorized uses only. All activity may be monitored and reported.
                                                 <username>@<external server ip>'s password:
Last login: Wed Jan 23 17:46:07 2019 from <jumpbox ip>
                                                 Authorized uses only. All activity may be monitored and reported.
<external server welcome banner>
 <username>@<externalservername> <username>> Connection to <external server ip> closed by remote host.
                                                 Connection to <external server ip> closed.
                                                 [?1h=[<username>@<jumpboxservername> ~]$
<External server IP>: Raising commandComplete event
<External server IP>: Class.commandComplete
<External server IP>: Host.commands: ls
<External server IP>: Next command from host.commands: ls
<External server IP>: Notifications: Normal Command to run
<External server IP>: running: ls
ls
<External server IP>: Command waiting
<results of the ls from the jumpbox home directory>
<External server IP>: Command waiting
<more results of the ls from the jumpbox home directory>
<External server IP>: Command waiting
[<username>@<jumpboxservername> ~]$
<External server IP>: text formatting filter: ([{1}[0-9;]+m{1}), response is ok: true
<External server IP>: ASCII filter: [^
                                                  -~], response is ok: true
<External server IP>: Normal prompt detected
<External server IP>: Command complete:
Command:
ls
Response:
<results of the ls from the jumpbox home directory>
<External server IP>: Raising commandComplete event
<External server IP>: Class.commandComplete
<External server IP>: No commands so exit
<External server IP>: Run exit
<External server IP>: Queued exit commands: exit
<External server IP>: running: exit
exit
logout
<External server IP>: Command waiting
<External server IP>: Stream.finish
<External server IP>: Class.end
<External server IP>: Stream.close
<External server IP>: Connection.close
SSH connection to <External server IP> closed
(sshObj launches the callback for object finished. We close the VPN and clean the report)
Data processing: data received timeout
BACKEND > Timeout on command exit. Comand: sudo su - <authorized user>
```

Here's the SSH config:

```
sshObj = {
    server: {
        host: '<jumpbox ip>',
        port: '22',
        userName: '<jumpbox user>',
        password: '<jumpbox pass>'
    },
    idleTimeOut: 6000,
    msg: {
        send: sshOnMessage
    },
    onError: sshOnError,
    onCommandTimeout: sshOnCommandTimeout,
    onData: (data) => {
        console.log(data);
    },
    standardPrompt: '$',
    commands: [],
    connectedMessage: "Connected to Jumpbox",
    readyMessage: "Ready for launching connections to new servers",
    closedMessage: "Disconnected from Jumpbox",
    debug: true,
    verbose: true,
    disableColorFilter: true,
    hosts: [
        server: {
            host: <external server ip>,
            port: '22',
            userName: <user>,
            password: <pass>
        },
        commands: [
            'sudo su - onelink',
            'ls',
        ],
        idleTimeOut: 6000,
        connectedMessage: `Connected to ${ip}`,
        closedMessage: `SSH connection to ${ip} closed`,
        msg: {
            send: sshOnMessage
        },
        onError: sshOnError,
        onCommandTimeout: sshOnCommandTimeout,
    ],
}

```
sshOnMessage logs the received message in different mediums
sshOnCommandTimeout generates a console error (it will do more things in the future)
sshOnError cancels the process and generates a console message

**Comment by codexnovus** [comment]
If needed I can rerun the tests with a vanilla library but happens more or less the same, except it never captures the password prompt, never sends the proper connection string, and as with the above example, assumes it already is connected to the external server although is not really true.

**Comment by cmp-202** [comment]
Hosts is an array of host objects it should be:

```javascript
host2: {server: {
            host: <external server ip>,
            port: '22',
            userName: <user>,
            password: <pass>
        },
        commands: [
            'sudo su - onelink',
            'ls',
        ],
        idleTimeOut: 6000,
        connectedMessage: `Connected to ${ip}`,
        closedMessage: `SSH connection to ${ip} closed`,
        msg: {
            send: sshOnMessage
        },
        onError: sshOnError,
        onCommandTimeout: sshOnCommandTimeout,
    }

host.hosts = [host2]
```

I have worked through the ssh connection code, it wasn't just pre check it was all of the SSH connection prompt detection that need updating. If you grab the latest commit and give that a try it should connect for you. One thing I am not sure of is recursive failure fallback but that might not be an issue for you. Thats where a ssh connection legitimately fails at which point the previous host object should be reloaded.
If there are no more hosts and commands for that host it should roll back to the previous host if there is one or end and so on.
See how you go and let me know.
Cheers,

Andrew

**Comment by cmp-202** [comment]
I am about 90% there and there is a commit to master that is good to use.
Tunneling ssh connection detection is passing tests.
Sequential host connections 1->2->3 are working and a failed connection to say host 3 seems to be rolling back through the hosts as expected with the desired session text for each.
A number of hosts in a host.hosts array 1->2,3 works when connections complete but if one fails it is not returning to the previous host and closing the connection correctly. I get a command timeout from the wrong host IP config in debug.
This may not affect you but is the last 10% to resolve.
I will not get to work on this until probably the end of the week maybe weekend I hope this helps in the mean time.
Checkout ssh2shell/test/tunneltest.js for my test example.
Cheers,

Andrew

**Comment by codexnovus** [comment]
I've been doing tests but so far had no luck connecting to the second server. Also discovered that normal connections bug on me with this on the latest version:

```
/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:481
        this._connections[0].sessionText += "\n\n" + this.sshObj.server.host + ":" + this.sshObj.sessionText;

TypeError: Cannot read property 'sessionText' of undefined
    at SSH2Shell._runExit (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:481:26)
    at SSH2Shell._runExit (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:4:59)
    at SSH2Shell._nextCommand (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:341:21)
    at SSH2Shell._nextCommand (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:4:59)
    at SSH2Shell._commandComplete (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:322:21)
    at SSH2Shell._commandComplete (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:4:59)
    at Timeout._onTimeout (/home/onelink/projects/ope-ng-server/node_modules/ssh2shell/lib/ssh2shell.js:108:28)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
```

I'm creating some synthetic tests that I hope will help me explain better where is failing, because right now the output I'm getting is a bit confusing.

**Comment by codexnovus** [comment]
Quick update to say that it passes all synthetic tests I made so far, so probably there's something wrong with my coding now. Thanks for fixing it!

**Comment by codexnovus** [comment]
I discovered that the problem I had has something to do with the particular server, that uses escape codes that seem to confound the app. To be precise, the following escape codes where not filtered ([?1h=) and ([?1l>).  Switching to a different server (that does not generate these codes) seemed to solve the problem

**Comment by cmp-202** [comment]
Lol don't you hate that.
There are a couple of options:
1. Remove '>' from the standard prompt chars option: `host.standardPrompt = "$%#"`
and/or
2. Change the host.textColorFilter regular expression for just that host config to match the different format escaping. 

I still have the last ssh failed rollback for multiple hosts on the same level to fix and test before I can publish. I might not get to that until the weekend. Good to get this all sorted and tested again.

*Background*
Ssh2shell came out of a hubot chat bot script that performed git version deploys to a staging and production server via commands entered into chat. The production server could only be accessed through the staging server. No devs had permission to access production directly, no passwords, it was cert authentication only on both servers for all accounts. It was only the hubot staging login that had the cert for accessing production and no one could access it. Because the whole process was scripted for both servers it was always done the same way, no manual deploy commands it was only done in chat. 

The process was: Deploy (branch, commit, version) to staging, test, version stable release code and then deploy only versioned code to production requiring two people to confirm the deployment. Or rollback to a known working version for either server. 

And so the tunneling through staging to production to run git commands is where it began.

**Comment by cmp-202** [comment]
I'm going to close this one.
