### ISSUE TITLE
password prompt in german

### ISSUE THREAD

**Issue by etos-git** [cmp-202/ssh2shell#66]
I've problem with detecting password prompt in german. I can see in the code:
`  @passwordPromt            = new RegExp("password.*" + @sshObj.passwordPromt + "\\s?$","i") unless @passwordPromt
    @passphrasePromt          = new RegExp("password.*" + @sshObj.passphrasePromt + "\\s?$","i") unless @passphrasePromt`,
but our prompt is
`[sudo] Passwort für <username>: `.
It results in endless waiting for password.

**Comment by etos-git** [comment]
OK, I found it. I need to have:
`		const shell = new ssh2shell(script);
		**shell.passwordPromt = new RegExp('passwor[dt].*:\\s?$', 'i');**
		shell.connect((sessionText) => {
			return done();
		});`

**Comment by cmp-202** [comment]
Yep I will add that in. Bad hard coding.

**Comment by cmp-202** [comment]
I committed to master a change that gives access in the host.passPromptText value to set whatever is needed or default to the old hard coded "Password". Readme updated for host definition.
