### ISSUE TITLE
"Expecting" a specific output before executing the next command

### ISSUE THREAD

**Issue by theunreal** [cmp-202/ssh2shell#68]
How I can wait for a specific output from a command before executing the next one?

**Comment by cmp-202** [comment]
Hi,
Yes.
You can use onCommandProcessing event to check for the desired output from the command being run and then manipulate the commands array by either adding or removing commands from the array or terminate the connection.

There is a similar example using onCommandProcessing in the readme here:
https://github.com/cmp-202/ssh2shell/blob/master/README.md#responding-to-non-standard-command-prompts

Also the /test/timeouttest.js has similar command result testing example but of course for timeout event.

So in an onCommandProcessing event handler test is the command being run, has the data received have the content you require. If so do what is required next, if not keep waiting.

Failure: use onCommandComplete, test for command and confirm response doesn't contain what's required. Here you can terminate the session or set a new command or whatever you need as a result of the failure.

**Comment by cmp-202** [comment]
I am going to close this one.
