### ISSUE TITLE
How to execute command that take some time to load answear ?

### ISSUE THREAD

**Issue by cahobaut** [cmp-202/ssh2shell#70]
`
var dotenv = require('dotenv').config();
var fs = require('fs');

//dotenv.load();

var host2 = {
        server: {
                host:         process.env.SERVER2_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER2_USER_NAME,
                password:     process.env.SERVER2_PASSWORD,

        },
        commands:[],
        connectedMessage: 'connected to host2',
        debug: true,
        verbose: true,
};

var host3 = {
        server: {
                host:         process.env.SERVER3_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER3_USER_NAME,
                password:     process.env.SERVER3_PASSWORD,

        },
        commands: ['dr_check'],
        connectedMessage:'connected to host3',
        debug: true,
        verbose: true,
};

host2.hosts = [host3];
var SSH2Shell = require('ssh2shell'),
_SSH = new SSH2Shell(host2);
callback = function(sessionText){
        console.log('le résulat est le suivant: ',sessionText);
        fs.writeFile('../../Data2/LOG/test.txt', sessionText, function (err) {
                if (err) console.log(err);
                else console.log('création du fichier ok');
        });
}
_SSH.connect(callback);

`

the command 'dr_check' take some time to send answear when I do it manualy. This is the first problem
 
Debug
`
Ready
host3: Host.commands: dr_check
host3: Next command from host.commands: dr_check
host3: Notifications: Normal Command to run
host3: sending: dr_check
host3: run command
host3: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
host3: Non-standard ASCII filtered: false
Data processing: data received timeout
host3: Class.commandTimeout
host3: Timeout command: dr_check response:
============================
 DR_CHECK PROCEDURE STARTED 27/09/2019-17:35:46

host3: Process an exit
host3: Queued exit commands: 1
host3: sending: exit
host3: run command
host3: Class.error
Timeout error: host3: Command timed out after 5 seconds
host3: Connection.close
Closed
le résulat est le suivant:
host3: Stream.finish
host3: Class.end
host3: Clearing host event handlers
création du fichier ok
`
I can understand that there is a timeout problem, isn't it?
How can I manage the timeout to allow more time for example?

**Comment by cahobaut** [comment]
I've identify this line into the lib 
`
this.idleTime = (ref2 = this.sshObj.idleTimeOut) != null ? ref2 : 5000;
`
Is it the def on the timeout ? Should I try to modify yoour lib ?

**Comment by cmp-202** [comment]
Look in the readme for timeout handling.On 28/09/2019 3:47 AM, cahobaut <notifications@github.com> wrote:I've identify this line into the lib
this.idleTime = (ref2 = this.sshObj.idleTimeOut) != null ? ref2 : 5000;
Is it the def on the timeout ? Should I try to modify yoour lib ?

**Comment by cahobaut** [comment]
Thank you I've seen the exemple. I've another question please, When I'm connected to my host I use command to connect to MySQL it work but when I use 'exit' command to close my sql it close the connection and finish the program. Any suggestion ?

**Comment by cahobaut** [comment]
I've been able to use 'quit' to replace 'exit' command but I'm not sure that it'll be the case for all my connections.

**Comment by cmp-202** [comment]
Moving this to a new issue.

**Comment by cmp-202** [comment]
According to the [MySQL 8.0 Ref](https://dev.mysql.com/doc/refman/8.0/en/mysql-commands.html) you can use "\q" for both exit and quit.
