### ISSUE TITLE
How to pipe command ?

### ISSUE THREAD

**Issue by cahobaut** [cmp-202/ssh2shell#71]
I try to execute command with pipe like 'quest -a | grep down' but it seems not working. It fails in my onCommandTimeout with error: cannot read property sessionText of undefined

**Comment by cmp-202** [comment]
That sounds like a bug.

**Comment by cmp-202** [comment]
I went through the timeout test and added in a secondary host just in case and I couldn't reproduce it.
The command timeout indicates it can't detect a valid prompt after a command is sent.
Is the prompt that results from that piped command in the default prompt characters `host.standardPrompt = ">$%#"`

**Comment by cahobaut** [comment]
It isn't. I try to test command separately and I can get result but when I pass all my commands it stops somewhere.


`

var host1 = {
        server: {
                host:         process.env.SERVER1_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER1_USER_NAME,
                password:     process.env.SERVER1_PASSWORD,

        },
        commands:[],
        connectedMessage: 'connected to host1',
        debug: true,
        verbose: true,
};

var host2 = {
        server: {
                host:         process.env.SERVER2_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER2_USER_NAME,
                password:     process.env.SERVER2_PASSWORD,

        },

        commands: ['dr_check','my_cmgm','all status','exit','my_conn','use udb','select * ...','quit','quest -a | grep down','df -k','quit','quit','quit' ],
        connectedMessage:'connected to host2',
        debug: true,
        verbose: true,
};

host1.hosts = [host2];

host2.onCommandTimeout = function (command, response, stream, connection) {
        if(this.sshObj.debug){this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout");}
        if ( command== "dr_check" || command=="quest -a | grep down" && host2.nodePrompt != true) {
                this.sshObj.nodePrompt = true;
        }else {
                this.emit("error", this.sshObj.server.host
                + ": Command timed out after #{this._idleTime/1000} seconds. command: "
                + command, "Timeout", true, function(err, type){
                        this.sshObj.sessionText += response;

                })
        }
}

var SSH2Shell = require('ssh2shell'),
_SSH = new SSH2Shell(host1);
callback = function(sessionText){
        console.log('le résulat est le suivant: ',sessionText);
        fs.writeFile('../../Data2/LOG/test.txt', sessionText, function (err) {
                if (err) console.log(err);
                else console.log('création du fichier ok');
        });
}
_SSH.connect(callback);
`


When I do this I can see execution of commands but it fails on quest -a | grep down but when I start my commands with this one it works. I this my problem is into my onCommandTimeout. How can I correctly pass all commands that are supposed to be a problem there ?

**Comment by cmp-202** [comment]
Lets simplify your timeout to see what is happening.

```javascript
host2.onCommandTimeout = function (command, response, stream, connection) {
    this.emit("msg", this.sshObj.server.host + ": Timeout: command: " + command + ". response: " + response)
}
```
We want to see the output from that.
If you do not write to the stream in response the timeout will close the connection.
The error raised is also using `true` which also closes the connection. I might have to review the example if that came from the readme. I know it's in the test file.

I also see an "exit" command in your commands, is that not giving you problems with disconnection as you indicated.

**Comment by cahobaut** [comment]
When I use this simpliciity there is no problem I can execute all my commands. It was a mistake I've retry with exit but it still close connections. This is not the biggest problem now. Thank you I really appreciate your help. I'll surely open an other issue about how to do I on a set of host in parallel but I'll try it before.
