### ISSUE TITLE
Multi connection on servers using the same jumping host

### ISSUE THREAD

**Issue by cahobaut** [cmp-202/ssh2shell#73]
Hey, I've an other problem today lol
I want to access multipes server, all thoses are available via a same host. I'm  able to connect to one of them using my jump. It's a litle bit more complicated when I try to do it on all of them at the same time.

Here what I've try: 
`var host1 = {
        server: {
                host:         process.env.SERVER1_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER1_USER_NAME,
        //      password:     process.env.SERVER1_PASSWORD,
                privateKey:   fs.readFileSync('/path/key'),
        },
        readyTimeout: 99999,
        commands:[],
        connectedMessage: 'connected to host1',
        debug: true,
        verbose: true,
};

sql.query("select * from equipement where idGroupe = 34", function(err,res){

        if(err){
                console.log("error: ", err);
        }
else{
                for (var i = 0; i< res.length; i++){
                        res[i].IP = ipInt(res[i].IP).toIP();
                        //console.log(res[i]);
                        var host2 = {
                                server: {
                                        host: res[i].IP,
                                        port: process.env.PORT,
                                        userName: 'login',
                                        password: 'pwd',
                                },
                                commands:[arrayCommands],
                                connectedMessage: 'connected to host2'+res[i].Nom,
                                debug: true,
                                verbose: true,
                        };
                        host1.hosts = [host2];

                        host1.onCommandTimeout = function (command, response, stream, connection){
                                this.emit("msg", this.sshObj.host + ": host.onCommandTimeout");
                        }

                        host2.onCommandTimeout = function (command, response, strzam, connection) {
                                this.emit("msg", this.sshObj.host + ": host.onCommandTimeout");
                        }
                        _SSH = new SSH2Shell(host1);
                        var fichier = '../../Data2/LOG/'+res[i].Nom+'.txt';
                        callback = function(sessionText) {
                                console.log('le résultat est le suivant: ', sessionText);
                                fs.writeFile(fichier, sessionText, function(err){
                                        if (err) console.log(err);
                                        else console.log('création du fichier ok');
                                });
                        }
                        _SSH.connect(callback);

                }
        }

});`
So I create the client for the jumping host then I loop on server list that I want to access then I create client for them then I connect.

I've theses outputs 
`host1: initiate
host1: Connection.connect
connected to host1
host1: Connection.connect
connected to host1
host1: Connection.ready
Ready
host1: Connection.ready
Ready
host1: Connection.shell
host1: Connection.shell
host1: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
host1: Non-standard ASCII filtered: false
host1: First prompt detected
host1: No commands so exit
host1: Process an exit
host1: Next host from this host
host1: SSH to host2
host1: Clearing previous event handlers
host2: Clearing host event handlers
host2: Load Defaults
host2: Host loaded

[host2 object ]

hosst2: initiate
host2: SSH command: connect
host2: sending: ssh -x  -o "StrictHostKeyChecking=no" -p 22 login@host2
host2: run command
host1: text formatting filter: ([{1}[0-9;]+m{1}), filtered: false
host1: Non-standard ASCII filtered: false
host1: First prompt detected
host1: No commands so exit
host1: Process an exit
host1: load previous host
host1: Closed
host1: Load previous host config
host1: Class.end
host1: Previous hosts: 1
host1: Reload previous host
host1: Load Defaults
host1: Host loaded

[host1 object]

host1: Process an exit
host1: Exit command: Stream: close
host1: Stream.finish
host1: Class.end
host1: Clearing host event handlers
le résultat est le suivant:  host1:

création du fichier ok
[Execution of all commands on host2]

host2: Raising commandComplete event
host2: Class.commandComplete
host2: No commands so exit
host2: Process an exit
host2: Queued exit commands: 1
/home/alvin/globaldata/Alvin02v/node_modules/ssh2shell/lib/ssh2shell.js:493
        this._connections[0].sessionText += "\n" + this.sshObj.server.host + ": " + this.sshObj.sessionText;
                         ^

TypeError: Cannot read property 'sessionText' of undefined

`
I Don't really understand. Can you give me some suggestions plz?

**Comment by cmp-202** [comment]
Are you using the npm package? Your output doesn't look like what I get for a single host jump test.
Also can you look up the markup definitions for posting in github and indent code I find it hard to read. If you want to know how it will look use the preview tab for each comment.

**Comment by cmp-202** [comment]
Not sure if this of use but probably good to know.

I did a significant rewrite of the multi host management in the latest version.
So you know how you use the following:
`SSH = new SSH2Shell(host)` to set the first host that connects using SSH2.
you can also use:
`SSH = new SSH2Shell([host1, host2, host3, host4,...])`
This is an array of primary hosts which in each case is also connected to using SSH2 not running an ssh command.

Each primary host can also have secondary hosts as normal.
If you can get to each directly rather than using one to get to all the others this would work for you.

**Comment by cahobaut** [comment]
I've upgrade the the latest v 1 Week ago. I think this is related to the loop. I've try Something else:
```typescript
var host1 = {
        server: {
                host:         process.env.SERVER1_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER1_USER_NAME,
                privateKey:   fs.readFileSync('/home/alvin/.ssh/id_rsa'),
        },
        commands:['uptime'],
        connectedMessage: 'connected to host1',
        debug: true,
        verbose: true,
};
var host2 = {
        server: {
                host:         process.env.SERVER2_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER2_USER_NAME,
                password:     process.env.SERVER2_PASSWORD,

        },
        commands: commands,
        connectedMessage:'connected to host2',
        debug: true,
        verbose: true,
};
var host3 = {
        server: {
                host:         process.env.SERVER3_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER3_USER_NAME,
                password:     process.env.SERVER3_PASSWORD,
         },
        commands: commands,
        connectedMessage: 'connected to host3',
        debug: true,
        verbosee: true
};
host1.hosts = [host2, host3];
host2.onCommandTimeout = function (command, response, stream, connection) {
        this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout");
}

host2.onEnd = function (sessionText, sshObj){
        this.emit('msg', this.sshObj.server.host+ ': host.onEnd event');
}

var SSH2Shell = require('ssh2shell'),
_SSH = new SSH2Shell(host1);
callback = function(sessionText){
        console.log('le résulat est le suivant: ',sessionText);
        fs.writeFile('../../Data2/LOG/test.txt', sessionText, function (err) {
                if (err) console.log(err);
                else console.log('création du fichier ok');
        });
}
_SSH.connect(callback);
```

**Comment by cahobaut** [comment]
I've upgrade the the latest v 1 Week ago. I think this is related to the loop. I've try Something else:
```typescript
var host1 = {
        server: {
                host:         process.env.SERVER1_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER1_USER_NAME,
                privateKey:   fs.readFileSync('/home/alvin/.ssh/id_rsa'),
        },
        commands:['uptime'],
        connectedMessage: 'connected to host1',
        debug: true,
        verbose: true,
};
var host2 = {
        server: {
                host:         process.env.SERVER2_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER2_USER_NAME,
                password:     process.env.SERVER2_PASSWORD,

        },
        commands: commands,
        connectedMessage:'connected to host2',
        debug: true,
        verbose: true,
};
var host3 = {
        server: {
                host:         process.env.SERVER3_HOST,
                port:         process.env.PORT,
                userName:     process.env.SERVER3_USER_NAME,
                password:     process.env.SERVER3_PASSWORD,
         },
        commands: commands,
        connectedMessage: 'connected to host3',
        debug: true,
        verbosee: true
};
host1.hosts = [host2, host3];
host2.onCommandTimeout = function (command, response, stream, connection) {
        this.emit("msg", this.sshObj.server.host + ": host.onCommandTimeout");
}

host2.onEnd = function (sessionText, sshObj){
        this.emit('msg', this.sshObj.server.host+ ': host.onEnd event');
}

var SSH2Shell = require('ssh2shell'),
_SSH = new SSH2Shell(host1);
callback = function(sessionText){
        console.log('le résulat est le suivant: ',sessionText);
        fs.writeFile('../../Data2/LOG/test.txt', sessionText, function (err) {
                if (err) console.log(err);
                else console.log('création du fichier ok');
        });
}
_SSH.connect(callback);
```

and the output is : 
```
```

**Comment by cmp-202** [comment]
Your code seems okay to me, output is as expected. The event handlers are not needed they do that by default.
Can you run `ssh2shell/test/tunneltest.js` edit the `host.server` details to match what you are connecting to.

**Comment by cmp-202** [comment]
I was wondering if your private key and passphrase might not be getting handled correctly by the code that makes the ssh connection. 
I haven't tested yet as I would have to set it all up and I don't have time tonight but it seems the key difference.
I will let you know.

**Comment by cahobaut** [comment]
I've try it but what I want is to access host2 via host1 then host3 via host1. I've replace

```typescript
host2.hosts = [ host3 ];
//Set the two hosts you are tunnelling to through host1
host1.hosts = [ host2 ];
```

with 

```typescript
//host2.hosts = [ host3 ];
//Set the two hosts you are tunnelling to through host1
host1.hosts = [ host2, host3 ];
```

I'm I right ?

Here is the output: 


```
Connected to host1
Ready
Connected to host2
Ready
host2ip: Closed
host3ip: SSH connection failed
host3ip: SSH failed response: ^
Error: Invalid parameter.
*A:COR1IMSRSW01#
host3ip: Closed
-----Callback session text:
host1ip: echo host1
host1
cha2imsomc01:axadmin #
host2ip: echo host2
                 ^
MINOR: CLI Command not allowed for this user.
*A:COR1IMSRSW01#

-----Callback end
```

There is a problem when connecting to the host3

**Comment by cahobaut** [comment]
thank you. I Don't use passphrase it was working without

**Comment by cmp-202** [comment]
Sorry my bad.
So this is what I get when I run a modified version of ./test/tunneltest.js as you require:

```
node .\test\tunneltest.js
Connected to host1
Ready
Connected to host2
Ready
192.168.0.31: Closed
Connected to host3
Ready
192.168.0.32: Closed
>> -----Callback session text:
192.168.0.30:
192.168.0.31: echo host2
host2
user@server2:~$
192.168.0.32: echo host3
host3
user@server3:~$
-----Callback end
```
What is your error: MINOR: CLI Command not allowed for this user. You might need to resolve that.
I would recommend following the steps of each connection and commands manually just in case there is some thing wrong there.

**Comment by cahobaut** [comment]
I've replace the echo command with an other that is allowed on this server. 
It seems like there is a problem to connect to the third host:
output:

```
Connected to host1
Ready
Connected to host3
Ready
host3: Closed
host2: SSH connection failed
host2: SSH failed response: ^
Error: Invalid parameter.
*A:COR1IMSRSW02#
host2: Closed
-----Callback session text:
host1: echo host1
host1
cha2imsomc01:axadmin #
host3: environment no more
*A:COR1IMSRSW02#show bof
===============================================================================
BOF (Memory)
===============================================================================
    primary-image    cf3:\TiMOS-C-14.0.R8
    primary-config   cf3:\config.cfg
    address          --------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    static-route     ---------------
    no autonegotiate
    duplex           full
    speed            100
    wait             3
    persist          on
    no li-local-save
    no li-separate
    no fips-140-2
    console-speed    115200
===============================================================================
*A:COR1IMSRSW02#

-----Callback end
```


I've try to switch host2 and host3 in host1's hosts array to verify if it there was bad parameter but it still connect to the fiirst one then raise an error. Maybe related to the privatekey ?

**Comment by cmp-202** [comment]
Is this in your host:
host.server.privateKey = require('fs').readFileSync('/path/to/private/key/id_rsa'),

**Comment by cmp-202** [comment]
Also always good to search the readme as it might already be covered.

**Comment by cmp-202** [comment]
Can you look on SSH server logs for failed attempt events so we can get more info. 

If helpful after that can you save debug and verbose content to a file and attach it to your post.

**Comment by cmp-202** [comment]
I reworked you first code block so you can see how I would have done it.
It isn't a solution its an example.

```javascript
var debug: true,
    verbose: true,
    host1 = {
        server: {
            //SSH2.client connect options 
	    host: process.env.SERVER1_HOST,
            port: process.env.PORT,
            userName: process.env.SERVER1_USER_NAME,
            privateKey: fs.readFileSync('/path/key'),
            
	    //SSH secondary connection options go here
	    ssh{
                //Secondary host ssh connection flags go here
		//Options go here, ConnectTimeout instead of readyTimeout. 
		//Ref https://man.openbsd.org/ssh_config.5#ConnectTimeout
		options: {ConnectTimeout: #####}
            }
        },
        commands:[],
        connectedMessage: 'connected to host1',
        debug: debug,
        verbose: verbose
    },
    hosts = [];

sql.query("select * from equipement where idGroupe = 34", function(err,res){
    if(err){
        console.log("error: ", err);
    }
    else
    {
        for (var i = 0; i< res.length; i++){
            res[i].IP = ipInt(res[i].IP).toIP();

            //console.log(res[i]);
            hosts[i] = {
                server: {
                    host: res[i].IP,
                    port: process.env.PORT,
                    userName: 'login',
                    password: 'pwd',
                },
                //arrayCommands defined somewhere else. 
                commands:[arrayCommands],
                connectedMessage: 'connected to host'+i+" "+res[i].Nom,

                //write the final log for this host here (not callback)
                onEnd: function(sessionText, sshObj) {
                    console.log('le résultat est le suivant: ', sessionText);

                    fs.writeFile(sshObj.logFile, sessionText, function(err){
                        if (err) console.log(err);
                        else console.log('création du fichier ok');
                    });
                }
                logFile: '../../Data2/LOG/'+res[i].Nom+'.txt'
                debug: debug,
                verbose: verbose,
            };
        }
    }
});

host1.hosts = hosts;

//Only set timeout handlers if you require special handling. Timeouts can be seen in debug/verbose
_SSH = new SSH2Shell(host1);

callback = function(sessionText) {
    //only run at end of SSH2 connections
    console.log('le résultat est le suivant: ', sessionText);	
}

_SSH.connect(callback);
```

**Comment by cmp-202** [comment]
Not sure if this is of any use.
I don't know if you need to connect to the first host or not to make the secondary connections you are wanting to get to but it is possible to set an array of primary hosts when making the instance.
Each primary host connects using SSH2.client not ssh command.

e.g.
```javascript
//primary hosts
hosts = [ host1, host2, host3, host4]
_SSH = new SSH2Shell(hosts);

compared to 
//one primary the rest secondary
host = {...}
host.hosts = [ host1, host2, host3, host4]
_SSH = new SSH2Shell(host);
```

**Comment by cmp-202** [comment]
Is this still unresolved?
