### ISSUE TITLE
Messages every time

### ISSUE THREAD

**Issue by simakwm** [cmp-202/ssh2shell#74]
How do I make this module silent? I mean, no "Connected", "Ready" or "Closed" output to console every session?

**Comment by cmp-202** [comment]
I didn't get the notifications for these last three issues and although they are likely to be pointless now I will put the response in case others have the same question.

The connection related messages are always sent to the msg output. Setting the default to "" or " " may hide those messages.
The only other option is for me to add a connection messages flag to turn it on and off.

**Comment by cmp-202** [comment]
Will reopen if this needs more attention.
