### ISSUE TITLE
How to get file contents?

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [cmp-202/ssh2shell#76]
I am new to ssh2shell 

```
const host = {
    server: {
        host: '**********',
        userName: '*****',
        passPhrase: '*******',
        privateKey: require('fs').readFileSync('./privatekey.ppk'),
        streamEncoding:     "utf8",
    },
    commands: [
         "sudo -i"
        ,"sudo ssh qa-etl-1"
        , "sudo -i",
        "cd /home/salt/eventSub",
        "ls -1",
         "tail -f  log.log"
    ]
};

var SSH2Shell = require('ssh2shell'),
    SSH = new SSH2Shell(host),
    callback = function (sessionText) {
        console.log(sessionText)
    }
SSH.connect(callback);
```

![image](https://user-images.githubusercontent.com/26269665/86797234-0e3caa80-c08d-11ea-96b4-287f3c564db7.png)

I am struggling to get the file contents of log file

**Comment by cmp-202** [comment]
Sorry I didn't get the notification of the last three issues. This may be of no use now but I will give you what I think anyway.

Command timeout is triggered when there is no data from the stream for 5 seconds (default) from when the command was sent.
If the tail command is taking more than 5 seconds to process the log file before returning the output the timeout will then be triggered. 
The timeout time can be increased in the host config, commandProcessing, or commandTimeout events and then reverted if needed in commandComplete.
This may give you the delay needed for the tail command to output its data.

**Comment by cmp-202** [comment]
I am closing this unless there is any more activity on it.
