### ISSUE TITLE
Is there any way of adding a delay between commands?

### ISSUE THREAD

**Issue by liben96** [cmp-202/ssh2shell#77]
Hi guys,
First of all thanks for this useful library.

My question: is there any way of adding delay between commands? 

Basically I pass an array of commands to send to the server. I also parse the response on the 'onCommandComplete' event. Depending on the respond of some commands... I need to add new commands, stop the process, etc.

I have noticed that there is no option to add a delay between commands. 
idleTimeOut and dataIdleTimeOut -> only work for waiting the response of the server.

Can you help with this?

Also, when I want to stop the process If one command fails... what I am doing is just empty the commands array in the sshObject.
Is this approach correct?

Thanks

**Comment by cmp-202** [comment]
Hi,
Your welcome.
No it isn't possible to add a delay as the process is event-driven from the stream and would need another timer to do it. There are two timers already: one for the time since the last data event and the command timeout, I don't want to add more timers. If a command is timing out then the commandTimeout event can be used to handle it. IdleTime can be changed on the fly if a command needs more time.

The [single host example](https://github.com/cmp-202/ssh2shell#connecting-to-a-single-host) in the readme shows the handling of different command output.

Clearing the commands array will terminate the connection but you can also try `this._runExit()` if using multiple hosts or `this.close()` for a single host, this has just been added in the recent update. If using commandProcessing the stream is passed in the event variables so `stream.close()` can be called directly also.

`this._runExit()` goes through all the hosts and connections management while exiting a host connection compared to `this.close() and stream.close()` which closes the stream directly.
I hope that helps.

Andrew

**Comment by liben96** [comment]
Ok. Thanks for you answer Andrew.

**Comment by liben96** [comment]
Hi,
Is this now available in the version?
Thanks

**Comment by cmp-202** [comment]
Hi,
I hope this isn't a dumb question but what is the case for needing delays between completed commands?

There is another option: [persistent-shell](https://www.npmjs.com/package/persistent-shell).
It keeps the connection open with no command timeout so there is no time limit for a command to run.
Commands can be run using `this.runCommand(command)`.

Additional Events:
`onFirstPrompt` triggers when the connection is made and the first prompt is ready for you to run a command.
`onLastCommand` triggers when a command completes and the commands array is empty so you can run a new command.
`onCommandProcessing and onCommandComplete` are the same as in ssh2shell.

```javascript
var persistentShell = require (persistent-shell),
   host = {
      server:             {... },
      onLastCommand: function(command){
         if(command.indexOf("la") >-1){
            this.exit();
         }
      },
      onFirstPrompt: function(){
         this.runCommand("la");
      }
   },
   session = new persistentShell(host),
   callback = function( sessionText ){
         this.emit("info", "-----Callback\nSession text:\n\n" + sessionText);
         this.emit("info", "\n\n-----Callback end" );
   }

session.connect(callback)
```

**Comment by liben96** [comment]
Hi. 
Thanks for your message.
Our problem is that after sending a command, we need to read the response from the server... parse it, and then depending on some factors, we send one command or another... 
Our array of commands is dynamic depending on the response to some of the previous commands sent.
Currently, it sends the whole array with commands... one after the other.
We have found a workaround modifying a little bit the library... but I was asking if there is an official way of achieving it.
Thanks

**Comment by cmp-202** [comment]
Okay I think there are a couple of ways of doing it using `onCommandComplete` or `onCommandProcessing`, [`onCommandTimeout`](https://github.com/cmp-202/ssh2shell#command-time-out-event-handler) is the third but I think it is the first two based on your description. I am not sure how complicated your case is but this is the basic concept.

So the response parse is done in `onCommandComplete`.
You can add/remove a command, clear `sshObj.commands = []` which will close the connection or replace the `sshObj.commands` array with a new set of commands.

```javascript
host.onCommandComplete = function( command, response, sshObj ) {
  //say confirm it is the root home dir and the `cd.ssh` command
  if (command === "echo $(pwd)" && response.indexOf("/root") != -1 ) {
    //unshift will add the command as the next command, use push to add command as the last command
    sshObj.commands.unshift("cd .ssh");
  }
  //we are listing the dir so output it to the msg handler
  else if (command === "ls -l"){      
    sshObj.commands = [];
  }
  else {
    sshObj.commands = ["sudo echo $(pwd)", "sudo ls -l"];
  }
 }
```

`onCommandProcessing` checks the response as it is received before the command prompt is detected (command completed).
```javascript
host.onCommandProcessing = function( command, response, sshObj, stream ) {
   //Check the command and prompt exits and respond with a 'y' but only does it once
   if (command == "apt-get install nano" && response.indexOf("[y/N]?") != -1 && sshObj.firstRun != true) {
     sshObj.firstRun = true
     stream.write('y\n');
     //add a command
     sshObj.commands.unshift("echo \"next command added\"");
   }   
 };
```

**Comment by liben96** [comment]
That's very similar to what we are currently doing.

Thanks for your help :)
