### ISSUE TITLE
Stop a process when I want

### ISSUE THREAD

**Issue by Qlenglet** [cmp-202/ssh2shell#78]
Hello everybody,

I can't find any clue on the documentation about how can I terminate my command before it's finished. I need to implement this behavior for my app and I will be very nice If someone can show me how to do it with a simple example.

I tried to close the connection but I have an error wihich says that this._stream.close is not a function 

Thanks a lot

**Comment by cmp-202** [comment]
For anyone looking for an answer to this try using `commandProcessing` event to catch the command that needs terminating and send `stream.write('\x03')` (ctrl-c) to cancel the command and return to the prompt . If you want to terminate the whole connection you can use stream.close() for a single host or `this._runExit()` for a multi-host process. Stream is a property of commandProcessing event handler allowing you to access it directly for this very reason.
