### ISSUE TITLE
When I define OnError function,  the "close",  "callback" params are always undefined inside OnError function during runtime if any error occurs.

### ISSUE THREAD

**Issue by cheekykesav** [cmp-202/ssh2shell#79]
When I define OnError function,  the "close",  "callback" params are always undefined inside OnError function during runtime if any error occurs.

My expectation:  I should receive "close" - either default value: false   
                                                      "callback" - default inbuilt callback function

Error I got was connection.error though. But undefined values in close and callback.  

please let me know why am I getting this. I want to know how this callback and close works with OnError.

Thank you.

**Comment by cmp-202** [comment]
Hi,
So there are a couple of error handlers at different levels in the execution at runtime.

1. Connection.error: Which is what seems to be the error handler you are encountering and relates to the ssh2 connection process, top level.
2. Stream.error: Next level relates to the session stream resulting from the connection process.
3. Session.error: The last level is the errors you raise during the process of running commands.

The first two don't use the full host config `host.OnError` definition with close and callback but just return the basic error messages for each given the failure of both is likely to be before the session is active. Both are outside the session handling process and things like the `sessionText` probably don't exist for running a callback.
The last is raised by you as a result of a command error detected in the command response during `commandProcessing`, `commandComplete`, or the default `commandTimeout` events.

The default host.OnError handler checks the close and callback variables to avoid `undefined` as follows :(coffeescript)
```coffeescript
    @.on "error", (err, type, close = false, callback) =>
      @.emit 'msg', "#{@sshObj.server.host}: Class.error" if @sshObj.debug
      if ( err instanceof Error )
        @.emit 'msg', "Error: " + err.message + ", Level: " + err.level
      else
        @.emit 'msg', "#{type} error: " + err
      callback(err, type) if typeof callback == 'function'
      @connection.end() if close

   @connection.on "error", (err) =>
      @.emit 'msg', "#{@sshObj.server.host}: Connection.error" if @sshObj.debug
      @.emit "error", err, "Connection"

   @_stream.on "error", (err) =>
      @.emit 'msg', "#{@sshObj.server.host}: Stream.error" if @sshObj.debug
      @.emit 'error', err, "Stream"
```

**Comment by cheekykesav** [comment]
Thank you. This clarified my doubt.
