### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by perfectwebtech** [cmp-202/ssh2shell#80]
as any example with xterm or terminal 

can run browser base and want to multiple host connecting using terminal 

web base

**Comment by cmp-202** [comment]
Sorry for the late response I missed the email notification.
Not quite sure what you are aiming for. 
Can you give me some more information (without sensitive details) like what a correct process would like?
The host configs, error output, the output of verbose and debug.

Examples of multiple connections:
There is a [test file example](https://github.com/cmp-202/ssh2shell/blob/master/test/Multiple%20primary%20hosts.js)  
[and in the readme](https://github.com/cmp-202/ssh2shell#tunnelling-nested-host-objects)
