### ISSUE TITLE
Receiving Command time out on keyboard interactive mode due to unidentified prompt character

### ISSUE THREAD

**Issue by einkal** [cmp-202/ssh2shell#81]
Hello,

I have enabled the keyboard interactive feature on and receiving a response back from host but still I am receiving a time out.
I have tried the recommended stream.write('\n') approach in your example but it didn't help.
The probable reason which I have found out looking in into your code is that it is due the unidentified prompt characters.
The characters in your regex for standard prompt identification are - ">$%#"  but the prompt on my VM is  ":" (colon).
I am connecting to SUSE Linux Enterprise Server 11 SP4 using the ssh2shell module. 
Kindly help me to fix this error.

**Comment by cmp-202** [comment]
So did the connection to the server complete or is that returning the timeout?
Which timeout is important because if it is a connection timeout then it's the connecting to the server that is the problem like authentication failure, handled by SSH2.
If it is a command or prompt timeout then sending commands and handling the server responses has hung waiting for a response it won't get. Like a prompt character not in the default values.

Change prompt char:
```var host.standardPrompt = ":"```

Verbose and debug provide plenty of information.
```javascript
var host {
verbose:             true,  //outputs all received content
  debug:             true  //outputs information about each process step
}
```

**Comment by einkal** [comment]
Hello,

It's a command time out error that I am receiving. I can see the connection response from the server showing up in command processing and command time out eventually. I wi check of setting host.standardPrompt woul

**Comment by einkal** [comment]
Hello,

It's a command time out error that I am receiving. I can see the connection response from the server showing up in command processing and command time out eventually. I wi check of setting host.standardPrompt would help or not . As I would first connect to the VM and then do a sudo su , so the prompt would change again.

**Comment by cmp-202** [comment]
[`Sudo su`](https://github.com/cmp-202/ssh2shell#sudo-and-su-commands) processing is handled separately.
Again using verbose and debug will show you what is failing through that `sudo` process.
If a sudo prompt detection is failing it can be changed using `host.passwordPrompt = ":";`
See: [change prompts](https://github.com/cmp-202/ssh2shell#prompt-detection-override)
There is a [test file](https://github.com/cmp-202/ssh2shell/blob/master/test/sudosutest.js) that is a bit overly complicated but gives the different uses of `sudo and su`.

**Comment by cmp-202** [comment]
Presumed resolved
