### ISSUE TITLE
Characters missing in response

### ISSUE THREAD

**Issue by rehpa** [cmp-202/ssh2shell#82]
I've been testing this package to grab cert pem data with the openssl command in the ssh session.  When testing this I noticed I have issues with losing characters in the pem output that I get from the response.  

It seems any 'm' that is prefixed by an integer causes those two characters to be omitted in the output.

Example commands I've tested it with outside sending the pem data back.  The response to both these commands will be missing two characters ['2m','9m']

    commands: [
        "echo 'SG00K3g5Zk8wTGJFWUJSQ2lpMmZqVDlrVUdzam5xanNoQ0hwT3pTYThDaUd6SG5YQ0t0ei9mVEJH'",
        "echo 'ny1V++SWDdOVyaNOqTy0XZetwec2m4dtAHcAb1N2rDHwMRnYmQCkURX/dxUcEdkC'"
    ],

Any ideas on what might cause this and a way to work around it?

**Comment by cmp-202** [comment]
Hi,
[Here is the filtering options in the host config:](https://github.com/cmp-202/ssh2shell#text-regular-expression-filters)

```javeacript
//Optional: Regular expressions to clean output text
  asciiFilter:        "[^\r\n\x20-\x7e]", //removes non-standard ASCII
  disableColorFilter:  false, //turns colour filtering on and off
  textColorFilter:    "(\[{1}[0-9;]+m{1})" //removes colour formatting codes
```
It's the text color filter that is matching and removing it.
You can use the `host.disableColorFilter = true` to stop it from filtering.
You can disable/enable the filter in `host.onCommandComplete` event handler based on a conditional test.
See how that goes.

Andrew

**Comment by rehpa** [comment]
Thank you for pointing that out!  That resolved the issued I was having.
