### ISSUE TITLE
connect callback return the same sessionText 

### ISSUE THREAD

**Issue by Najmey** [cmp-202/ssh2shell#84]
Hi,
I use ssh2shell to get readings from linux service, these readings are updated periodically, so ssh connection is instanciated inside cron job schedule 1 hour timespan using node-cron, so when first timespan run I get the latest reading....and then I get the same result over and over.
after review debug event message, I found that in *** second run *** I get "No commands so exit" message, and same sessionText as  *** first run *** is returned.

this is the debug event track output :
*******************  first run **************************************
routine job started at :04/08/2021, 10:07:00  ----> printed to console from cron job
100.100.100.100: Load Defaults
100.100.100.100: initiate
100.100.100.100: eventName
100.100.100.100: Connection.connect
SSH Connected
100.100.100.100: Connection.ready
SSH Result Ready
100.100.100.100: Connection.shell
100.100.100.100: First prompt detected
100.100.100.100: Notifications: Normal Command to run
100.100.100.100: run command
100.100.100.100: Normal prompt detected
100.100.100.100: Raising commandComplete event
100.100.100.100: Class.commandComplete
100.100.100.100: Notifications: Normal Command to run
100.100.100.100: run command
Data processing: data received timeout
100.100.100.100: Normal prompt detected
100.100.100.100: Raising commandComplete event
100.100.100.100: Class.commandComplete
100.100.100.100: No commands so exit
100.100.100.100: Process an exit
100.100.100.100: Exit command: Stream: close
100.100.100.100: Stream.close
100.100.100.100: Stream.finish
100.100.100.100: Class.end
100.100.100.100: Clearing host event handlers
connected to db ----> printed to console
saved to db ----> printed to console

*******************  second run **************************************
routine job started at :04/08/2021, 11:07:00   ----> printed to console from cron job
100.100.100.100: Load Defaults
100.100.100.100: initiate
100.100.100.100: eventName
100.100.100.100: Connection.connect
SSH Connected
100.100.100.100: Connection.ready
SSH Result Ready
100.100.100.100: Connection.shell
100.100.100.100: First prompt detected
100.100.100.100: _**No commands so exit**_
100.100.100.100: Process an exit
100.100.100.100: Exit command: Stream: close
100.100.100.100: Stream.close
100.100.100.100: Stream.finish
100.100.100.100: Class.end
100.100.100.100: Clearing host event handlers
connected to db ----> printed to console
saved to db  ----> printed to console

*******************  third run **************************************
routine job started at :04/08/2021, 12:07:00   ----> printed to console from cron job
100.100.100.100: Load Defaults
100.100.100.100: initiate
100.100.100.100: eventName
100.100.100.100: Connection.connect
SSH Connected
100.100.100.100: Connection.ready
SSH Result Ready
100.100.100.100: Connection.shell
100.100.100.100: First prompt detected
100.100.100.100: _**No commands so exit**_
100.100.100.100: Process an exit
100.100.100.100: Exit command: Stream: close
100.100.100.100: Stream.close
100.100.100.100: Stream.finish
100.100.100.100: Class.end
100.100.100.100: Clearing host event handlers
connected to db  ----> printed to console

----------------------------cron job code:-----------------------------------
```
`class RoutineJobSchedule{
    constructor( ){
        var task = cron.schedule(' 7 * * * *', ( ) =>  {
        console.log('routine job started at :' +new Date( ).toLocaleString('en-GB', { timeZone: "Africa/Tripoli" }));
             new SSHConnect( );
        }, {
            scheduled: true,
            timezone: "Africa/Tripoli"
        });
        task.start( );
    }`


-----------------------------------------SSH connection code:---------------------------------------------
`class SSHConnect{
  
    constructor(){
      var SSH = new SSH2Shell(gurEpg);
      if(SSH.sshObj.debug){
        SSH.emit("msg", SSH.sshObj.server.host + ": eventName");
      }
      SSH._buffer = "";
      SSH.connect() ; 
      SSH.on('end',this.End);
      if(SSH.sshObj.debug){
           SSH.emit("msg", SSH.sshObj.server.host + ": eventName");
      }
    }
    
    End = function (sessionText,sshObj){
      this._buffer  ="";
      this.shellSummary = sessionText.split('\n').join().replace(/,/g,'').replace(/\s/g,"#").split('###').filter(e => e);
      categorize(this.shellSummary);
    }
  }`
----------------------------------------Host configs------------------------------------
`gurEpg: {
    server:        {     
      host: '100.100.100.100',
      port: "22",
      userName: 'name',
      password: 'pass'
    },
    debug:true,
    commands:      [ "start shell", "do_some_thing" ],
    streamEncoding:     "utf8",
    connectedMessage:    "SSH Connected",
  readyMessage:        "SSH Result Ready",
  asciiFilter:        "[^\r\n\x20-\x7e]", //removes non-standard ASCII
  disableColorFilter:  false, //turns colour filtering on and off
  textColorFilter:    "(\[{1}[0-9;]+m{1})", //removes colour formatting codes
  }`
```

**Comment by cmp-202** [comment]
Hi,
`gurEpg` might be the problem.
It sounds like the host config is having the commands removed as they are processed on the first run and but `gurEpg` remains persistent in the cron instance so no commands exist next time/s it runs unless we redefine `gurEpg`.

Try something like:
```javascript
class SSHConnect{  
    constructor(){
       //host config gurEpg is scoped to each run
       var gurEpg = {
             server:        {     
               host: '100.100.100.100',
               port: "22",
               userName: 'name',
               password: 'pass'
             },
             debug:true,
             commands:      [ 
                "msg:"+this.server.host + ": eventName", //look at message output methods 
                "start shell", 
                "do_some_thing",
                "msg:"+this.server.host + ": eventName"],
             connectedMessage:    "SSH Connected",
             readyMessage:        "SSH Result Ready"
             //don't duplicate defaults
       },
       SSH: new SSH2Shell(gurEpg),
       End: function (sessionText,sshObj){
            var shellSummary =sessionText.split('\n').join().replace(/,/g,'').replace(/\s/g,"#").split('###').filter(e => e);
            categorize(shellSummary);
       }
       SSH.on('end',End);
       SSH.connect() ; 
    } 
  }
```

**Comment by cmp-202** [comment]
On a side note, it would be interesting if you turn off debug and turn on verbose.
Verbose outputs the state of `this.sshObj` so you would see the incoming host config every time it is run.

**Comment by cmp-202** [comment]
https://stackoverflow.com/questions/13104494/does-javascript-pass-by-reference

**Comment by cmp-202** [comment]
If you have multiple servers to query each time you can use the multiple primary hosts method.

```javascript
gurEpg = {config};
gurEpg2 ={config};
gurEpg3 = {config};

SSH = new SSH2Shell([gurEpg, gurEpg1, gurEpg 2]);
var callback = function (sessionText){
            var shellSummary =sessionText.split('\n').join().replace(/,/g,'').replace(/\s/g,"#").split('###').filter(e => e);
            categorize(shellSummary);
       }
SSH.connect(callback);
```

See the tests folder `Multiple primary hosts.js` example.

**Comment by Najmey** [comment]
yep!
 worked by declaring host object within constructor
verbose output indicates that commands are existed in each run
you saved me...thank you.

**Comment by cmp-202** [comment]
Awesome glad it worked.
