### ISSUE TITLE
How support the japanese (euc-jp) encoding

### ISSUE THREAD

**Issue by 320IM** [cmp-202/ssh2shell#90]
How to support the japanese (euc-jp) encoding  ?
streamcoding : euc-jp ? seems not work

**Comment by cmp-202** [comment]
Hi,
See [Buffer encoding types](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings) for info on why it isn't working.

**Comment by 320IM** [comment]
Yeah, I see, Seems cannot Support euc-jp, Thanks

**Comment by 320IM** [comment]
when I console.log the ondata it can show the japanese charactors but for the 'response' of onCommandComplete cannot show the japanese charactors , is there anything else to deal with 'response' ?   Thanks in advance

**Comment by 320IM** [comment]
Here is my temp solution, can support showing the japanese charactors.
        onData: function( data123 ) {
            data12 += data123;
        },
        onCommandComplete: function(command, response, sshObj ) {
            console.log(data12);
}

**Comment by cmp-202** [comment]
I wonder if the ASCII filtering is doing it.

Try turning off ASCII filtering: `host.disableASCIIFilter = true`
If that works you could try modifying the ASCII filter with filtering turned back on: `host.asciiFilter = "[^\r\n]"`
I doubt it is the color filtering.

The buffer, apart from filtering, is only trimmed which I can't see affecting the output for you.
Passing a stream to the pipe functrion will also give you the raw data.

**Comment by 320IM** [comment]
disableASCIIFilter: true,   working awsome,  Thanks, Let me closed the ticket.
