### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by aggarwaldev** [cmp-202/ssh2shell#92]
Hey,

Is it possible to add TypeScript declarations to the package?

**Comment by cmp-202** [comment]
Hi,
I would not be able to put in the work and I think ssh2shell is trying to do too much as it is.
A new package that validates the host config, including event handlers, would have some benefits but again I am not able to do that work myself.
Sorry,

Andrew

**Comment by aggarwaldev** [comment]
Alright, thank you for letting me know.
