### ISSUE TITLE
SSH Connection Failed

### ISSUE THREAD

**Issue by dalgharib** [cmp-202/ssh2shell#95]
Hi,

We are developing Node js App which will connect to other devices (ex. Centos) and execute commands on it using SSH2SHELL. 
Some commands executed very well **except the commands that contains ssh word within its scripts**. These commands with ssh word is outputting "SSH Connection Failed" message.

Please Help!

**Comment by cmp-202** [comment]
Hi,
Ssh2shell detects and handles ssh connections as a core function and will be trying to use the credentials of the current host object to authenticate which in your case will fail.
There are a couple of options:

- Use [persistent-shell](https://github.com/cmp-202/persistent-shell) which doesn't handle it at all leaving you to run, detect and respond to ssh prompts yourself.
- Use [nested host configs](https://github.com/cmp-202/ssh2shell#tunnelling-nested-host-objects) to handle connections using multiple hosts, one host config for each connection rather than calling the ssh command in your scripts.

Using multiple hosts would look like this: `host1.hosts = [host2]` 
Host1 connects and runs its commands and then connects to host2 via ssh and runs its commands returning both session text content when it finishes.

**Comment by dalgharib** [comment]
Hi Andrew,

Thanks for your elaboration.

Actually, we are using SSH2SHELL to execute set of commands in one host at a time, and not nested hosts; however, some commands contain word 'ssh' in its scripts, (example: show ssh); these commands are returning "SSH Connection Failed" message.

What we are trying to do, is executing commands on a host and retrieving the output using SSH2SHELL, and then list the output and preview it in our page.

So, please advise to resolve this matter.

**Comment by cmp-202** [comment]
I have tweaked the SSH command detection so it is working now.
I tested using `echo SSH` and it wasn't treated as an SSH command.
Grab [ssh2shell.js](https://raw.githubusercontent.com/cmp-202/ssh2shell/master/lib/ssh2shell.js) and put it in ssh2shell/lib folder and try it. Once confirmed I will publish it to npm.
Thanks,

Andrew

**Comment by dalgharib** [comment]
Thanks Andrew for your prompt feedback,

We have tested the new ssh2shell.js file as you instructed; it solved the issue for the commands that have the `ssh` word at the end of it; HOWEVER, it still did not solve the problem for the commands that contain `ssh` word in the middle/first.

We are very keen to solve this issue, and continue using ssh2shell module since it is very powerful, interesting, and professional.

We will be awaiting your gentle response.

**Comment by cmp-202** [comment]
I have separated the ssh commands connecting hosts from the commands you set. It was a bit of a mission finding it all but I think I have it right now, fingers crossed. 
Again if you could try that file [ssh2shell.js](https://raw.githubusercontent.com/cmp-202/ssh2shell/master/lib/ssh2shell.js) and see how you go.
I used ssh2shell/test/tunneltest.js to test both multiple host configs connecting via the internal ssh command and ssh commands in each host config so I could confirm each nested host still handled manual ssh commands the same.
I used both `ssh -V` and `echo ssh` to check ssh in the two different positions without ssh2shell trying to handle it.
Thanks

Andrew

**Comment by cemres** [comment]
HI Andrew,

I was experiencing the same issue with "ssh" being on start/middle/end. 

Just for the update the last ssh2shell.js that you have provided seems to be working fine.

**Comment by cmp-202** [comment]
No Problem at all.
I will hold off on full tests until you have done those checks in case adjustments are needed.
Thanks,

Andrew

**Comment by cmp-202** [comment]
Wonderful thanks for bringing this to my attention I think it is a good correction separating automated host to host ssh connections from user-defined ssh related commands.
I will add a test file to cover it and run through the tests tonight.
Thanks,

Andrew

**Comment by dalgharib** [comment]
Hello,

We will process the testing and feed back.

However, we are facing a "MaxListenersExceededWarning" issue now, and It is really disturbing. This happens when we execute number of commands using ssh2shell, and it does not stop/exit the process since it is a warning. And, really we can`t find a way to git rid of it except using (require('events').EventEmitter.prototype._maxListeners(0)). but as we know setting the maxlisteners to unlimitid (0) is not a good practice; so we need to find out the number of events/ listeners required and then set it with _maxListeners in order to solve this warning in more professional way. Thus, is there a way to find the required number of events/listeners?

Sorry for mentioning this issue here, and we are ready to go with your recommendations.

Thanks,

**Comment by cmp-202** [comment]
What output do you get for `time node app.js` for your app?

**Comment by cmp-202** [comment]
I haven't done any research about this error but I have provided a bit more debug around listeners counts.
Is this with the new code versions or the first fix that worked with ssh?
I have added a list of each event handler and how many listeners are attached to each just prior to removing them.
Can you try [ssh2shell.js](https://raw.githubusercontent.com/cmp-202/ssh2shell/master/lib/ssh2shell.js) again and turn on debug in your host config `host.debug = true` to see it.

I am getting 9 listeners at the most when I run the `test/keyboard-interactivetest.js` test.
Remove listeners occurs with changes in hosts and the `stream.finish` event.

**Comment by cmp-202** [comment]
I had a look at [`event.defaultmaxlisteners()`](https://nodejs.org/api/events.html#eventsdefaultmaxlisteners) which apparently defaults to 10 listeners per event which is more than enough for a single instance of ssh2shell running commands on one host based on my debug numbers. 

`this._stream.setMaxListeners()` is not accessible until after the connection has been made and the `steam` is returned.
I do not recommend changing the `maxListeners`, I think finding which event is hitting the limit and finding where that is happening is the preferred solution.
Thanks,

Andrew

**Comment by cmp-202** [comment]
published to npm

**Comment by cmp-202** [comment]
Hi,Sorry I misunderstood.so your command is being flagged as an ssh command requiring authentication which fails.I will have a look at the test for that ssh command tomorrow.Andrew
