### ISSUE TITLE
Unhandled error Error: read ECONNRESET

### ISSUE THREAD

**Issue by chassy33** [cmp-202/ssh2shell#97]
I have a fairly simple app. I am using ssh2shell to run specific show commands on cisco routers. I create the host and specify the commands and the host IP and everything usually works. I have a `onEnd:`, `onError:`, and `onCommandTimeout:` event handlers configured. however if the error is ECONNRESET, I get the following debug output every time 

```
10.10.10.4: Load Defaults
10.10.10.4: Connection.connect
10.10.10.4: Connection.ready
10.10.10.4: Connection.shell
10.10.10.4: First prompt detected
10.10.10.4: Notifications: Normal Command to run
10.10.10.4: run command
10.10.10.4: Normal prompt detected
10.10.10.4: Raising commandComplete event
10.10.10.4: Class.commandComplete
10.10.10.4: Notifications: Normal Command to run
10.10.10.4: run command
Data processing: data received timeout
10.10.10.4: Normal prompt detected
10.10.10.4: Raising commandComplete event
10.10.10.4: Class.commandComplete
10.10.10.4: No commands so exit
10.10.10.4: Process an exit
10.10.10.4: Exit command: Stream: close
10.10.10.4: Stream.close
10.10.10.4: Stream.finish
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on SSH2Shell instance at:
    at Client.<anonymous> (c:\MyPrograms\JavaScript\Circuit_Generator\node_modules\ssh2shell\lib\ssh2shell.js:934:24)
    at Client.emit (events.js:315:20)
    at Socket.<anonymous> (c:\MyPrograms\JavaScript\Circuit_Generator\node_modules\ssh2\lib\client.js:745:12)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

Below are my test event handlers with simple console statements to see if that code block even runs (they don't):

```
            onEnd: function (sessionText, sshObj) {
                setTimeout(() => {
                    resolve(sessionText)
                }, 2000)
            },
            onError: function (error) {
                console.log('there was an error')
            },
            onCommandTimeout: function (command) {
                console.log('there was an timeout')

                reject('Timed Out!')

            }
```

I am just not sure how to handle the error since I already have an `onError:` event handler configured. Not sure if this is a user error (most likely) or what, but only this specific error causes problems and ends my app.

**Comment by cmp-202** [comment]
Hi,
Just a couple of things first re event handler definitions:

```javascript
onError:            function( err, type, close = false, callback ) {
   //Run when an error event is raised.
   //err: is either an Error object or a string containing the error message
   //type: is a string containing the error type
   //close: is a Boolean value indicating if the connection should be closed or not
   //callback: is the function to run when handling the error defined as function(err,type){}
   //if using this remember to handle closing the connection based on the close parameter.
   //To close the connection us this.connection.close()
  }

onCommandTimeout:    function( command, response, stream, connection ) {
   //Event is raised when a standard prompt is not detected and no data is 
   //received from the host within the host.idleTimeout value.
   //command: is the last command run or "" when first connected.
   //response: is the text received up to the time out.
   //stream: gives stream.write() access if a response is required outside the normal command flow.
   //connection: gives access to close the connection if all else fails
   //The timer can be reset from within this event in case a stream write gets no response.
  },
```

I couldn't repeat it with an ubuntu server host and using your handlers, I was unsure why your using a timer in your `onEnd`. Can you change to using a callback function to remove the event from the equation?


I have changed when the listeners are being cleared which was affecting both `error` and `msg` events after `stream.finish()`, `connection closed` was not showing in output.


Can you grab the [/lib/ssh2shell.js](https://github.com/cmp-202/ssh2shell/blob/master/lib/ssh2shell.js)  file and give it a try to see if there is any change?

**Comment by cmp-202** [comment]
Sorry just pushed that now.

**Comment by chassy33** [comment]
@cmp-202 Thanks for the quick reply and code change! I will give this a try in the morning and let you know. As for the setTimeout function that I am using, that's just to add a slight delay between devices. I was finding that without it, I would have other issues almost like it was trying the next device before fully closing the first device session (not completely sure, but adding a slight delay fixed that issue)

**Comment by cmp-202** [comment]
If you are connecting to multiple hosts are you using [ssh2shell multiple primary hosts](https://github.com/cmp-202/ssh2shell/blob/master/test/multiple_primary_hosts.js)  to handle it or doing it yourself?

**Comment by chassy33** [comment]
I am just handling it myself. I wrapped the SSH function in a promise wrapper so after it runs it returns a promise. I have have a pdf scrubber that pulls ip address and vlan info from the PDF, then adds it to an array. Then loops over the array and for each item it establishes a ssh session to the device and then manipulates the output before moving on to the next device. So it opens and closes a new session for each device one at a time. I thought about trying the host tunnelling, but honestly this is all new to me and that was alot more code I didn't know what it did.

**Comment by cmp-202** [comment]
Okay, I can understand that.

The multiple primary hosts is a bit simpler than tunneling.
If you can turn that array of host data from the pdf into an array of host objects and use that when you create the `SSH` instance it will do them one at a time. The full `sessionText` is returned at the end for all hosts.

You can create a generic host config common to all hosts and then make the array of hosts where you just add the server IP etc specific to the host object you are adding. 

If you need to manipulate text on all hosts the same way add the `onCommandComplete` or `onCommandProcessing` needed to process it is added to the generic host config. See the readme for a howto on that.

```javascript
//generic host config for all hosts as normal
var host = {...},
    hosts = []

//IP spacific
host1 = host;
host1.server.host = IP;
hosts.push(host1);
//same for other hosts or in your case iterate over PDF data

var SSH2Shell = require ('ssh2shell'),

    SSH = new SSH2Shell( hosts ),

    callback = function( sessionText ){
          console.log ( "-----Callback session text:\n" + sessionText);
          console.log ( "-----Callback end" );
    }

SSH.connect(callback);
```

**Comment by cmp-202** [comment]
The last couple of issues has shown up a problem with how the event listeners were cleared which is why your `onError` event failed. 
Switching between hosts now only clears the listeners that have handlers defined in the host object, like `host.onError`.
Instance event handlers are not removed and remain global to all hosts. 
`SSH.on('error', function(err, type, close = false, callback){... })`.
They should be working as intended now right the way through to `connection.close`.

Andrew

**Comment by chassy33** [comment]
Do I need to grab the ssh2shell.js file again for the above changes? also I have been testing with the new file and have not seen any issues when using it. I never see that same ECONNRESET error so thanks for fixing that!

**Comment by cmp-202** [comment]
I have made some other changes so grab it just in case.

I'm very pleased the error is resolved.

Andrew

**Comment by cmp-202** [comment]
Npm package has been updated to v2.0.4 with latest changes. New read.me on npm and git for easier access to information.
