### ISSUE TITLE
What is the default SSH2SHELL ALgorithms (Kex, cipher)

### ISSUE THREAD

**Issue by dalgharib** [cmp-202/ssh2shell#99]
Greetings,

We are using SSH2SHELL Library on our Nodejs App. We got an issue connecting to devices (Error: Handshake failed: no matching key exchange algorithm).

Accordingly, we are seeking the Default kex and cipher algorithms used by SSH2SHELL in order to compare with the device algorithms we need to ssh to it from our Nodejs app.

please, what is the default ALgorithms (Kex, cipher) used by ssh2shell?

Please support!

**Comment by cmp-202** [comment]
Hi
Read.me: [Default ciphers](https://github.com/cmp-202/ssh2shell#default-cyphers-)
SSH2: [Client methods](https://github.com/mscdex/ssh2#client-methods)
I hope this helps.
Andrew

**Comment by dalgharib** [comment]
Hi, I think the ciphers list in the Read.me:[Default ciphers](https://github.com/cmp-202/ssh2shell#default-cyphers-) is an example and no the full list. isn`t it?
As for those listed in SSH2: [Client methods](https://github.com/mscdex/ssh2#client-methods), is this list the default for ssh2shell. please support?

**Comment by cmp-202** [comment]
Yes, the SSH2.client default ciphers are the definitive list.
